import type { Metadata } from "next";
import Link from "next/link";
import { Breadcrumbs } from "@/components/Breadcrumbs";
import { ElectricChargingCalculator } from "@/components/ElectricChargingCalculator";
import { FaqSection } from "@/components/FaqSection";
import { pageMetadata } from "@/lib/site";

export const metadata: Metadata = pageMetadata({title:"Electric Motorcycle Charging Cost Calculator",description:"Estimate electric motorcycle charging cost in the Philippines from battery capacity, electricity rate, claimed range and daily distance.",path:"/tools/electric-motorcycle-charging-cost"});

export default function ElectricChargingCostPage(){return <section className="page shell"><Breadcrumbs items={[{label:"Tools",href:"/tools"},{label:"Electric charging cost"}]}/><div className="page-head"><span className="entity-kicker">Editable electricity estimate</span><h1>Electric motorcycle charging-cost calculator</h1><p>Enter the usable battery capacity, your electricity rate and expected range to estimate the cost of a full charge, 100 km and one month of riding.</p></div><ElectricChargingCalculator/><div className="source-panel"><h2>Use the battery setup you will actually ride</h2><p>A motorcycle with two 1.5 kWh batteries has 3 kWh of listed capacity. Use 1.5 kWh when riding with one battery and 3 kWh when charging both. The estimate does not include charging losses or a battery-subscription fee.</p><Link href="/motorcycles/electric/range-comparison">Compare battery capacity and range</Link></div><FaqSection title="Electric motorcycle charging questions" items={[{question:"How do I calculate the cost of charging an electric motorcycle?",answer:"Multiply battery capacity in kWh by the electricity rate per kWh. Actual wall consumption can be higher because charging is not perfectly efficient."},{question:"Does the calculator include battery subscription fees?",answer:"No. It estimates electricity only. Add any battery subscription, swapping, parking or service fees separately."},{question:"Why is actual range lower than the published figure?",answer:"Range changes with speed, traffic, hills, rider and cargo weight, tire pressure, temperature and battery condition."}]}/></section>;} 