import type { Metadata } from "next";
import Link from "next/link";
import { maintenanceSchedules, brandServiceResources } from "@/lib/maintenance";
import { getModelById } from "@/lib/data";
import { pageMetadata } from "@/lib/site";
import { Breadcrumbs } from "@/components/Breadcrumbs";
import { FaqSection } from "@/components/FaqSection";
export const metadata:Metadata=pageMetadata({title:"Motorcycle Maintenance Schedules Philippines",description:"Official Philippine motorcycle maintenance resources plus exact owner-manual intervals where available.",path:"/ownership/maintenance",index:true});
export default function MaintenanceHub(){return <section className="page shell"><Breadcrumbs items={[{label:"Ownership",href:"/ownership"},{label:"Maintenance"}]}/><div className="page-head"><h1>Use the exact motorcycle schedule—not a generic service interval</h1><p>Manufacturer service resources are shown separately from exact interval tables taken from owner manuals.</p></div><div className="section-head compact"><div><h2>Exact intervals currently available</h2></div></div><div className="topic-grid ownership-guide-grid">{maintenanceSchedules.map(s=>{const m=getModelById(s.modelId);return m?<Link className="ownership-guide-card" href={`/motorcycles/${m.makeSlug}/${m.slug}#maintenance`} key={s.modelId}><span>Owner manual</span><h2>{m.make} {m.model}</h2><p>{s.items.length} maintenance items with the original manual linked.</p><small className="verified-pill">Checked {s.lastChecked}</small></Link>:null})}</div><div className="section-head compact"><div><h2>Maintenance planners and service networks</h2></div></div><div className="source-ladder">{brandServiceResources.map(r=><article key={r.makeSlug}><span>{r.makeSlug}</span><div><h2>{r.label}</h2><small>Checked {r.lastChecked}</small></div><div><p>{r.description}</p><a className="text-link" href={r.url} target="_blank" rel="noreferrer">Open official resource ↗</a></div></article>)}</div><FaqSection title="Motorcycle maintenance questions" items={[{question:"Should every motorcycle use the same service interval?",answer:"No. Service intervals vary by model, engine and manufacturer. Use the exact owner manual or official maintenance planner for the motorcycle whenever one is available."},{question:"Are MotoIndex maintenance intervals generic estimates?",answer:"Manual-backed tables are labeled separately from general manufacturer service resources. When an exact model schedule is not available, MotoIndex links to the official brand resource instead of inventing an interval."},{question:"What should I do if the owner manual and a dealer recommendation differ?",answer:"Treat the owner manual and current manufacturer service information as the baseline, then ask the dealer to explain any additional recommendation based on local use, warranty or motorcycle condition."}]}/></section>}
