/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  poweredByHeader: false,
  output: "export",
  images: {
    unoptimized: true,
    formats: ["image/webp"],
    // Remote patterns remain only as a migration fallback if a local asset has not been synced yet.
    remotePatterns: [
      { protocol: "https", hostname: "bikeluggage.co.uk" },
      { protocol: "https", hostname: "cdn.aripitstop.com" },
      { protocol: "https", hostname: "cdn.awsli.com.br" },
      { protocol: "https", hostname: "cdn.idealo.com" },
      { protocol: "https", hostname: "cdn11.bigcommerce.com" },
      { protocol: "https", hostname: "dainese-cdn.thron.com" },
      { protocol: "https", hostname: "data.outletmoto.eu" },
      { protocol: "https", hostname: "down-ph.img.susercontent.com" },
      { protocol: "https", hostname: "easyr.com.au" },
      { protocol: "https", hostname: "evohelmet.com" },
      { protocol: "https", hostname: "gbrands.ph" },
      { protocol: "https", hostname: "images.ctfassets.net" },
      { protocol: "https", hostname: "kawasakileisurebikes.ph" },
      { protocol: "https", hostname: "kranosgears.com" },
      { protocol: "https", hostname: "kytasia.com" },
      { protocol: "https", hostname: "mc.suzuki.com.ph" },
      { protocol: "https", hostname: "motortrade.com.ph" },
      { protocol: "https", hostname: "platincdn.com" },
      { protocol: "https", hostname: "secmotosupply.com" },
      { protocol: "https", hostname: "shop.motoworld.com.ph" },
      { protocol: "https", hostname: "shopmotoman.com" },
      { protocol: "https", hostname: "teamgraphitee.com" },
      { protocol: "https", hostname: "tripleclampmoto.ca" },
      { protocol: "https", hostname: "vault.widen.net" },
      { protocol: "https", hostname: "wheeltek.com.ph" },
      { protocol: "https", hostname: "www.kawasakileisurebikes.ph" },
      { protocol: "https", hostname: "www.motoworld.com.ph" },
      { protocol: "https", hostname: "www.shoei-europe.com" },
      { protocol: "https", hostname: "www.teamspyder.com" },
      { protocol: "https", hostname: "www.tenplus.ph" },
    ],
  },
  experimental: { optimizePackageImports: [] },
};

export default nextConfig;
