import type { Metadata } from "next";
import { databaseConfigured } from "@/lib/db";
import { getVerifiedOffers } from "@/lib/persistentOffers";
import { offerCounts, sellerOffers } from "@/lib/offers";
import { commerceOfferFreshness, sourceBackedCommerceOffers } from "@/lib/commerceOffers";
import { php } from "@/lib/utils";
export const metadata:Metadata={title:"Offers Review",robots:{index:false,follow:false}};
export default async function OffersReview(){
  const persistent=databaseConfigured()?await getVerifiedOffers():[];
  const counts=offerCounts();
  const rows=persistent.length?persistent:sellerOffers;
  const sourceRows=sourceBackedCommerceOffers.sort((a,b)=>b.observedAt.localeCompare(a.observedAt));
  return <section className="page shell"><div className="page-head"><h1>Published offer review</h1><p>{persistent.length?"Showing verified offers currently published from the database ingestion workflow.":"Database is not connected or has no verified offers yet; legacy demo rows remain isolated from the public verified-commerce layer."}</p></div><div className="health-summary"><div><span>Visible review rows</span><strong>{rows.length}</strong></div><div><span>Database verified</span><strong>{persistent.length}</strong></div><div><span>Source-backed accessory offers</span><strong>{sourceRows.length}</strong></div><div><span>Legacy expired</span><strong>{persistent.length?0:counts.expired||0}</strong></div></div><div className="admin-table"><div className="admin-row offer-admin-head"><span>Entity / seller</span><span>Price</span><span>Status</span><span>Observed</span></div>{rows.map((o:any)=><div className="admin-row" key={o.id}><span><b>{o.entityId}</b><small>{o.sellerName} · {o.entityType}</small></span><span>{o.pricePhp?php(o.pricePhp):"—"}</span><span><em className={`offer-status ${o.status}`}>{o.status}</em></span><span>{o.observedAt}</span></div>)}</div><div className="note-box"><h2>Source-backed accessory observations</h2><p>These rows are generated only from verified catalog products that already have a dated Philippine price source. They expire from public comparison blocks after the commerce freshness window and never fabricate extra merchants.</p><div className="admin-table"><div className="admin-row offer-admin-head"><span>Entity / merchant</span><span>Price</span><span>Freshness</span><span>Source</span></div>{sourceRows.map((o)=><div className="admin-row" key={o.id}><span><b>{o.entityId}</b><small>{o.sellerName} · {o.entityType}</small></span><span>{o.pricePhp?php(o.pricePhp):"—"}</span><span><b>{commerceOfferFreshness(o).label}</b><small>{o.observedAt}</small></span><span>{o.targetUrl?<a className="text-link" href={o.targetUrl} target="_blank" rel="noreferrer">Open source ↗</a>:"Missing"}</span></div>)}</div></div><div className="note-box"><h2>Verification checklist</h2><p>Confirm exact model/SKU, seller identity, tax/fees, stock state, financing assumptions, source URL and observed timestamp. Use the ingestion queue for row-level approvals and the expiry control for stale records. Affiliate status must never change editorial ordering.</p></div></section>
}
