import type { Metadata } from "next";
import Link from "next/link";
import { pageMetadata } from "@/lib/site";
import { Breadcrumbs } from "@/components/Breadcrumbs";
import { JsonLd } from "@/components/JsonLd";
import { articleSchema } from "@/lib/articleSchema";

export const metadata:Metadata=pageMetadata({title:"Rainy Season Motorcycle Commute Checklist Philippines",description:"Practical rainy-season motorcycle commuting checks for tires, braking, visibility, rain gear, water exposure and post-ride inspection.",path:"/commute/rainy-season",index:true});
export default function Page(){const rainyArticle=articleSchema({headline:"Rainy season motorcycle commute checklist for the Philippines",description:"Practical rainy-season riding guidance for Philippine commuters: visibility, tires, braking distance and gear.",path:"/commute/rainy-season",about:"rainy season motorcycle riding Philippines",keywords:["motorcycle rainy season Philippines","wet weather motorcycle riding tips","monsoon motorcycle commute"]});return <section className="page shell"><Breadcrumbs items={[{label:"Commuting",href:"/commute"},{label:"Rainy season"}]}/><div className="page-head"><h1>Prepare the motorcycle for rain—not for guessed flood depth.</h1><p>Ground clearance is not a flood-depth rating. Water depth, intake location, electronics, current, road damage and manufacturer limits matter far more than one chassis number.</p></div><div className="rain-check-grid"><article><span>01</span><h2>Tires first</h2><p>Check pressure, tread, age and damage. Use the model&apos;s stock-size page before shopping for replacements.</p><Link href="/fitment">Open tire fitment →</Link></article><article><span>02</span><h2>Braking + visibility</h2><p>Make sure lamps, brake controls and tires are in good condition. ABS can help in some braking situations, but it does not create wet-road grip.</p><Link href="/recommendations#safety-efficiency">Browse ABS-equipped models →</Link></article><article><span>03</span><h2>Pack actual rain gear</h2><p>Prioritize visibility, waterproof coverage and a secure fit that cannot interfere with controls or wheels.</p><Link href="/accessories/rain-gear">Rain gear →</Link></article><article><span>04</span><h2>Do not infer wading depth</h2><p>Ground clearance is useful for pothole/obstacle context. It is not a manufacturer-approved water-fording depth.</p><Link href="/motorcycles">Check model specs →</Link></article><article><span>05</span><h2>After heavy rain</h2><p>Inspect brakes, chain where applicable, controls, tires and any water intrusion. Follow the manufacturer&apos;s service guidance after abnormal exposure.</p><Link href="/ownership/maintenance">Maintenance resources →</Link></article><article><span>06</span><h2>Keep registration current</h2><p>LTO continues active enforcement against unregistered vehicles. Keep registration and required documents in order before daily use.</p><a href="https://lto.gov.ph/news/lto-warns-of-impounding-unregistered-motor-vehicles-as-over-20000-with-expired-registration-apprehended-in-june-2025/" target="_blank" rel="noreferrer">LTO guidance ↗</a></article></div><div className="note-box"><h2>When the road is flooded</h2><p>If depth, current, road surface or hidden hazards are uncertain, the safer decision can be not to enter. This page deliberately avoids giving a universal “safe water depth” for motorcycles.</p></div><JsonLd data={rainyArticle} /></section>}
