import type { Metadata } from "next";
import Link from "next/link";
import { pageMetadata } from "@/lib/site";
import { commuteGuides } from "@/lib/commute";
import { publicMotorcycles } from "@/lib/data";

export const metadata:Metadata=pageMetadata({title:"Motorcycle Commuting Philippines — Traffic & Cost Tools",description:"Motorcycle commute tools for traffic, affordability, daily fuel cost, work riding, passenger use and rainy-season preparation in the Philippines.",path:"/commute",index:true});

export default function CommutePage(){return <section className="page shell"><div className="page-head"><h1>Compare motorcycles for traffic, budget and daily use.</h1><p>Purchase price is only part of a commute. Weight, transmission, fuel use, distance, parking, passenger needs and wet-season riding all affect day-to-day cost and convenience.</p></div><div className="commute-hero-grid"><div className="commute-context"><h2>Congestion changes what matters in a daily motorcycle.</h2><p>A 2025 Senate filing citing the 2024 TomTom Traffic Index placed Davao, Manila and Caloocan among cities with high rush-hour time losses. These tools do not assume a motorcycle removes congestion; they focus on costs and specifications a buyer can compare.</p><div className="source-links"><a href="https://legacy.senate.gov.ph/lisdata/4774243764%21.pdf" target="_blank" rel="noreferrer">Senate / traffic source ↗</a><a href="https://new.doe.gov.ph/prices" target="_blank" rel="noreferrer">DOE fuel-price monitors ↗</a></div></div><div className="commute-stat-stack"><span><small>Current motorcycles</small><b>{publicMotorcycles.length}</b></span><span><small>Default distance</small><b>20 km/day · 22 days</b></span><span><small>Fuel price</small><b>Editable</b></span></div></div><div className="section-head"><div><h2>Start with your own numbers</h2></div></div><div className="commute-tool-grid"><Link href="/commute/cost-calculator"><span>01</span><h3>Daily commute cost</h3><p>Estimate fuel, maintenance reserve, parking and cost per workday for any current motorcycle.</p></Link><Link href="/commute/affordability"><span>02</span><h3>Affordability ceiling</h3><p>Set take-home pay, a monthly cap, running-cost reserve, down payment, APR and term.</p></Link><Link href="/finder"><span>03</span><h3>Motorcycle finder</h3><p>Filter by traffic, inseam, passenger use, transmission, weight, seat height and budget.</p></Link></div><div className="section-head commute-section-head"><div><h2>Compare by everyday use</h2></div></div><div className="commute-guide-grid">{commuteGuides.map(g=><Link href={`/commute/${g.slug}`} key={g.slug}><h3>{g.title}</h3><p>{g.description}</p></Link>)}<Link href="/commute/rainy-season"><span>Wet-season prep</span><h3>Rainy-season motorcycle commute checklist</h3><p>Visibility, tires, braking, rain gear, water exposure and what ground-clearance numbers do not tell you.</p></Link></div><div className="note-box"><h2>Specs do not equal safety</h2><p>Low weight, automatic transmission and good fuel economy can make stop-go use easier, but they do not prove a motorcycle is safer or faster through traffic. Test ergonomics in person and ride within the law.</p></div></section>}
