"use client";
import { useMemo, useState } from "react";
import Link from "next/link";
import type { Motorcycle } from "@/lib/types";
import { maxPurchasePriceFromBudget } from "@/lib/commuteMath";
import { observedMarketRange, observedMarketPriceLabel } from "@/lib/marketChecks";

export function AffordabilityCalculator({models}:{models:Motorcycle[]}){
  const [income,setIncome]=useState(30000),[share,setShare]=useState(20),[running,setRunning]=useState(2500),[down,setDown]=useState(20000),[apr,setApr]=useState(12),[term,setTerm]=useState(36);
  const result=useMemo(()=>maxPurchasePriceFromBudget(income,share,running,down,apr,term),[income,share,running,down,apr,term]);
  const matches=useMemo(()=>models.filter(m=>observedMarketRange(m).from<=result.maxPurchasePrice).sort((a,b)=>observedMarketRange(a).from-observedMarketRange(b).from).slice(0,12),[models,result.maxPurchasePrice]);
  return <div className="affordability-tool"><div className="affordability-copy"><h2>Estimate a purchase-price ceiling from your monthly budget</h2><p>Choose the monthly cap, running-cost reserve, down payment, rate and term yourself. The calculator works backward to an estimated purchase-price ceiling.</p><div className="affordability-total"><small>Maximum modeled purchase price</small><strong>₱{(Math.floor(result.maxPurchasePrice/100)*100).toLocaleString()}</strong></div></div><div className="affordability-fields"><label>Monthly take-home pay <b>₱{income.toLocaleString()}</b><input type="range" min="10000" max="150000" step="1000" value={income} onChange={e=>setIncome(Number(e.target.value))}/></label><label>Your motorcycle budget cap <b>{share}% of take-home</b><input type="range" min="5" max="50" step="1" value={share} onChange={e=>setShare(Number(e.target.value))}/></label><label>Running-cost reserve <b>₱{running.toLocaleString()}/mo</b><input type="range" min="0" max="12000" step="250" value={running} onChange={e=>setRunning(Number(e.target.value))}/></label><label>Cash down payment <b>₱{down.toLocaleString()}</b><input type="range" min="0" max="150000" step="5000" value={down} onChange={e=>setDown(Number(e.target.value))}/></label><label>APR assumption <b>{apr}%</b><input type="range" min="0" max="36" step="1" value={apr} onChange={e=>setApr(Number(e.target.value))}/></label><label>Loan term<select value={term} onChange={e=>setTerm(Number(e.target.value))}><option value="12">12 months</option><option value="24">24 months</option><option value="36">36 months</option></select></label></div><div className="affordability-kpis"><span><small>Total monthly cap</small><b>₱{Math.round(result.totalMonthlyBudget).toLocaleString()}</b></span><span><small>Available for payment</small><b>₱{Math.round(result.paymentBudget).toLocaleString()}</b></span><span><small>Modeled financed principal</small><b>₱{Math.round(result.principal).toLocaleString()}</b></span><span><small>Models under ceiling</small><b>{matches.length}</b></span></div><div className="affordable-models">{matches.map(m=><Link key={m.id} href={`/motorcycles/${m.makeSlug}/${m.slug}`}><span><b>{m.make} {m.model}</b><small>{m.category}</small></span><strong>{observedMarketPriceLabel(m)}</strong></Link>)}</div><div className="note-box compact-note"><p><b>Estimate only.</b> This is not financial advice and does not include dealer fees, compulsory products, late charges or lender-specific rules. Use the actual disclosure statement from your lender before signing.</p></div></div>;
}
