"use client";
import { useMemo, useState } from "react";

const sample=`sellerSlug,entityType,entityId,pricePhp,downpaymentPhp,monthlyPhp,termMonths,availability,observedAt,sourceUrl,affiliateUrl\ndemo-yamaha-dealer-a,motorcycle,yamaha-aerox-v3,125900,25000,5850,24,In stock,2026-08-24,,`;
function parseCsv(input:string){const lines=input.trim().split(/\r?\n/).filter(Boolean);if(lines.length<2)return[];const heads=lines[0].split(",").map(x=>x.trim());return lines.slice(1).map(line=>{const vals=line.split(",");return Object.fromEntries(heads.map((h,i)=>[h,(vals[i]||"").trim()]));});}

export function OfferImportPreview(){
  const [csv,setCsv]=useState(sample),[sourceLabel,setSourceLabel]=useState("Manual partner import"),[sourceUrl,setSourceUrl]=useState(""),[result,setResult]=useState<any>(null),[busy,setBusy]=useState(false);
  const rows=useMemo(()=>parseCsv(csv),[csv]);
  async function call(url:string,body:any){setBusy(true);try{const r=await fetch(url,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const j=await r.json();setResult(j);if(!r.ok)throw new Error(j.error||"Request failed");window.dispatchEvent(new Event("motoindex-ingestion-refresh"));}catch(e){setResult({error:e instanceof Error?e.message:"Request failed"});}finally{setBusy(false)}}
  return <div className="ingest-grid"><div><label className="field-label">Source label<input value={sourceLabel} onChange={e=>setSourceLabel(e.target.value)}/></label><label className="field-label">Source URL (optional)<input value={sourceUrl} onChange={e=>setSourceUrl(e.target.value)} placeholder="https://seller.example/inventory"/></label><label className="field-label">CSV offer rows<textarea value={csv} onChange={e=>setCsv(e.target.value)} rows={12}/></label><div className="hero-actions"><button className="button" disabled={busy} onClick={()=>call("/api/ingestion/validate",{rows})}>Validate {rows.length} rows</button><button className="button" disabled={busy||!rows.length||!sourceLabel.trim()} onClick={()=>call("/api/ingestion/stage",{sourceLabel,sourceUrl,rows})}>Stage to database</button><button className="button ghost on-light" onClick={()=>setCsv(sample)}>Reset sample</button></div><small className="muted-note">Staging persists rows but never publishes them. Every row must pass catalog/seller matching and explicit review first.</small></div><div className="ingest-result">{result?.error?<><h3>Could not continue</h3><p>{result.error}</p></>:result?.batch?<><h3>Batch staged</h3><p>{result.batch.rowCount} rows saved · {result.batch.errorCount} need review.</p><small>Batch {result.batch.id}</small></>:result?<><h3>{result.validRows} valid · {result.invalidRows} invalid</h3><div className="issue-list">{(result.results||[]).map((x:any)=><div key={x.index} className={x.ok?"issue-ok":"issue-bad"}><b>Row {x.index+2}</b><span>{x.ok?"Ready for staging":x.issues.join(" · ")}</span></div>)}</div></>:<><h3>Validate, then stage</h3><p>Rows are checked before they are persisted. Staging also matches each seller slug and MotoIndex catalog entity so bad IDs cannot be approved accidentally.</p></>}</div></div>
}
