"use client";
import { useCallback, useEffect, useState } from "react";

export function OfferIngestionQueue(){
  const [data,setData]=useState<any>({batches:[]}),[busy,setBusy]=useState("");
  const load=useCallback(async()=>{const r=await fetch("/api/ingestion/batches",{cache:"no-store"});setData(await r.json());},[]);
  useEffect(()=>{load();const h=()=>load();window.addEventListener("motoindex-ingestion-refresh",h);return()=>window.removeEventListener("motoindex-ingestion-refresh",h)},[load]);
  async function post(url:string,body:any={}){setBusy(url+JSON.stringify(body));try{const r=await fetch(url,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)alert(j.error||"Request failed");await load();}finally{setBusy("")}}
  if(!data.databaseConfigured)return <div className="note-box"><h2>Database not connected</h2><p>Set <code>DATABASE_URL</code>, run <code>npm run db:migrate</code>, and reload this page. CSV validation remains available without a database, but staging, review, publishing and expiry require Postgres.</p></div>;
  return <div className="admin-stack"><div className="section-head compact"><div><h2>Persistent import queue</h2><p>Approve only rows with clean seller and entity matches. Publishing is explicit and appends price history.</p></div><button className="button ghost on-light" onClick={()=>post("/api/ingestion/expire",{maxAgeDays:30})}>Expire stale offers</button></div>{!data.batches?.length?<div className="note-box"><p>No staged batches yet.</p></div>:data.batches.map((b:any)=><article className="note-box" key={b.id}><div className="section-head compact"><div><h3>{b.sourceLabel}</h3><p>{b.rowCount} rows · {b.approvedCount} approved · {b.rejectedCount} rejected · status: <strong>{b.status}</strong></p></div>{b.approvedCount>0&&b.status!=="published"?<button className="button" disabled={!!busy} onClick={()=>post(`/api/ingestion/batches/${b.id}/publish`)}>Publish approved</button>:null}</div><div className="admin-table"><div className="admin-row offer-admin-head"><span>Row / entity</span><span>Price</span><span>Match</span><span>Review</span></div>{b.rows.map((r:any)=><div className="admin-row" key={r.id}><span><b>#{r.rowNumber} {r.entityId}</b><small>{r.sellerSlug} · {r.entityType}</small></span><span>{r.pricePhp?`₱${Number(r.pricePhp).toLocaleString("en-PH")}`:"—"}</span><span>{r.issues?.length?<small className="issue-bad">{r.issues.join(" · ")}</small>:<small className="issue-ok">{r.matchedEntityLabel}</small>}</span><span>{r.status==="published"?<b>Published</b>:r.status==="approved"?<><b>Approved</b><button className="text-button" onClick={()=>post(`/api/ingestion/batches/${b.id}/review`,{rowId:r.id,status:"rejected"})}>Reject</button></>:r.status==="rejected"?<b>Rejected</b>:<div className="hero-actions"><button className="text-button" disabled={!!busy||r.issues?.length} onClick={()=>post(`/api/ingestion/batches/${b.id}/review`,{rowId:r.id,status:"approved"})}>Approve</button><button className="text-button" disabled={!!busy} onClick={()=>post(`/api/ingestion/batches/${b.id}/review`,{rowId:r.id,status:"rejected"})}>Reject</button></div>}</span></div>)}</div></article>)}</div>
}
