import type { Metadata } from "next";
import Link from "next/link";
import { Breadcrumbs } from "@/components/Breadcrumbs";
import { LoanCalculatorFromUrl } from "@/components/LoanCalculatorFromUrl";
import { pageMetadata } from "@/lib/site";
import { FaqSection } from "@/components/FaqSection";

export const metadata: Metadata = pageMetadata({ title: "Motorcycle Loan Calculator Philippines", description: "Estimate motorcycle monthly payments in the Philippines by cash price, down payment, loan term and annual interest rate.", path: "/tools/motorcycle-loan-calculator" });

export default function MotorcycleLoanCalculatorPage() {
  return <section className="page shell"><Breadcrumbs items={[{label:"Tools",href:"/tools"},{label:"Loan calculator"}]}/><div className="page-head"><h1>Motorcycle loan calculator Philippines</h1><p>Estimate a monthly motorcycle payment from the purchase price, down payment, term and annual rate. Every input is editable and saved in the URL so you can return to or share the exact scenario.</p></div><LoanCalculatorFromUrl/><div className="source-panel"><h2>How to use the estimate</h2><p>Use the calculator for side-by-side planning, then ask the lender for the cash price, down payment, financed principal, effective interest or add-on rate, loan term, processing fees, insurance and total amount payable. A lower advertised monthly amount can still cost more overall if the term or fees are higher.</p><div className="tool-crosslinks"><Link href="/tools/lto-registration-fee-calculator"><b>LTO registration budget</b><small>Add registration costs to your purchase plan.</small></Link><Link href="/tools/motorcycle-insurance-calculator"><b>Insurance budget</b><small>Estimate CTPL and comprehensive planning costs.</small></Link><Link href="/motorcycles"><b>Motorcycle prices</b><small>Open a model and load its current price into this calculator.</small></Link></div></div><FaqSection title="Motorcycle financing questions" items={[{question:"What numbers should I copy from a dealer loan quote?",answer:"Use the actual cash price, down payment, financed principal, annual rate or equivalent rate basis, term and all required fees. Compare total amount payable as well as the monthly payment."},{question:"Does a lower monthly payment mean a cheaper motorcycle loan?",answer:"Not necessarily. A longer term can reduce the monthly payment while increasing the total amount paid. Compare the full repayment amount and fees."},{question:"Is this calculator a lender approval or quotation?",answer:"No. It is an estimate for planning and comparison. Approval, rates, fees and final payment schedules come from the lender or dealer."}]}/></section>;
}
