import type { Motorcycle } from "./types";

const verifiedAt = "2026-10-04";

// Fresh closeout pass after the October 2026 ZigWheels keyword audit.
// Only models with defensible current Philippine-market evidence are added here.
export const currentModelGapOct2026: Motorcycle[] = [
  {
    id: "honda-crf300l",
    alsoKnownAs: ["Honda CRF300L", "CRF 300L", "CRF300L"],
    make: "Honda",
    makeSlug: "honda",
    model: "CRF300L",
    slug: "crf300l",
    generation: "Current Philippine model",
    marketStatus: "current",
    category: "Dual-sport",
    srp: 269900,
    engineCc: 286,
    powerHp: 26.2,
    torqueNm: 26.1,
    curbWeightKg: 138,
    seatHeightMm: 882,
    fuelTankL: 7.8,
    fuelConsumptionKmL: 29.5,
    groundClearanceMm: 284,
    frontTire: "80/100-21",
    rearTire: "120/80-18",
    abs: "ABS; front and rear disc brakes",
    colors: ["Extreme Red"],
    searchVolume: 900,
    keywordDifficulty: 6,
    sourceLabel: "Honda Philippines CRF300L launch/current-market reference with 2026 Philippine specification cross-check",
    sourceUrl: "https://www.hondaph.com/motorcycle/news/honda-philippines-unleashes-power-and-innovation-at-the-action-packed-inside-racing-bikefest-2025",
    verifiedAt,
    freshness: "verified",
    marketPriceSourceLabel: "Current Philippine CRF300L price listing",
    marketPriceSourceUrl: "https://www.zigwheels.ph/new-motorcycles/honda/crf300l/price",
    marketPriceCheckedAt: verifiedAt,
    priceContext: "Honda Philippines listed the CRF300L at ₱269,900 in its 2025 Philippine off-road lineup, and current 2026 Philippine market listings continue to show ₱269,900. Confirm final dealer stock and quote before purchase.",
    transmission: "Manual",
    summary: "Current Philippine 286cc dual-sport with 26.2 hp, 26.1 Nm, a 7.8 L tank, 21/18-inch wheels, 284 mm ground clearance and ₱269,900 current market price."
  },
  {
    id: "kawasaki-klx140r-f",
    alsoKnownAs: ["Kawasaki KLX 140", "KLX 140", "KLX140R F", "KLX 140R F"],
    make: "Kawasaki",
    makeSlug: "kawasaki",
    model: "KLX140R F",
    slug: "klx140r-f",
    generation: "2026 Philippine model",
    marketStatus: "current",
    category: "Off-road trail bike",
    srp: 162000,
    engineCc: 144,
    powerHp: 10.9,
    torqueNm: 12,
    curbWeightKg: 99,
    seatHeightMm: 860,
    fuelTankL: 5.8,
    groundClearanceMm: 315,
    frontTire: "2.75-21",
    rearTire: "4.10-18",
    abs: "No ABS; front and rear petal disc brakes",
    colors: ["Lime Green"],
    searchVolume: 900,
    keywordDifficulty: 6,
    sourceLabel: "Kawasaki Philippines 2026 KLX140R F product, price and specification page",
    sourceUrl: "https://www.kawasaki-lifestyle.com/en/motorcycles/klx/klx140r-f-2026.html",
    verifiedAt,
    freshness: "verified",
    marketPriceSourceLabel: "Kawasaki Philippines",
    marketPriceSourceUrl: "https://www.kawasaki-lifestyle.com/en/motorcycles/klx/klx140r-f-2026.html",
    marketPriceCheckedAt: verifiedAt,
    priceContext: "Kawasaki's Philippine 2026 product page lists the KLX140R F at ₱162,000. This is an off-road trail motorcycle; verify the intended use, transport and registration requirements before purchase.",
    transmission: "Manual",
    summary: "Current 2026 Philippine 144cc full-size-wheel trail bike with a 5-speed manual transmission, 21/18-inch wheels, 860 mm seat, 315 mm ground clearance and ₱162,000 official price."
  }
];
