import type { Motorcycle } from "./types";

const verifiedAt = "2026-10-04";

export const currentModelGapCloseout2026: Motorcycle[] = [
  {
    id: "honda-crf300l",
    alsoKnownAs: ["Honda CRF 300L", "CRF 300L"],
    make: "Honda",
    makeSlug: "honda",
    model: "CRF300L",
    slug: "crf300l",
    generation: "Current Philippine 286cc generation",
    category: "Dual-sport",
    srp: 269900,
    engineCc: 286,
    powerHp: 26.3,
    torqueNm: 26.1,
    curbWeightKg: 138,
    seatHeightMm: 882,
    fuelTankL: 7.8,
    fuelConsumptionKmL: 29.5,
    groundClearanceMm: 284,
    frontTire: "80/100-21",
    rearTire: "120/80-18",
    abs: "Front and rear disc brakes; current international CRF300L specification includes ABS, confirm exact Philippine unit",
    colors: ["Extreme Red"],
    searchVolume: 900,
    keywordDifficulty: 6,
    sourceLabel: "Honda Philippines 2025 CRF300L launch and Philippine-market specification cross-check",
    sourceUrl: "https://www.hondaph.com/motorcycle/news/honda-philippines-unleashes-power-and-innovation-at-the-action-packed-inside-racing-bikefest-2025",
    verifiedAt,
    freshness: "verified",
    marketStatus: "current",
    marketPriceSourceLabel: "Honda Philippines",
    marketPriceSourceUrl: "https://www.hondaph.com/motorcycle/news/honda-philippines-unleashes-power-and-innovation-at-the-action-packed-inside-racing-bikefest-2025",
    marketPriceCheckedAt: verifiedAt,
    priceContext: "Honda Philippines launched the CRF300L at ₱269,900 in March 2025. Current Philippine market listings still show the model at that price; confirm dealer stock, exact model year and final quote before purchase.",
    transmission: "Manual",
    summary: "Current Philippine 286cc dual-sport with 19.6 kW official Philippine output, 26.1 Nm, 882 mm seat, 138 kg Philippine-market listed curb weight, 21/18-inch wheels and 284 mm ground clearance."
  },
  {
    id: "kawasaki-klx-140",
    alsoKnownAs: ["Kawasaki KLX140", "KLX140"],
    make: "Kawasaki",
    makeSlug: "kawasaki",
    model: "KLX 140",
    slug: "klx-140",
    generation: "Current Philippine model",
    category: "Off-road trail bike",
    srp: 160000,
    engineCc: 144,
    powerHp: 11.93,
    torqueNm: 11.3,
    curbWeightKg: 99,
    seatHeightMm: 780,
    fuelTankL: 5.8,
    groundClearanceMm: 236,
    frontTire: "70/100-17",
    rearTire: "90/100-14",
    abs: "No ABS stated by Kawasaki Philippines; front and rear disc brakes",
    colors: [],
    searchVolume: 900,
    keywordDifficulty: 6,
    sourceLabel: "Kawasaki Leisure Bikes Philippines current KLX 140 product page and Philippine specification cross-check",
    sourceUrl: "https://kawasakileisurebikes.ph/motorcycles/kx-series/klx-140/",
    verifiedAt,
    freshness: "verified",
    marketStatus: "current",
    marketPriceSourceLabel: "Kawasaki Leisure Bikes Philippines",
    marketPriceSourceUrl: "https://kawasakileisurebikes.ph/motorcycles/kx-series/klx-140/",
    marketPriceCheckedAt: verifiedAt,
    priceContext: "Kawasaki Leisure Bikes Philippines currently lists the KLX 140 at ₱160,000 MSRP, excluding freight and other charges. Philippine comparison listings show ₱162,000, so confirm the dealer quote before purchase.",
    transmission: "Manual",
    summary: "Current 144cc off-road trail bike with 11.93 hp, 11.3 Nm, 99 kg curb mass, 780 mm seat, 17/14-inch wheels and dual disc brakes."
  }
];
