import type { Motorcycle } from "./types";

const verifiedAt = "2026-10-04";

export const currentModelGapCloseout2026: Motorcycle[] = [
  {
    id: "honda-crf300l",
    alsoKnownAs: ["Honda CRF 300L", "CRF 300L"],
    make: "Honda",
    makeSlug: "honda",
    model: "CRF300L",
    slug: "crf300l",
    generation: "Current Philippine 286cc generation",
    category: "Dual-sport",
    srp: 269900,
    engineCc: 286,
    powerHp: 26.3,
    torqueNm: 26.1,
    curbWeightKg: 138,
    seatHeightMm: 882,
    fuelTankL: 7.8,
    fuelConsumptionKmL: 29.5,
    groundClearanceMm: 284,
    frontTire: "80/100-21",
    rearTire: "120/80-18",
    abs: "Front and rear disc brakes; current international CRF300L specification includes ABS, confirm exact Philippine unit",
    colors: ["Extreme Red"],
    searchVolume: 900,
    keywordDifficulty: 6,
    sourceLabel: "Honda Philippines 2025 CRF300L launch and Philippine-market specification cross-check",
    sourceUrl: "https://www.hondaph.com/motorcycle/news/honda-philippines-unleashes-power-and-innovation-at-the-action-packed-inside-racing-bikefest-2025",
    verifiedAt,
    freshness: "verified",
    marketStatus: "current",
    marketPriceSourceLabel: "Honda Philippines",
    marketPriceSourceUrl: "https://www.hondaph.com/motorcycle/news/honda-philippines-unleashes-power-and-innovation-at-the-action-packed-inside-racing-bikefest-2025",
    marketPriceCheckedAt: verifiedAt,
    priceContext: "Honda Philippines launched the CRF300L at ₱269,900 in March 2025. Current Philippine market listings still show the model at that price; confirm dealer stock, exact model year and final quote before purchase.",
    transmission: "Manual",
    summary: "Current Philippine 286cc dual-sport with 19.6 kW official Philippine output, 26.1 Nm, 882 mm seat, 138 kg Philippine-market listed curb weight, 21/18-inch wheels and 284 mm ground clearance."
  },
  {
    id: "kawasaki-klx-140",
    alsoKnownAs: ["Kawasaki KLX140", "KLX140"],
    make: "Kawasaki",
    makeSlug: "kawasaki",
    model: "KLX 140",
    slug: "klx-140",
    generation: "Current Philippine model",
    category: "Off-road trail bike",
    srp: 160000,
    engineCc: 144,
    powerHp: 11.93,
    torqueNm: 11.3,
    curbWeightKg: 99,
    seatHeightMm: 780,
    fuelTankL: 5.8,
    groundClearanceMm: 236,
    frontTire: "70/100-17",
    rearTire: "90/100-14",
    abs: "No ABS stated by Kawasaki Philippines; front and rear disc brakes",
    colors: [],
    searchVolume: 900,
    keywordDifficulty: 6,
    sourceLabel: "Kawasaki Leisure Bikes Philippines current KLX 140 product page and Philippine specification cross-check",
    sourceUrl: "https://kawasakileisurebikes.ph/motorcycles/kx-series/klx-140/",
    verifiedAt,
    freshness: "verified",
    marketStatus: "current",
    marketPriceSourceLabel: "Kawasaki Leisure Bikes Philippines",
    marketPriceSourceUrl: "https://kawasakileisurebikes.ph/motorcycles/kx-series/klx-140/",
    marketPriceCheckedAt: verifiedAt,
    priceContext: "Kawasaki Leisure Bikes Philippines currently lists the KLX 140 at ₱160,000 MSRP, excluding freight and other charges. Philippine comparison listings show ₱162,000, so confirm the dealer quote before purchase.",
    transmission: "Manual",
    summary: "Current 144cc off-road trail bike with 11.93 hp, 11.3 Nm, 99 kg curb mass, 780 mm seat, 17/14-inch wheels and dual disc brakes."
  },
  {
    id: "honda-rs125-final-edition",
    alsoKnownAs: ["Honda RS125 Fi", "Honda RS 125", "RS125 Fi", "RS 125 FI"],
    make: "Honda",
    makeSlug: "honda",
    model: "RS125 Final Edition",
    slug: "rs125-final-edition",
    generation: "2026 Final Edition",
    category: "Underbone",
    srp: 77000,
    engineCc: 125,
    powerHp: 9.5,
    torqueNm: 9.55,
    curbWeightKg: 104,
    seatHeightMm: 767,
    fuelTankL: 3.9,
    groundClearanceMm: 135,
    frontTire: "70/90-17",
    rearTire: "80/90-17",
    abs: "No ABS listed; hydraulic front disc and rear drum brake",
    colors: ["Matte Axis Gray Metallic", "Pearl Sylvestris Gray"],
    searchVolume: 2000,
    keywordDifficulty: 1,
    sourceLabel: "Honda Philippines September 2026 RS125 Final Edition release with current price, availability and colors; RS125 Fi specification cross-check",
    sourceUrl: "https://www.hondaph.com/motorcycle/news/honda-releases-its-rs125-final-edition",
    verifiedAt,
    freshness: "verified",
    marketStatus: "current",
    marketPriceSourceLabel: "Honda Philippines",
    marketPriceSourceUrl: "https://www.hondaph.com/motorcycle/news/honda-releases-its-rs125-final-edition",
    marketPriceCheckedAt: verifiedAt,
    priceContext: "Honda Philippines launched the 2026 RS125 Final Edition at ₱77,000 and states that this final production run will remain available until March 2028, subject to the 20,000-unit allocation and dealer stock.",
    transmission: "Manual",
    summary: "Current 2026 RS125 Final Edition underbone with a 125cc air-cooled engine, 4-speed manual transmission, 104 kg curb weight, 767 mm seat and official ₱77,000 SRP."
  },
  {
    id: "honda-nx500-e-clutch",
    alsoKnownAs: ["Honda NX500", "NX500 E-Clutch", "NX 500"],
    make: "Honda",
    makeSlug: "honda",
    model: "NX500 E-Clutch",
    slug: "nx500-e-clutch",
    generation: "2026 E-Clutch Philippine model",
    category: "Adventure motorcycle",
    srp: 420000,
    engineCc: 471,
    powerHp: 47,
    torqueNm: 43,
    curbWeightKg: 199,
    seatHeightMm: 830,
    fuelTankL: 17.5,
    fuelConsumptionKmL: 27.8,
    groundClearanceMm: 180,
    frontTire: "110/80R19",
    rearTire: "160/60R17",
    abs: "2-channel ABS",
    colors: ["Matte Gunpowder Black Metallic", "Pearl Horizon Black"],
    searchVolume: 800,
    keywordDifficulty: 4,
    sourceLabel: "Honda Philippines current 2026 NX500 E-Clutch listing and Makina Moto Expo launch; Honda 2026 NX500 E-Clutch specification cross-check",
    sourceUrl: "https://www.hondaph.com/big-bike/list",
    verifiedAt,
    freshness: "verified",
    marketStatus: "current",
    marketPriceSourceLabel: "Honda Philippines current Big Bike list",
    marketPriceSourceUrl: "https://www.hondaph.com/big-bike/list",
    marketPriceCheckedAt: verifiedAt,
    priceContext: "Honda Philippines currently lists the NX500 E-Clutch at ₱420,000. The April 2026 Philippine launch announced ₱419,000, so use the current catalog price and confirm the final dealer quote.",
    transmission: "Manual",
    summary: "Current Philippine 471cc adventure motorcycle with Honda E-Clutch, 2-channel ABS, 19/17-inch wheels, 830 mm seat, 199 kg kerb weight and current ₱420,000 catalog price."
  },
  {
    id: "kawasaki-z900-standard",
    alsoKnownAs: ["Kawasaki Z900", "Z900", "Z 900"],
    make: "Kawasaki",
    makeSlug: "kawasaki",
    model: "Z900 Standard",
    slug: "z900-standard",
    generation: "Current Philippine model",
    category: "Naked street bike",
    srp: 566500,
    engineCc: 948,
    powerHp: 123.64,
    torqueNm: 98.6,
    curbWeightKg: 212,
    seatHeightMm: 810,
    fuelTankL: 17,
    groundClearanceMm: 145,
    frontTire: "120/70-17",
    rearTire: "180/55-17",
    abs: "ABS on current Z900 platform; confirm exact Philippine-market unit equipment",
    colors: [],
    searchVolume: 1000,
    keywordDifficulty: 4,
    sourceLabel: "Kawasaki Leisure Bikes Philippines current Z900 Standard product page with MSRP and Philippine specifications; 2026 Kawasaki Z900 specification cross-check",
    sourceUrl: "https://kawasakileisurebikes.ph/motorcycles/sports/z900-standard/",
    verifiedAt,
    freshness: "verified",
    marketStatus: "current",
    marketPriceSourceLabel: "Kawasaki Leisure Bikes Philippines",
    marketPriceSourceUrl: "https://kawasakileisurebikes.ph/motorcycles/sports/z900-standard/",
    marketPriceCheckedAt: verifiedAt,
    priceContext: "Kawasaki Leisure Bikes Philippines currently lists the Z900 Standard at ₱566,500 MSRP, excluding freight and other charges. Confirm the exact dealer quote and current unit specification.",
    transmission: "Manual",
    summary: "Current Philippine 948cc inline-four naked bike with 123.64 hp, 98.6 Nm, 212 kg curb mass, 17 L tank and official ₱566,500 MSRP."
  }
];
