import type { Motorcycle } from "./types";

const verifiedAt = "2026-10-04";

export const currentModelGapCloseout2026: Motorcycle[] = [
  {
    id: "honda-crf300l",
    alsoKnownAs: ["Honda CRF 300L", "CRF 300L"],
    make: "Honda",
    makeSlug: "honda",
    model: "CRF300L",
    slug: "crf300l",
    generation: "Current Philippine 286cc generation",
    category: "Dual-sport",
    srp: 269900,
    engineCc: 286,
    powerHp: 26.3,
    torqueNm: 26.1,
    curbWeightKg: 138,
    seatHeightMm: 882,
    fuelTankL: 7.8,
    fuelConsumptionKmL: 29.5,
    groundClearanceMm: 284,
    frontTire: "80/100-21",
    rearTire: "120/80-18",
    abs: "Front and rear disc brakes; current international CRF300L specification includes ABS, confirm exact Philippine unit",
    colors: ["Extreme Red"],
    searchVolume: 900,
    keywordDifficulty: 6,
    sourceLabel: "Honda Philippines 2025 CRF300L launch and Philippine-market specification cross-check",
    sourceUrl: "https://www.hondaph.com/motorcycle/news/honda-philippines-unleashes-power-and-innovation-at-the-action-packed-inside-racing-bikefest-2025",
    verifiedAt,
    freshness: "verified",
    marketStatus: "current",
    marketPriceSourceLabel: "Honda Philippines",
    marketPriceSourceUrl: "https://www.hondaph.com/motorcycle/news/honda-philippines-unleashes-power-and-innovation-at-the-action-packed-inside-racing-bikefest-2025",
    marketPriceCheckedAt: verifiedAt,
    priceContext: "Honda Philippines launched the CRF300L at ₱269,900 in March 2025. Current Philippine market listings still show the model at that price; confirm dealer stock, exact model year and final quote before purchase.",
    transmission: "Manual",
    summary: "Current Philippine 286cc dual-sport with 19.6 kW official Philippine output, 26.1 Nm, 882 mm seat, 138 kg Philippine-market listed curb weight, 21/18-inch wheels and 284 mm ground clearance."
  },
  {
    id: "kawasaki-klx-140",
    alsoKnownAs: ["Kawasaki KLX140", "KLX140"],
    make: "Kawasaki",
    makeSlug: "kawasaki",
    model: "KLX 140",
    slug: "klx-140",
    generation: "Current Philippine model",
    category: "Off-road trail bike",
    srp: 160000,
    engineCc: 144,
    powerHp: 11.93,
    torqueNm: 11.3,
    curbWeightKg: 99,
    seatHeightMm: 780,
    fuelTankL: 5.8,
    groundClearanceMm: 236,
    frontTire: "70/100-17",
    rearTire: "90/100-14",
    abs: "No ABS stated by Kawasaki Philippines; front and rear disc brakes",
    colors: [],
    searchVolume: 900,
    keywordDifficulty: 6,
    sourceLabel: "Kawasaki Leisure Bikes Philippines current KLX 140 product page and Philippine specification cross-check",
    sourceUrl: "https://kawasakileisurebikes.ph/motorcycles/kx-series/klx-140/",
    verifiedAt,
    freshness: "verified",
    marketStatus: "current",
    marketPriceSourceLabel: "Kawasaki Leisure Bikes Philippines",
    marketPriceSourceUrl: "https://kawasakileisurebikes.ph/motorcycles/kx-series/klx-140/",
    marketPriceCheckedAt: verifiedAt,
    priceContext: "Kawasaki Leisure Bikes Philippines currently lists the KLX 140 at ₱160,000 MSRP, excluding freight and other charges. Philippine comparison listings show ₱162,000, so confirm the dealer quote before purchase.",
    transmission: "Manual",
    summary: "Current 144cc off-road trail bike with 11.93 hp, 11.3 Nm, 99 kg curb mass, 780 mm seat, 17/14-inch wheels and dual disc brakes."
  },
  {
    id: "honda-rs125",
    alsoKnownAs: ["Honda RS125 Fi", "RS125 Fi", "Honda RS 125"],
    make: "Honda",
    makeSlug: "honda",
    model: "RS125 Final Edition",
    slug: "rs125",
    generation: "2026 Final Edition",
    category: "Sport underbone",
    srp: 77000,
    engineCc: 125,
    powerHp: 9.55,
    torqueNm: 9.55,
    curbWeightKg: 104,
    seatHeightMm: 767,
    fuelTankL: 3.9,
    fuelConsumptionKmL: 67.5,
    groundClearanceMm: 135,
    frontTire: "70/90-17",
    rearTire: "80/90-17",
    abs: "No ABS; hydraulic front disc and rear drum",
    colors: ["Matte Axis Gray Metallic", "Pearl Sylvestris Gray"],
    searchVolume: 2000,
    keywordDifficulty: 1,
    sourceLabel: "Honda Philippines September 2026 RS125 Final Edition launch with current availability and SRP",
    sourceUrl: "https://www.hondaph.com/motorcycle/news/honda-releases-its-rs125-final-edition",
    verifiedAt,
    freshness: "verified",
    marketStatus: "current",
    marketPriceSourceLabel: "Honda Philippines RS125 Final Edition launch",
    marketPriceSourceUrl: "https://www.hondaph.com/motorcycle/news/honda-releases-its-rs125-final-edition",
    marketPriceCheckedAt: verifiedAt,
    priceContext: "Honda Philippines launched the 2026 RS125 Final Edition at ₱77,000 on September 14, 2026 and states that 20,000 Final Edition units will remain available through March 2028. Confirm branch stock and final cash price before purchase.",
    transmission: "Manual",
    summary: "Current 2026 Final Edition 125cc sport underbone with PGM-FI, 67.5 km/L published WMTC fuel economy, 767 mm seat, 104 kg curb weight and a four-speed rotary transmission."
  },
  {
    id: "honda-nx500-e-clutch",
    alsoKnownAs: ["Honda NX500", "NX 500", "NX500 E-Clutch"],
    make: "Honda",
    makeSlug: "honda",
    model: "NX500 E-Clutch",
    slug: "nx500",
    generation: "2026 Philippine E-Clutch model",
    category: "Adventure touring",
    srp: 420000,
    engineCc: 471,
    powerHp: 49.75,
    torqueNm: 44.7,
    curbWeightKg: 196,
    seatHeightMm: 834,
    fuelTankL: 17.7,
    fuelConsumptionKmL: 29.9,
    groundClearanceMm: 181,
    frontTire: "110/80-19",
    rearTire: "160/60-17",
    abs: "2-channel ABS",
    colors: ["Pearl Horizon Black", "Matte Gunpowder Black Metallic"],
    searchVolume: 800,
    keywordDifficulty: 4,
    sourceLabel: "Honda Philippines 2026 NX500 E-Clutch launch and current Big Bike catalog",
    sourceUrl: "https://www.hondaph.com/big-bike/news/honda-philippines-launches-three-new-models-elevates-innovation-at-makina-moto-expo-2026",
    verifiedAt,
    freshness: "verified",
    marketStatus: "current",
    marketPriceSourceLabel: "Honda Philippines current Big Bike catalog",
    marketPriceSourceUrl: "https://www.hondaph.com/big-bike/list",
    marketPriceCheckedAt: verifiedAt,
    priceContext: "Honda Philippines launched the NX500 E-Clutch at ₱419,000 in April 2026; the current Honda Big Bike catalog lists ₱420,000. MotoIndex uses the current catalog price and keeps the launch figure as historical context.",
    transmission: "Manual",
    summary: "Current 471cc adventure-touring motorcycle with Honda E-Clutch, 2-channel ABS, 17.7 L tank, 834 mm seat, 196 kg curb weight, 29.9 km/L WMTC figure and RoadSync-capable TFT instrumentation."
  },
  {
    id: "yamaha-mt-15",
    alsoKnownAs: ["Yamaha MT15", "MT15"],
    make: "Yamaha",
    makeSlug: "yamaha",
    model: "MT-15",
    slug: "mt-15",
    generation: "Current Philippine dealer-listed model",
    category: "Naked street bike",
    srp: 180000,
    engineCc: 155,
    powerHp: 19.0,
    torqueNm: 14.7,
    curbWeightKg: 133,
    seatHeightMm: 810,
    fuelTankL: 10,
    groundClearanceMm: 155,
    frontTire: "110/70-17",
    rearTire: "140/70-17",
    abs: "No ABS listed in the current Philippine comparison-market specification",
    colors: ["Ice Storm", "Tech Black"],
    searchVolume: 1400,
    keywordDifficulty: 8,
    sourceLabel: "Current Philippine Yamaha dealer listing with price and specifications",
    sourceUrl: "https://www.guanzongroup.com.ph/product/mt-15/",
    verifiedAt,
    freshness: "verified",
    marketStatus: "current",
    marketPriceSourceLabel: "Guanzon current MT-15 dealer listing",
    marketPriceSourceUrl: "https://www.guanzongroup.com.ph/product/mt-15/",
    marketPriceCheckedAt: verifiedAt,
    priceContext: "Guanzon currently lists the Yamaha MT-15 at ₱180,000 SRP with financing examples. Dealer pricing can vary by branch; confirm the current Yamaha unit, model code and final quote before purchase.",
    transmission: "Manual",
    summary: "Current Philippine dealer-listed 155cc naked bike with 19 hp, 14.7 Nm, six-speed transmission, 810 mm seat, 133 kg curb weight, 10 L tank and 17-inch tubeless tires."
  }
];