import type { EntityMedia } from "./types";

// Generated from checked product source pages by scripts/backfill-product-media.mjs.
// Local WebP derivatives are used at runtime; sourceImageUrl and sourceUrl preserve provenance.
export const generatedProductMedia: EntityMedia[] = [
  {
    "id": "spyder-surge-v2-generated-product",
    "entityType": "helmet",
    "entityId": "spyder-surge-v2",
    "role": "primary",
    "src": "/media/helmets/spyder-surge-v2.webp",
    "sourceImageUrl": "http://www.teamspyder.com/cdn/shop/files/A6501093800.png?v=1760060494",
    "alt": "Spyder Surge Plain V2 product image",
    "width": 1200,
    "height": 1200,
    "rightsStatus": "external-reference",
    "sourceLabel": "Checked product-page image · Spyder Surge Plain V2",
    "sourceUrl": "https://www.teamspyder.com/products/spyder-surge-p-plain-v2",
    "lastChecked": "2026-09-12"
  },
  {
    "id": "spyder-force-v2-generated-product",
    "entityType": "helmet",
    "entityId": "spyder-force-v2",
    "role": "primary",
    "src": "/media/helmets/spyder-force-v2.webp",
    "sourceImageUrl": "http://www.teamspyder.com/cdn/shop/files/A6500150800.png?v=1714030448",
    "alt": "Spyder Force+ Plain V2 product image",
    "width": 1200,
    "height": 1200,
    "rightsStatus": "external-reference",
    "sourceLabel": "Checked product-page image · Spyder Force+ Plain V2",
    "sourceUrl": "https://www.teamspyder.com/products/spyder-force-pd-s0-v2",
    "lastChecked": "2026-09-12"
  },
  {
    "id": "spyder-corsa-v2-generated-product",
    "entityType": "helmet",
    "entityId": "spyder-corsa-v2",
    "role": "primary",
    "src": "/media/helmets/spyder-corsa-v2.webp",
    "sourceImageUrl": "http://www.teamspyder.com/cdn/shop/files/A6500315800.png?v=1689936234",
    "alt": "Spyder Corsa Plain V2 product image",
    "width": 1200,
    "height": 1200,
    "rightsStatus": "external-reference",
    "sourceLabel": "Checked product-page image · Spyder Corsa Plain V2",
    "sourceUrl": "https://www.teamspyder.com/products/spyder-corsa-plain-v2",
    "lastChecked": "2026-09-12"
  },
  {
    "id": "spyder-nf1-generated-product",
    "entityType": "helmet",
    "entityId": "spyder-nf1",
    "role": "primary",
    "src": "/media/helmets/spyder-nf1.webp",
    "sourceImageUrl": "http://www.teamspyder.com/cdn/shop/files/A6509835800.png?v=1712977695",
    "alt": "Spyder NF1 Plain product image",
    "width": 1200,
    "height": 1200,
    "rightsStatus": "external-reference",
    "sourceLabel": "Checked product-page image · Spyder NF1 Plain",
    "sourceUrl": "https://www.teamspyder.com/products/neo-nf1-plain-s0",
    "lastChecked": "2026-09-12"
  },
  {
    "id": "spyder-shift-plus-generated-product",
    "entityType": "helmet",
    "entityId": "spyder-shift-plus",
    "role": "primary",
    "src": "/media/helmets/spyder-shift-plus.webp",
    "sourceImageUrl": "http://www.teamspyder.com/cdn/shop/files/A6506520800.png?v=1712728198",
    "alt": "Spyder Shift+ Plain product image",
    "width": 1200,
    "height": 1200,
    "rightsStatus": "external-reference",
    "sourceLabel": "Checked product-page image · Spyder Shift+ Plain",
    "sourceUrl": "https://www.teamspyder.com/products/shift-plain",
    "lastChecked": "2026-09-12"
  },
  {
    "id": "spyder-rogue-plus-v2-generated-product",
    "entityType": "helmet",
    "entityId": "spyder-rogue-plus-v2",
    "role": "primary",
    "src": "/media/helmets/spyder-rogue-plus-v2.webp",
    "sourceImageUrl": "http://www.teamspyder.com/cdn/shop/files/A6508134800.png?v=1738741626",
    "alt": "Spyder Rogue+ Plain V2 product image",
    "width": 1200,
    "height": 1200,
    "rightsStatus": "external-reference",
    "sourceLabel": "Checked product-page image · Spyder Rogue+ Plain V2",
    "sourceUrl": "https://www.teamspyder.com/products/spyder-rogue-pd-plain-vesion2",
    "lastChecked": "2026-09-12"
  },
  {
    "id": "gille-gxr-sh-526-generated-product",
    "entityType": "helmet",
    "entityId": "gille-gxr-sh-526",
    "role": "primary",
    "src": "/media/helmets/gille-gxr-sh-526.webp",
    "sourceImageUrl": "https://down-ph.img.susercontent.com/file/ph-11134207-820l8-ms6qnjt351xc03",
    "alt": "Gille GXR SH-526 product image",
    "width": 1200,
    "height": 1200,
    "rightsStatus": "external-reference",
    "sourceLabel": "Checked product-page image · Gille GXR SH-526",
    "sourceUrl": "https://shopee.ph/product/505955057/19111260810",
    "lastChecked": "2026-09-12"
  },
  {
    "id": "hjc-rpha-12-generated-product",
    "entityType": "helmet",
    "entityId": "hjc-rpha-12",
    "role": "primary",
    "src": "/media/helmets/hjc-rpha-12.webp",
    "sourceImageUrl": "http://hjchelmets.us/cdn/shop/files/white___rpha-12-solid_1_07199173-6c67-482e-afbd-6578d2e72bbf_1.webp?v=1773273992",
    "alt": "HJC RPHA 12 product image",
    "width": 1200,
    "height": 1200,
    "rightsStatus": "external-reference",
    "sourceLabel": "Checked product-page image · HJC RPHA 12",
    "sourceUrl": "https://hjchelmets.us/products/rpha-12-solid",
    "lastChecked": "2026-09-12"
  },
  {
    "id": "agv-ax9-generated-product",
    "entityType": "helmet",
    "entityId": "agv-ax9",
    "role": "primary",
    "src": "/media/helmets/agv-ax9.webp",
    "sourceImageUrl": "https://dainese-cdn.thron.com/api/v1/content-delivery/shares/lxnwxt/contents/6acea8f8-5244-4f38-8d8c-9ad0d8d69f7f/image/image?format=webp&q_auto=high&w=450&h=450",
    "alt": "AGV AX9 product image",
    "width": 1200,
    "height": 1200,
    "rightsStatus": "external-reference",
    "sourceLabel": "Checked product-page image · AGV AX9",
    "sourceUrl": "https://www.agv.com/us/en/full-face/ax9/",
    "lastChecked": "2026-09-12"
  },
  {
    "id": "shark-skwal-i3-generated-product",
    "entityType": "helmet",
    "entityId": "shark-skwal-i3",
    "role": "primary",
    "src": "/media/helmets/shark-skwal-i3.webp",
    "sourceImageUrl": "http://www.shark-helmets.com/cdn/shop/files/HE0835EKAR_SHARK-HELMETS-SKWAL-I3-GANG-MAT_ps_01.webp?v=1787800777",
    "alt": "Shark Skwal i3 product image",
    "width": 1200,
    "height": 1200,
    "rightsStatus": "external-reference",
    "sourceLabel": "Checked product-page image · Shark Skwal i3",
    "sourceUrl": "https://www.shark-helmets.com/en/products/skwal-i3-gang-he0835ekar",
    "lastChecked": "2026-09-12"
  },
  {
    "id": "mt-atom-2-sv-generated-product",
    "entityType": "helmet",
    "entityId": "mt-atom-2-sv",
    "role": "primary",
    "src": "/media/helmets/mt-atom-2-sv.webp",
    "sourceImageUrl": "http://mthelmets.com/cdn/shop/files/133500PA220-1PP-26-FU404SV_MT_Helmets_ATOM_2_SV_Pure_A2_Matt_02.webp?crop=center&height=1200&v=1781627586&width=1200",
    "alt": "MT Atom 2 SV product image",
    "width": 1200,
    "height": 1200,
    "rightsStatus": "external-reference",
    "sourceLabel": "Checked product-page image · MT Atom 2 SV",
    "sourceUrl": "https://mthelmets.com/en/products/atom-2-sv-pure-a2-matt",
    "lastChecked": "2026-09-12"
  },
  {
    "id": "shark-aeron-gp-fim-generated-product",
    "entityType": "helmet",
    "entityId": "shark-aeron-gp-fim",
    "role": "primary",
    "src": "/media/helmets/shark-aeron-gp-fim.webp",
    "sourceImageUrl": "http://www.shark-helmets.com/cdn/shop/files/HE1010EDKD_SHARK-HELMETS-AERON-GP-FIM-FULL-CARBON_ps_01.webp?v=1787680607",
    "alt": "Shark Aeron GP FIM product image",
    "width": 1200,
    "height": 1200,
    "rightsStatus": "external-reference",
    "sourceLabel": "Checked product-page image · Shark Aeron GP FIM",
    "sourceUrl": "https://www.shark-helmets.com/en/products/aeron-gp-fim-full-carbon-he1010edkd",
    "lastChecked": "2026-09-12"
  },
  {
    "id": "shark-spartan-gt-pro-carbon-generated-product",
    "entityType": "helmet",
    "entityId": "shark-spartan-gt-pro-carbon",
    "role": "primary",
    "src": "/media/helmets/shark-spartan-gt-pro-carbon.webp",
    "sourceImageUrl": "http://www.shark-helmets.com/cdn/shop/files/HE1308EDWU_SHARK-HELMETS-SPARTAN-GT-PRO-STHYR-GLOSSY_ps_01.webp?v=1787674066",
    "alt": "Shark Spartan GT Pro Carbon product image",
    "width": 1200,
    "height": 1200,
    "rightsStatus": "external-reference",
    "sourceLabel": "Checked product-page image · Shark Spartan GT Pro Carbon",
    "sourceUrl": "https://www.shark-helmets.com/en/products/spartan-gt-pro-carbon-sthyr-he1308edwu",
    "lastChecked": "2026-09-12"
  },
  {
    "id": "shark-spartan-gt-pro-generated-product",
    "entityType": "helmet",
    "entityId": "shark-spartan-gt-pro",
    "role": "primary",
    "src": "/media/helmets/shark-spartan-gt-pro.webp",
    "sourceImageUrl": "http://www.shark-helmets.com/cdn/shop/files/HE1319EWRB_SHARK-HELMETS-SPARTAN-GT-PRO-FLAGSTAFF_ps_01.webp?v=1787674112",
    "alt": "Shark Spartan GT Pro product image",
    "width": 1200,
    "height": 1200,
    "rightsStatus": "external-reference",
    "sourceLabel": "Checked product-page image · Shark Spartan GT Pro",
    "sourceUrl": "https://www.shark-helmets.com/en/products/spartan-gt-pro-flagstaff-he1319ewrb",
    "lastChecked": "2026-09-12"
  },
  {
    "id": "mt-thunder-4-sv-generated-product",
    "entityType": "helmet",
    "entityId": "mt-thunder-4-sv",
    "role": "primary",
    "src": "/media/helmets/mt-thunder-4-sv.webp",
    "sourceImageUrl": "http://mthelmets.com/cdn/shop/files/130800PA220-1PP-26-FF118SV_MT_Helmets_Thunder_4_SV_Pure_A2_Matt_02.webp?crop=center&height=1200&v=1781627540&width=1200",
    "alt": "MT Thunder 4 SV product image",
    "width": 1200,
    "height": 1200,
    "rightsStatus": "external-reference",
    "sourceLabel": "Checked product-page image · MT Thunder 4 SV",
    "sourceUrl": "https://mthelmets.com/en/products/thunder-4-sv-pure-a2-matt",
    "lastChecked": "2026-09-12"
  },
  {
    "id": "bell-lithium-mips-generated-product",
    "entityType": "helmet",
    "entityId": "bell-lithium-mips",
    "role": "primary",
    "src": "/media/helmets/bell-lithium-mips.webp",
    "sourceImageUrl": "https://vault.widen.net/content/vyeobkptjg?w=1500&h=1500",
    "alt": "Bell Lithium MIPS product image",
    "width": 1200,
    "height": 1200,
    "rightsStatus": "external-reference",
    "sourceLabel": "Checked product-page image · Bell Lithium MIPS",
    "sourceUrl": "https://www.bellhelmets.com/product/lithium-mips/250070001600000002.html",
    "lastChecked": "2026-09-12"
  },
  {
    "id": "mt-braker-sv-generated-product",
    "entityType": "helmet",
    "entityId": "mt-braker-sv",
    "role": "primary",
    "src": "/media/helmets/mt-braker-sv.webp",
    "sourceImageUrl": "http://mthelmets.com/cdn/shop/files/134600PA010-1PP-26-FF128SV_MT_Helmets_Braker_SV_Pure_A0_02.webp?crop=center&height=1200&v=1781627617&width=1200",
    "alt": "MT Braker SV product image",
    "width": 1200,
    "height": 1200,
    "rightsStatus": "external-reference",
    "sourceLabel": "Checked product-page image · MT Braker SV",
    "sourceUrl": "https://mthelmets.com/en/products/braker-sv-pure-a0-gloss",
    "lastChecked": "2026-09-12"
  },
  {
    "id": "mt-streetfighter-sv-s-generated-product",
    "entityType": "helmet",
    "entityId": "mt-streetfighter-sv-s",
    "role": "primary",
    "src": "/media/helmets/mt-streetfighter-sv-s.webp",
    "sourceImageUrl": "https://mthelmets.com/cdn/shop/files/132700PA120-1PP-26-TR902BSV_MT_Helmets_Streetfighter_SV_S_Pure_A1_Matt_02.webp?v=1781627565&width=460",
    "alt": "MT Streetfighter SV product image",
    "width": 1200,
    "height": 1200,
    "rightsStatus": "external-reference",
    "sourceLabel": "Checked product-page image · MT Streetfighter SV",
    "sourceUrl": "https://mthelmets.com/en/collections/streetfighter-sv-s",
    "lastChecked": "2026-09-12"
  },
  {
    "id": "bell-race-star-dlx-flex-generated-product",
    "entityType": "helmet",
    "entityId": "bell-race-star-dlx-flex",
    "role": "primary",
    "src": "/media/helmets/bell-race-star-dlx-flex.webp",
    "sourceImageUrl": "https://vault.widen.net/content/gyn26njts8?w=1500&h=1500",
    "alt": "Bell Race Star DLX Flex product image",
    "width": 1200,
    "height": 1200,
    "rightsStatus": "external-reference",
    "sourceLabel": "Checked product-page image · Bell Race Star DLX Flex",
    "sourceUrl": "https://www.bellhelmets.com/product/race-star-dlx-flex/250070000200000005.html",
    "lastChecked": "2026-09-12"
  },
  {
    "id": "nhk-cross-one-generated-product",
    "entityType": "helmet",
    "entityId": "nhk-cross-one",
    "role": "primary",
    "src": "/media/helmets/nhk-cross-one.webp",
    "sourceImageUrl": "https://nhkhelmet.com/wp-content/uploads/2020/10/CROSS-ONE_FRONT-LEFT-SIDE-600x600.png",
    "alt": "NHK Cross One product image",
    "width": 1200,
    "height": 1200,
    "rightsStatus": "external-reference",
    "sourceLabel": "Checked product-page image · NHK Cross One",
    "sourceUrl": "https://nhkhelmet.com/cross-one/",
    "lastChecked": "2026-09-12"
  },
  {
    "id": "nhk-gp-r-tech-street-generated-product",
    "entityType": "helmet",
    "entityId": "nhk-gp-r-tech-street",
    "role": "primary",
    "src": "/media/helmets/nhk-gp-r-tech-street.webp",
    "sourceImageUrl": "https://nhkhelmet.com/wp-content/uploads/2021/11/GP-R-TECH-STREET_FRONTSIDE-600x600.png",
    "alt": "NHK GP R Tech Street product image",
    "width": 1200,
    "height": 1200,
    "rightsStatus": "external-reference",
    "sourceLabel": "Checked product-page image · NHK GP R Tech Street",
    "sourceUrl": "https://nhkhelmet.com/gp-r-tech-full-face/",
    "lastChecked": "2026-09-12"
  },
  {
    "id": "nhk-race-pro-generated-product",
    "entityType": "helmet",
    "entityId": "nhk-race-pro",
    "role": "primary",
    "src": "/media/helmets/nhk-race-pro.webp",
    "sourceImageUrl": "https://nhkhelmet.com/wp-content/uploads/2020/10/RACE-PRO_FRONT-LEFTSIDE-600x600.png",
    "alt": "NHK Race Pro product image",
    "width": 1200,
    "height": 1200,
    "rightsStatus": "external-reference",
    "sourceLabel": "Checked product-page image · NHK Race Pro",
    "sourceUrl": "https://nhkhelmet.com/race-pro/",
    "lastChecked": "2026-09-12"
  },
  {
    "id": "nhk-gp-r-tech-race-generated-product",
    "entityType": "helmet",
    "entityId": "nhk-gp-r-tech-race",
    "role": "primary",
    "src": "/media/helmets/nhk-gp-r-tech-race.webp",
    "sourceImageUrl": "https://nhkhelmet.com/wp-content/uploads/2020/10/GP-R-TECH-RACE_FRONT-LEFT-SIDE-600x600.png",
    "alt": "NHK GP R Tech Race product image",
    "width": 1200,
    "height": 1200,
    "rightsStatus": "external-reference",
    "sourceLabel": "Checked product-page image · NHK GP R Tech Race",
    "sourceUrl": "https://nhkhelmet.com/gp-r-tech/",
    "lastChecked": "2026-09-12"
  },
  {
    "id": "alpinestars-supertech-r10-generated-product",
    "entityType": "helmet",
    "entityId": "alpinestars-supertech-r10",
    "role": "primary",
    "src": "/media/helmets/alpinestars-supertech-r10.webp",
    "sourceImageUrl": "http://www.alpinestars.com/cdn/shop/files/8200124-2170-r3_s-r10-helmet_66d3266c-a3a9-4b52-b089-fa25576aa29f.png?v=1783760765",
    "alt": "Alpinestars Supertech R10 product image",
    "width": 1200,
    "height": 1200,
    "rightsStatus": "external-reference",
    "sourceLabel": "Checked product-page image · Alpinestars Supertech R10",
    "sourceUrl": "https://www.alpinestars.com/products/supertech-r10-solid-helmet",
    "lastChecked": "2026-09-12"
  },
  {
    "id": "alpinestars-supertech-m10-generated-product",
    "entityType": "helmet",
    "entityId": "alpinestars-supertech-m10",
    "role": "primary",
    "src": "/media/helmets/alpinestars-supertech-m10.webp",
    "sourceImageUrl": "http://www.alpinestars.com/cdn/shop/files/8300223-9190-r2_s-m10-fame-helmet_2b5700d5-5c39-4e1b-9d7c-9dea822e0f27.png?v=1783758167",
    "alt": "Alpinestars Supertech M10 product image",
    "width": 1200,
    "height": 1200,
    "rightsStatus": "external-reference",
    "sourceLabel": "Checked product-page image · Alpinestars Supertech M10",
    "sourceUrl": "https://www.alpinestars.com/products/supertech-m10-fame-helmet",
    "lastChecked": "2026-09-12"
  },
  {
    "id": "shoei-x-spr-pro-generated-product",
    "entityType": "helmet",
    "entityId": "shoei-x-spr-pro",
    "role": "primary",
    "src": "/media/helmets/shoei-x-spr-pro.webp",
    "sourceImageUrl": "https://www.shoei-europe.com/wp-content/uploads/2022/05/shoei_xspr-pro_product_poptitle.jpg",
    "alt": "Shoei X-SPR Pro product image",
    "width": 1200,
    "height": 1200,
    "rightsStatus": "external-reference",
    "sourceLabel": "Checked product-page image · Shoei X-SPR Pro",
    "sourceUrl": "https://www.shoei-europe.com/products/x-spr-pro/",
    "lastChecked": "2026-09-12"
  },
  {
    "id": "shoei-gt-air-3-generated-product",
    "entityType": "helmet",
    "entityId": "shoei-gt-air-3",
    "role": "primary",
    "src": "/media/helmets/shoei-gt-air-3.webp",
    "sourceImageUrl": "https://www.shoei-europe.com/wp-content/uploads/2025/12/menue-Products-gt-air3_smart-color.png",
    "alt": "Shoei GT-Air 3 product image",
    "width": 1200,
    "height": 1200,
    "rightsStatus": "external-reference",
    "sourceLabel": "Checked product-page image · Shoei GT-Air 3",
    "sourceUrl": "https://www.shoei-europe.com/products/gt-air3/",
    "lastChecked": "2026-09-12"
  },
  {
    "id": "shoei-neotec-3-generated-product",
    "entityType": "helmet",
    "entityId": "shoei-neotec-3",
    "role": "primary",
    "src": "/media/helmets/shoei-neotec-3.webp",
    "sourceImageUrl": "https://www.shoei-europe.com/wp-content/uploads/2023/07/shoei_neotec3_product_profilet_iny.png",
    "alt": "Shoei Neotec 3 product image",
    "width": 1200,
    "height": 1200,
    "rightsStatus": "external-reference",
    "sourceLabel": "Checked product-page image · Shoei Neotec 3",
    "sourceUrl": "https://www.shoei-europe.com/products/neotec3/",
    "lastChecked": "2026-09-12"
  },
  {
    "id": "shoei-hornet-adv-06-generated-product",
    "entityType": "helmet",
    "entityId": "shoei-hornet-adv-06",
    "role": "primary",
    "src": "/media/helmets/shoei-hornet-adv-06.webp",
    "sourceImageUrl": "https://www.shoei-europe.com/wp-content/uploads/2020/09/Menue-Products_HornetADV.png",
    "alt": "Shoei Hornet-ADV 06 product image",
    "width": 1200,
    "height": 1200,
    "rightsStatus": "external-reference",
    "sourceLabel": "Checked product-page image · Shoei Hornet-ADV 06",
    "sourceUrl": "https://www.shoei-europe.com/products/hornet-adv-06/",
    "lastChecked": "2026-09-12"
  },
  {
    "id": "shoei-glamster-06-generated-product",
    "entityType": "helmet",
    "entityId": "shoei-glamster-06",
    "role": "primary",
    "src": "/media/helmets/shoei-glamster-06.webp",
    "sourceImageUrl": "https://www.shoei-europe.com/wp-content/uploads/2020/09/shoei_glamster_moods_05.jpg",
    "alt": "Shoei Glamster 06 product image",
    "width": 1200,
    "height": 1200,
    "rightsStatus": "external-reference",
    "sourceLabel": "Checked product-page image · Shoei Glamster 06",
    "sourceUrl": "https://www.shoei-europe.com/products/glamster/",
    "lastChecked": "2026-09-12"
  },
  {
    "id": "shoei-j-cruise-3-generated-product",
    "entityType": "helmet",
    "entityId": "shoei-j-cruise-3",
    "role": "primary",
    "src": "/media/helmets/shoei-j-cruise-3.webp",
    "sourceImageUrl": "https://www.shoei-europe.com/wp-content/uploads/2024/05/shoei_J-Cruise3_product_profile_3_tiny.png",
    "alt": "Shoei J-Cruise 3 product image",
    "width": 1200,
    "height": 1200,
    "rightsStatus": "external-reference",
    "sourceLabel": "Checked product-page image · Shoei J-Cruise 3",
    "sourceUrl": "https://www.shoei-europe.com/products/j-cruise3/",
    "lastChecked": "2026-09-12"
  },
  {
    "id": "shoei-vfx-wr-06-generated-product",
    "entityType": "helmet",
    "entityId": "shoei-vfx-wr-06",
    "role": "primary",
    "src": "/media/helmets/shoei-vfx-wr-06.webp",
    "sourceImageUrl": "https://www.shoei-europe.com/wp-content/uploads/2020/09/Menue-Products-vfx-wr.png",
    "alt": "Shoei VFX-WR 06 product image",
    "width": 1200,
    "height": 1200,
    "rightsStatus": "external-reference",
    "sourceLabel": "Checked product-page image · Shoei VFX-WR 06",
    "sourceUrl": "https://www.shoei-europe.com/products/vfx-wr/",
    "lastChecked": "2026-09-12"
  },
  {
    "id": "mt-stinger-2-generated-product",
    "entityType": "helmet",
    "entityId": "mt-stinger-2",
    "role": "primary",
    "src": "/media/helmets/mt-stinger-2.webp",
    "sourceImageUrl": "https://mthelmets.com/cdn/shop/files/133400PA000-1PP-26-FF126_MT_Helmets_Stinger_2_Pure_A0_Gloss_02_98e88e4b-88f3-480f-8e68-5f8176ff8bce.webp?v=1781627575&width=460",
    "alt": "MT Stinger 2 product image",
    "width": 1200,
    "height": 1200,
    "rightsStatus": "external-reference",
    "sourceLabel": "Checked product-page image · MT Stinger 2",
    "sourceUrl": "https://mthelmets.com/en/collections/stinger-2",
    "lastChecked": "2026-09-12"
  },
  {
    "id": "mt-targo-s-generated-product",
    "entityType": "helmet",
    "entityId": "mt-targo-s",
    "role": "primary",
    "src": "/media/helmets/mt-targo-s.webp",
    "sourceImageUrl": "https://mthelmets.com/cdn/shop/files/1343D25C820-1PP-26-FF106B_MT_Helmets_Targo_S_Outside_C8_02.webp?v=1781627606&width=460",
    "alt": "MT Targo S product image",
    "width": 1200,
    "height": 1200,
    "rightsStatus": "external-reference",
    "sourceLabel": "Checked product-page image · MT Targo S",
    "sourceUrl": "https://mthelmets.com/en/collections/targo-s",
    "lastChecked": "2026-09-12"
  },
  {
    "id": "bell-srt-modular-generated-product",
    "entityType": "helmet",
    "entityId": "bell-srt-modular",
    "role": "primary",
    "src": "/media/helmets/bell-srt-modular.webp",
    "sourceImageUrl": "https://vault.widen.net/content/cw6ugr8piz?w=1500&h=1500",
    "alt": "Bell SRT-Modular product image",
    "width": 1200,
    "height": 1200,
    "rightsStatus": "external-reference",
    "sourceLabel": "Checked product-page image · Bell SRT-Modular",
    "sourceUrl": "https://www.bellhelmets.com/product/srt-modular/250070000800000001.html",
    "lastChecked": "2026-09-12"
  },
  {
    "id": "bell-mx-9-adv-mips-generated-product",
    "entityType": "helmet",
    "entityId": "bell-mx-9-adv-mips",
    "role": "primary",
    "src": "/media/helmets/bell-mx-9-adv-mips.webp",
    "sourceImageUrl": "https://vault.widen.net/content/z1pmns2ozh?w=1500&h=1500",
    "alt": "Bell MX-9 ADV MIPS product image",
    "width": 1200,
    "height": 1200,
    "rightsStatus": "external-reference",
    "sourceLabel": "Checked product-page image · Bell MX-9 ADV MIPS",
    "sourceUrl": "https://www.bellhelmets.com/product/mx-9-adv-mips/250040000300000001.html",
    "lastChecked": "2026-09-12"
  },
  {
    "id": "shark-ridill-2-generated-product",
    "entityType": "helmet",
    "entityId": "shark-ridill-2",
    "role": "primary",
    "src": "/media/helmets/shark-ridill-2.webp",
    "sourceImageUrl": "http://www.shark-helmets.com/cdn/shop/files/HE1122EKGA_SHARK-HELMETS-RIDILL-2-BERSEK-BLACK-GREEN-ANTHRACITE_ps_01.webp?v=1787674011",
    "alt": "Shark RIDILL 2 product image",
    "width": 1200,
    "height": 1200,
    "rightsStatus": "external-reference",
    "sourceLabel": "Checked product-page image · Shark RIDILL 2",
    "sourceUrl": "https://www.shark-helmets.com/en/products/ridill-2-bersek-he1122ekga",
    "lastChecked": "2026-09-12"
  },
  {
    "id": "shark-d-skwal-3-generated-product",
    "entityType": "helmet",
    "entityId": "shark-d-skwal-3",
    "role": "primary",
    "src": "/media/helmets/shark-d-skwal-3.webp",
    "sourceImageUrl": "http://www.shark-helmets.com/cdn/shop/files/HE0900EBLK_SHARK-HELMETS-D-SKWAL-3-BLANK-BLACK_ps_01.webp?v=1787673679",
    "alt": "Shark D-SKWAL 3 product image",
    "width": 1200,
    "height": 1200,
    "rightsStatus": "external-reference",
    "sourceLabel": "Checked product-page image · Shark D-SKWAL 3",
    "sourceUrl": "https://www.shark-helmets.com/en/products/d-skwal-3-blank-he0900eblk",
    "lastChecked": "2026-09-12"
  },
  {
    "id": "shad-sh39-generated-product",
    "entityType": "topbox",
    "entityId": "shad-sh39",
    "role": "primary",
    "src": "/media/topboxes/shad-sh39.webp",
    "sourceImageUrl": "https://www.shad.es/wp-content/uploads/8430358554245_1-1920x1920.jpg",
    "alt": "SHAD SH39 product image",
    "width": 1200,
    "height": 1200,
    "rightsStatus": "external-reference",
    "sourceLabel": "Checked product-page image · SHAD SH39",
    "sourceUrl": "https://www.shad.es/en/motorcycle-cases/top-cases-motorcycle-cases/top-case-sh39-carbon/",
    "lastChecked": "2026-09-12"
  }
];
