import type { Motorcycle } from "./types";

const verifiedAt = "2026-10-04";

export const harleyDavidsonGapExpansion2026: Motorcycle[] = [
  {
    id: "harley-davidson-nightster",
    alsoKnownAs: ["Harley Davidson Nightster", "Nightster 975"],
    make: "Harley-Davidson",
    makeSlug: "harley-davidson",
    model: "Nightster",
    slug: "nightster",
    generation: "2026 model",
    category: "Cruiser",
    srp: 799000,
    engineCc: 975,
    powerHp: 89,
    torqueNm: 95,
    curbWeightKg: 220,
    seatHeightMm: 705,
    fuelTankL: 11.7,
    groundClearanceMm: 110,
    frontTire: "100/90-19 57H",
    rearTire: "150/80B16 77H",
    abs: "ABS with traction control and drag-torque slip control",
    colors: [],
    searchVolume: 0,
    keywordDifficulty: 0,
    sourceLabel: "Harley-Davidson APAC 2026 Nightster technical specification",
    sourceUrl: "https://www.harley-davidson.com/ap/en/motorcycles/nightster.html",
    verifiedAt,
    freshness: "verified",
    marketStatus: "current",
    marketPriceSourceLabel: "Current Philippine Nightster market price reference",
    marketPriceSourceUrl: "https://www.zigwheels.ph/new-motorcycles/harley-davidson/nightster/price",
    marketPriceCheckedAt: verifiedAt,
    priceContext: "Current Philippine comparison listings show the Nightster from ₱799,000. Confirm the exact 2026 unit, dealer stock and final on-road quote before purchase.",
    transmission: "Manual",
    summary: "2026 Nightster with a 975cc Revolution Max 975T engine, 89 hp, 95 Nm, 705 mm unladen seat, 220 kg running-order weight and ABS-based rider-safety electronics."
  },
  {
    id: "harley-davidson-sportster-s",
    alsoKnownAs: ["Harley Davidson Sportster", "Harley Sportster", "Sportster S"],
    make: "Harley-Davidson",
    makeSlug: "harley-davidson",
    model: "Sportster S",
    slug: "sportster-s",
    generation: "2026 model",
    category: "Sport cruiser",
    srp: 959000,
    engineCc: 1252,
    powerHp: 121,
    torqueNm: 125,
    curbWeightKg: 228,
    seatHeightMm: 765,
    fuelTankL: 11.7,
    groundClearanceMm: 90,
    frontTire: "160/70R17 73V",
    rearTire: "180/70R16 77V",
    abs: "ABS with Harley-Davidson rider-safety electronics",
    colors: ["White Onyx Pearl", "Dark Billiard Gray", "Vivid Black", "Blood Orange", "Aurora Blue Denim"],
    searchVolume: 800,
    keywordDifficulty: 0,
    sourceLabel: "Harley-Davidson APAC 2026 Sportster S technical specification",
    sourceUrl: "https://www.harley-davidson.com/ap/en/motorcycles/sportster/sportster-s/1.html",
    verifiedAt,
    freshness: "verified",
    marketStatus: "current",
    marketPriceSourceLabel: "Current Philippine Sportster S market price reference",
    marketPriceSourceUrl: "https://www.zigwheels.ph/new-motorcycles/harley-davidson/sportster-s/price",
    marketPriceCheckedAt: verifiedAt,
    priceContext: "Current Philippine comparison listings show the Sportster S at ₱959,000. Confirm the exact paint, dealer stock and final on-road quote before purchase.",
    transmission: "Manual",
    summary: "2026 Sportster S with a 1,252cc Revolution Max 1250T engine, 121 hp, 125 Nm, 765 mm unladen seat, 228 kg running-order weight and modern rider-safety electronics."
  },
  {
    id: "harley-davidson-pan-america-1250-special",
    alsoKnownAs: ["Harley Davidson Pan America", "Pan America 1250", "Pan America Special"],
    make: "Harley-Davidson",
    makeSlug: "harley-davidson",
    model: "Pan America 1250 Special",
    slug: "pan-america-1250-special",
    generation: "2026 model",
    category: "Adventure touring",
    srp: 1380000,
    engineCc: 1252,
    powerHp: 150,
    torqueNm: 128,
    curbWeightKg: 263,
    seatHeightMm: 850,
    fuelTankL: 21.2,
    groundClearanceMm: 175,
    frontTire: "120/70R19 60V",
    rearTire: "170/60R17 72V",
    abs: "ABS with cornering rider-safety enhancements",
    colors: [],
    searchVolume: 0,
    keywordDifficulty: 0,
    sourceLabel: "Harley-Davidson APAC 2026 Pan America 1250 Special technical specification",
    sourceUrl: "https://www.harley-davidson.com/ap/en/motorcycles/pan-america-1250-special.html",
    verifiedAt,
    freshness: "verified",
    marketStatus: "current",
    marketPriceSourceLabel: "Current Philippine Pan America 1250 Special market price reference",
    marketPriceSourceUrl: "https://www.zigwheels.ph/new-motorcycles/harley-davidson/pan-america-1250/special",
    marketPriceCheckedAt: verifiedAt,
    priceContext: "Current Philippine comparison listings show the Pan America 1250 Special at ₱1.38 million. Confirm dealer stock, exact equipment and final on-road quote before purchase.",
    transmission: "Manual",
    summary: "2026 Pan America 1250 Special with a 1,252cc Revolution Max engine, 150 hp, 128 Nm, adjustable 850/875 mm unladen seat, 21.2 L tank and cornering rider-safety electronics."
  }
];
