import type { Motorcycle } from "./types";

const verifiedAt = "2026-10-04";

// Current Hero MotoCorp Philippine lineup added from official Hero Philippines
// product pages. Search-volume values use the supplied October 2026 ZigWheels
// keyword export where an unambiguous model keyword exists.
export const heroExpansion2026: Motorcycle[] = [
  {
    id: "hero-xpulse-200-4v",
    alsoKnownAs: ["Hero XPulse 200", "XPulse 200 4V", "XPulse 200"],
    make: "Hero",
    makeSlug: "hero",
    model: "XPulse 200 4V",
    slug: "xpulse-200-4v",
    generation: "Current Philippine model",
    category: "Dual-sport",
    srp: 140000,
    engineCc: 199.6,
    powerHp: 18.9,
    torqueNm: 17.35,
    curbWeightKg: 159,
    seatHeightMm: 825,
    fuelTankL: 13,
    groundClearanceMm: 220,
    frontTire: "90/90-21",
    rearTire: "120/80-18",
    abs: "Single-channel ABS with multi-terrain 3-mode ABS settings",
    colors: ["Metallic Nexus Blue White", "Black Sports Red", "Techno Blue Metallic Black"],
    searchVolume: 2100,
    keywordDifficulty: 0,
    sourceLabel: "Hero MotoCorp Philippines current XPulse 200 4V product page",
    sourceUrl: "https://www.heromotocorp.com/en-ph/products/premium/xpulse-200-4v.html",
    verifiedAt,
    freshness: "verified",
    marketStatus: "current",
    marketPriceSourceLabel: "Hero MotoCorp Philippines",
    marketPriceSourceUrl: "https://www.heromotocorp.com/en-ph/products/premium/xpulse-200-4v.html",
    marketPriceCheckedAt: verifiedAt,
    priceContext: "Hero MotoCorp Philippines currently lists the XPulse 200 4V at ₱140,000. Confirm the exact dealer quote and current stock before purchase.",
    transmission: "Manual",
    summary: "Current Philippine 199.6cc dual-sport with 18.9 hp, 21/18-inch wheels, 220 mm ground clearance, an 825 mm seat and official ₱140,000 price."
  },
  {
    id: "hero-hunk-160r-4v",
    alsoKnownAs: ["Hero Hunk 160R", "Hunk 160R 4V", "Hero Hunk"],
    make: "Hero",
    makeSlug: "hero",
    model: "Hunk 160R 4V",
    slug: "hunk-160r-4v",
    generation: "Current Philippine model",
    category: "Naked street bike",
    srp: 99900,
    engineCc: 163.2,
    powerHp: 16.9,
    torqueNm: 14.6,
    curbWeightKg: 145,
    seatHeightMm: 795,
    fuelTankL: 12,
    groundClearanceMm: 165,
    frontTire: "100/80-17",
    rearTire: "130/70 R17",
    abs: "Single-channel ABS with 276 mm front petal disc and 220 mm rear petal disc",
    colors: ["Matte Sports Black", "Blazing Sports Red"],
    searchVolume: 80,
    keywordDifficulty: 0,
    sourceLabel: "Hero MotoCorp Philippines current Hunk 160R 4V product page",
    sourceUrl: "https://www.heromotocorp.com/en-ph/products/premium/hunk.html",
    verifiedAt,
    freshness: "verified",
    marketStatus: "current",
    marketPriceSourceLabel: "Hero MotoCorp Philippines",
    marketPriceSourceUrl: "https://www.heromotocorp.com/en-ph/products/premium/hunk.html",
    marketPriceCheckedAt: verifiedAt,
    priceContext: "Hero MotoCorp Philippines currently lists the Hunk 160R 4V at ₱99,900. Confirm final dealer stock and quote before purchase.",
    transmission: "Manual",
    summary: "Current Philippine 163.2cc naked street bike with 16.9 Ps, single-channel ABS, 145 kg curb weight, 795 mm seat and official ₱99,900 price."
  },
  {
    id: "hero-xoom-110",
    alsoKnownAs: ["Hero Xoom", "Xoom 110"],
    make: "Hero",
    makeSlug: "hero",
    model: "Xoom 110",
    slug: "xoom-110",
    generation: "Current Philippine model",
    category: "Commuter scooter",
    srp: 69900,
    engineCc: 110.9,
    powerHp: 8.05,
    torqueNm: 8.7,
    curbWeightKg: 109,
    seatHeightMm: 770,
    fuelTankL: 5.2,
    groundClearanceMm: 155,
    frontTire: "90/90-12",
    rearTire: "100/80-12",
    abs: "No ABS listed; front disc or drum depending on variant, rear drum with integrated braking system",
    colors: ["Matt Abrax Orange", "Polestar Blue", "Black", "Sports Red"],
    searchVolume: 0,
    keywordDifficulty: 0,
    sourceLabel: "Hero MotoCorp Philippines current Xoom 110 product page",
    sourceUrl: "https://www.heromotocorp.com/en-ph/products/scooter/xoom-110.html",
    verifiedAt,
    freshness: "verified",
    marketStatus: "current",
    marketPriceSourceLabel: "Hero MotoCorp Philippines",
    marketPriceSourceUrl: "https://www.heromotocorp.com/en-ph/products/scooter/xoom-110.html",
    marketPriceCheckedAt: verifiedAt,
    priceContext: "Hero MotoCorp Philippines currently lists the Xoom 110 at ₱69,900. Confirm the exact brake variant, dealer stock and final quote before purchase.",
    transmission: "Automatic",
    summary: "Current Philippine 110.9cc automatic scooter with 8.05 bhp, a 770 mm seat, 109 kg curb weight, 12-inch wheels and official ₱69,900 price."
  }
];
