import type { Motorcycle } from "./types";

const verifiedAt = "2026-10-04";

export const heroGapExpansion2026: Motorcycle[] = [
  {
    id: "hero-xpulse-200-4v",
    alsoKnownAs: ["Hero XPulse 200", "XPulse 200", "XPulse 200 4V"],
    make: "Hero",
    makeSlug: "hero",
    model: "XPulse 200 4V",
    slug: "xpulse-200-4v",
    generation: "Current Philippine model",
    category: "Dual-sport",
    srp: 140000,
    engineCc: 199.6,
    powerHp: 18.9,
    torqueNm: 17.35,
    curbWeightKg: 159,
    seatHeightMm: 825,
    fuelTankL: 13,
    groundClearanceMm: 220,
    frontTire: "90/90-21",
    rearTire: "120/80-18",
    abs: "Single-channel ABS with multi-terrain modes",
    colors: ["Metallic Nexus Blue White", "Black Sports Red", "Techno Blue Metallic Black"],
    searchVolume: 2100,
    keywordDifficulty: 0,
    sourceLabel: "Hero MotoCorp Philippines current XPulse 200 4V product page",
    sourceUrl: "https://www.heromotocorp.com/en-ph/products/premium/xpulse-200-4v.html",
    verifiedAt,
    freshness: "verified",
    marketStatus: "current",
    marketPriceSourceLabel: "Hero MotoCorp Philippines",
    marketPriceSourceUrl: "https://www.heromotocorp.com/en-ph/products/premium/xpulse-200-4v.html",
    marketPriceCheckedAt: verifiedAt,
    priceContext: "Hero MotoCorp Philippines currently lists the XPulse 200 4V at ₱140,000. Confirm the final dealer quote, registration and financing before purchase.",
    transmission: "Manual",
    summary: "Current Philippine 199.6cc dual-sport with 18.9 bhp, 17.35 Nm, 21/18-inch tires, 220 mm ground clearance, 825 mm seat and a 13 L tank."
  },
  {
    id: "hero-hunk-160r-4v",
    alsoKnownAs: ["Hero Hunk", "Hunk Bike", "Hunk 160R"],
    make: "Hero",
    makeSlug: "hero",
    model: "Hunk 160R 4V",
    slug: "hunk-160r-4v",
    generation: "Current Philippine model",
    category: "Naked street bike",
    srp: 99900,
    engineCc: 163.2,
    powerHp: 16.9,
    torqueNm: 14.6,
    curbWeightKg: 145,
    seatHeightMm: 795,
    fuelTankL: 12,
    groundClearanceMm: 165,
    frontTire: "100/80-17",
    rearTire: "130/70 R17",
    abs: "Single-channel ABS",
    colors: ["Matte Sports Black", "Blazing Sports Red"],
    searchVolume: 1600,
    keywordDifficulty: 0,
    sourceLabel: "Hero MotoCorp Philippines current Hunk 160R 4V product page",
    sourceUrl: "https://www.heromotocorp.com/en-ph/products/premium/hunk.html",
    verifiedAt,
    freshness: "verified",
    marketStatus: "current",
    marketPriceSourceLabel: "Hero MotoCorp Philippines",
    marketPriceSourceUrl: "https://www.heromotocorp.com/en-ph/products/premium/hunk.html",
    marketPriceCheckedAt: verifiedAt,
    priceContext: "Hero MotoCorp Philippines currently lists the Hunk 160R 4V at ₱99,900. Confirm the final dealer quote, registration and financing before purchase.",
    transmission: "Manual",
    summary: "Current Philippine 163.2cc naked motorcycle with 16.9 PS published output, 14.6 Nm, USD front forks, single-channel ABS, 795 mm seat and 12 L tank."
  },
  {
    id: "hero-xoom-110",
    alsoKnownAs: ["Hero Xoom", "Hero Xoom 110"],
    make: "Hero",
    makeSlug: "hero",
    model: "Xoom 110",
    slug: "xoom-110",
    generation: "Current Philippine model",
    category: "Commuter scooter",
    srp: 69900,
    engineCc: 110.9,
    powerHp: 8.05,
    torqueNm: 8.7,
    curbWeightKg: 109,
    seatHeightMm: 770,
    fuelTankL: 5.2,
    groundClearanceMm: 155,
    frontTire: "90/90-12",
    rearTire: "100/80-12",
    abs: "No ABS listed; front disc/drum variant and rear drum with integrated braking",
    colors: ["Matt Abrax Orange", "Polestar Blue", "Black", "Sports Red"],
    searchVolume: 0,
    keywordDifficulty: 0,
    sourceLabel: "Hero MotoCorp Philippines current Xoom 110 product page",
    sourceUrl: "https://www.heromotocorp.com/en-ph/products/scooter/xoom-110.html",
    verifiedAt,
    freshness: "verified",
    marketStatus: "current",
    marketPriceSourceLabel: "Hero MotoCorp Philippines",
    marketPriceSourceUrl: "https://www.heromotocorp.com/en-ph/products/scooter/xoom-110.html",
    marketPriceCheckedAt: verifiedAt,
    priceContext: "Hero MotoCorp Philippines currently lists the Xoom 110 at ₱69,900. Confirm the exact brake variant and final dealer quote before purchase.",
    transmission: "Automatic",
    summary: "Current Philippine 110.9cc automatic scooter with 8.05 bhp, 8.7 Nm, 12-inch tires, 770 mm seat, 109 kg curb weight and a 5.2 L tank."
  },
  {
    id: "hero-xoom-125r",
    alsoKnownAs: ["Hero Xoom 125", "Xoom 125R"],
    make: "Hero",
    makeSlug: "hero",
    model: "Xoom 125R",
    slug: "xoom-125r",
    generation: "Current Philippine model",
    category: "Commuter scooter",
    srp: 76900,
    engineCc: 124.6,
    powerHp: 9.79,
    torqueNm: 10.4,
    curbWeightKg: 121,
    seatHeightMm: 777,
    fuelTankL: 5,
    groundClearanceMm: 164,
    frontTire: "110/80-14",
    rearTire: "120/70-14",
    abs: "No ABS listed; 220 mm front disc and 130 mm rear drum",
    colors: ["Pearl Silver White", "Matte Nexus Blue", "Candy Blazing Red", "Matte Giallo Lime", "Matte Axis Grey Metallic"],
    searchVolume: 0,
    keywordDifficulty: 0,
    sourceLabel: "Hero MotoCorp Philippines current Xoom 125R product page",
    sourceUrl: "https://www.heromotocorp.com/en-ph/products/scooter/xoom-125r.html",
    verifiedAt,
    freshness: "verified",
    marketStatus: "current",
    marketPriceSourceLabel: "Hero MotoCorp Philippines",
    marketPriceSourceUrl: "https://www.heromotocorp.com/en-ph/products/scooter/xoom-125r.html",
    marketPriceCheckedAt: verifiedAt,
    priceContext: "Hero MotoCorp Philippines currently lists the Xoom 125R at ₱76,900. Confirm the exact dealer stock, fees and final quote before purchase.",
    transmission: "Automatic",
    summary: "Current Philippine 124.6cc automatic scooter with 9.8 hp-equivalent published output, 10.4 Nm, 14-inch tires, 777 mm seat and 5 L tank."
  }
];
