import type { Motorcycle } from "./types";

const verifiedAt = "2026-10-04";

export const highVolumeCloseout2026: Motorcycle[] = [
  {
    id: "cfmoto-450cl-c",
    alsoKnownAs: ["CFMOTO CLC 450", "CFMOTO 450 CL-C", "450CL-C"],
    make: "CFMOTO",
    makeSlug: "cfmoto",
    model: "450CL-C",
    slug: "450cl-c",
    generation: "Current Philippine model",
    category: "Cruiser",
    srp: 287900,
    engineCc: 449,
    powerHp: 40.2,
    torqueNm: 42,
    curbWeightKg: 181,
    seatHeightMm: 705,
    fuelTankL: 12,
    groundClearanceMm: 160,
    frontTire: "130/90-16",
    rearTire: "150/80-16",
    abs: "Dual-channel ABS with traction control",
    colors: [],
    searchVolume: 1900,
    keywordDifficulty: 0,
    sourceLabel: "CFMOTO Philippines current 450CL-C product page with CFMOTO global chassis specification cross-check",
    sourceUrl: "https://www.cfmotoph.com/motorcycle/450cl-c",
    verifiedAt,
    freshness: "verified",
    marketStatus: "current",
    marketPriceSourceLabel: "CFMOTO Philippines",
    marketPriceSourceUrl: "https://www.cfmotoph.com/motorcycle/450cl-c",
    marketPriceCheckedAt: verifiedAt,
    priceContext: "CFMOTO Philippines currently lists the 450CL-C at ₱287,900. Confirm the exact dealer stock, registration and financing before purchase.",
    transmission: "Manual",
    summary: "Current Philippine 449cc twin-cylinder cruiser with 40.2 hp-equivalent published output, 42 Nm, 705 mm seat, 181 kg curb weight, 12 L tank, dual-channel ABS and TCS."
  },
  {
    id: "cfmoto-250sr",
    alsoKnownAs: ["CF Moto 250SR", "250 SR", "CFMOTO 250 SR"],
    make: "CFMOTO",
    makeSlug: "cfmoto",
    model: "250SR",
    slug: "250sr",
    generation: "Current Philippine model",
    category: "Sport bike",
    srp: 138900,
    engineCc: 249,
    powerHp: 27.5,
    torqueNm: 22,
    curbWeightKg: 165,
    seatHeightMm: 765,
    fuelTankL: 12,
    groundClearanceMm: 135,
    frontTire: "110/70 R17",
    rearTire: "140/60 R17",
    abs: "ABS",
    colors: [],
    searchVolume: 1100,
    keywordDifficulty: 0,
    sourceLabel: "CFMOTO Philippines current 250SR product page with CFMOTO technical-brochure chassis cross-check",
    sourceUrl: "https://www.cfmotoph.com/motorcycle/250sr",
    verifiedAt,
    freshness: "verified",
    marketStatus: "current",
    marketPriceSourceLabel: "CFMOTO Philippines",
    marketPriceSourceUrl: "https://www.cfmotoph.com/motorcycle/250sr",
    marketPriceCheckedAt: verifiedAt,
    priceContext: "CFMOTO Philippines currently lists the 250SR at ₱138,900. The Philippine product page publishes 165 kg curb weight and 765 mm seat height; exact dealer stock and final fees should still be confirmed.",
    transmission: "Manual",
    summary: "Current Philippine 249cc single-cylinder sport bike with 27.5 hp-equivalent published output, 22 Nm, ABS, 765 mm seat and a current ₱138,900 official price."
  },
  {
    id: "cfmoto-125-st-papio",
    alsoKnownAs: ["CFMOTO Papio", "CF Moto Papio", "ST Papio", "125 ST Papio"],
    make: "CFMOTO",
    makeSlug: "cfmoto",
    model: "125 ST Papio",
    slug: "125-st-papio",
    generation: "Current Philippine model",
    category: "Mini bike",
    srp: 90900,
    engineCc: 126,
    powerHp: 9.4,
    torqueNm: 9.2,
    curbWeightKg: 114,
    seatHeightMm: 775,
    fuelTankL: 7,
    groundClearanceMm: 145,
    frontTire: "120/70 R12",
    rearTire: "130/70 R12",
    abs: "Current Philippine product page confirms disc brakes; exact ABS equipment should be confirmed with the dealer",
    colors: [],
    searchVolume: 900,
    keywordDifficulty: 0,
    sourceLabel: "CFMOTO Philippines current 125 ST Papio product page with Philippine legacy-spec and current market dimension cross-check",
    sourceUrl: "https://www.cfmotoph.com/motorcycle/125-st-papio",
    verifiedAt,
    freshness: "verified",
    marketStatus: "current",
    marketPriceSourceLabel: "CFMOTO Philippines",
    marketPriceSourceUrl: "https://www.cfmotoph.com/motorcycle/125-st-papio",
    marketPriceCheckedAt: verifiedAt,
    priceContext: "CFMOTO Philippines currently lists the 125 ST Papio at ₱90,900. Older Philippine comparison pages may still show the previous ₱78,000 price, so use the current CFMOTO Philippines listing as the price baseline.",
    transmission: "Manual",
    summary: "Current Philippine 126cc mini bike with a six-speed gearbox, 9.4 hp-equivalent published output, 114 kg curb weight, 775 mm seat and 12-inch tires."
  },
  {
    id: "zontes-400m",
    alsoKnownAs: ["Bristol Zontes 400M", "Zontes 400M V2", "400M"],
    make: "Zontes",
    makeSlug: "zontes",
    model: "400M",
    slug: "400m",
    generation: "Current Philippine Version 2",
    category: "Maxi scooter",
    srp: 328800,
    engineCc: 400,
    powerHp: 38,
    torqueNm: 40,
    curbWeightKg: 175,
    seatHeightMm: 770,
    fuelTankL: 12,
    groundClearanceMm: 150,
    frontTire: "14-inch front wheel; exact tire size verify with dealer",
    rearTire: "13-inch rear wheel; exact tire size verify with dealer",
    abs: "Dual-channel ABS with traction control",
    colors: [],
    searchVolume: 2500,
    keywordDifficulty: 0,
    sourceLabel: "Bristol Motorcycles current Zontes 400M product page with Philippine specification cross-check",
    sourceUrl: "https://www.bristol-motorcycles.com/400m",
    verifiedAt,
    freshness: "verified",
    marketStatus: "current",
    marketPriceHighPhp: 338800,
    marketPriceSourceLabel: "Current Philippine 400M market references",
    marketPriceSourceUrl: "https://www.motopinas.com/buyers-guide/undated/zontes/400m/specs/",
    marketPriceCheckedAt: verifiedAt,
    priceContext: "Current Philippine sources show a pricing discrepancy: broad comparison listings still show ₱328,800, while current Version 2 references show about ₱338,000–₱338,800. MotoIndex stores the observed range and recommends confirming the exact Version 2 branch quote.",
    transmission: "Automatic",
    summary: "Current Philippine 400cc maxi-scooter with 38 hp, 40 Nm, CVT, 12 L tank, roughly 175 kg curb weight and dual-channel ABS/TCS; current Version 2 pricing should be confirmed with the dealer."
  },
  {
    id: "bmw-motorrad-r18",
    alsoKnownAs: ["BMW R18", "BMW R 18"],
    make: "BMW Motorrad",
    makeSlug: "bmw-motorrad",
    model: "R 18",
    slug: "r-18",
    generation: "Philippine-market R 18",
    category: "Heritage cruiser",
    srp: 1955000,
    engineCc: 1802,
    powerHp: 90,
    torqueNm: 158,
    curbWeightKg: 345,
    seatHeightMm: 690,
    fuelTankL: 16,
    groundClearanceMm: 146,
    frontTire: "120/70 R19",
    rearTire: "180/55 B16",
    abs: "ABS with BMW rider-assistance systems",
    colors: [],
    searchVolume: 2400,
    keywordDifficulty: 0,
    sourceLabel: "Current Philippine R 18 market specification with BMW Motorrad current R 18 family cross-check",
    sourceUrl: "https://www.zigwheels.ph/new-motorcycles/bmw/r18",
    verifiedAt,
    freshness: "verified",
    marketStatus: "uncertain",
    marketPriceSourceLabel: "Current Philippine R 18 market reference",
    marketPriceSourceUrl: "https://www.zigwheels.ph/new-motorcycles/bmw/r18/price",
    marketPriceCheckedAt: verifiedAt,
    priceContext: "Current Philippine comparison listings show the BMW R 18 at ₱1.955 million. BMW Motorrad's global current catalog still includes the R 18 family, but MotoIndex has not located a sufficiently clear current BMW Motorrad Philippines model page, so local availability remains dealer-verification required.",
    transmission: "Manual",
    summary: "1,802cc BMW heritage cruiser research record with 90 hp, 158 Nm, 690 mm seat and current Philippine ₱1.955M market reference; official local model-page availability should be confirmed."
  },
  {
    id: "honda-cb500x",
    alsoKnownAs: ["Honda CB500X", "CB 500X", "CB500 X"],
    make: "Honda",
    makeSlug: "honda",
    model: "CB500X",
    slug: "cb500x",
    generation: "Previous Philippine CB500X generation",
    category: "Adventure touring",
    srp: 384000,
    engineCc: 471,
    powerHp: 46.9,
    torqueNm: 43,
    curbWeightKg: 199,
    seatHeightMm: 834,
    fuelTankL: 17.7,
    fuelConsumptionKmL: 27.8,
    groundClearanceMm: 181,
    frontTire: "110/80-19",
    rearTire: "160/60-17",
    abs: "2-channel ABS",
    colors: [],
    searchVolume: 2000,
    keywordDifficulty: 0,
    sourceLabel: "Honda Philippines 2023 CB500X official big-bike brochure",
    sourceUrl: "https://www.hondaph.com/honda-bigbikes/files/products/63d08302db1b9.pdf",
    verifiedAt,
    freshness: "verified",
    marketStatus: "previous",
    priceContext: "₱384,000 is the historical Honda Philippines 2023 CB500X price, not a current new-bike quote. Current shoppers should compare the successor-generation NX500 E-Clutch.",
    transmission: "Manual",
    successorId: "honda-nx500-e-clutch",
    summary: "Previous Philippine 471cc CB500X with 46.9 hp-equivalent output, 43 Nm, 834 mm seat, 17.7 L tank and 2-channel ABS; current new-bike research should move to the NX500."
  }
];
