import type { Motorcycle } from "./types";

const verifiedAt = "2026-10-04";

export const historicalGapCloseout2026: Motorcycle[] = [
  {
      id: "honda-supra-gtr150",
      alsoKnownAs: ["Honda Supra GTR150", "Honda Supra GTR 150", "Supra GTR150", "Supra GTR 150"],
      make: "Honda",
      makeSlug: "honda",
      model: "Supra GTR150",
      slug: "supra-gtr-150",
      generation: "2019 Philippine launch generation",
      category: "Sport underbone",
      srp: 102900,
      engineCc: 150,
      powerHp: 15.4,
      torqueNm: 13.6,
      curbWeightKg: 121,
      seatHeightMm: 786,
      fuelTankL: 4.5,
      fuelConsumptionKmL: 42,
      groundClearanceMm: 150,
      frontTire: "90/80-17",
      rearTire: "120/70-17",
      abs: "No ABS claim verified; front and rear disc brakes",
      colors: ["Valiant Red", "Black"],
      searchVolume: 1200,
      keywordDifficulty: 1,
      sourceLabel: "Honda Philippines official Supra GTR150 launch with archived Philippine specification cross-check",
      sourceUrl: "https://www.hondaph.com/motorcycle/news/honda-philippines-launches-supra-gtr150-the-speed-aggressor-bike-for-the-sporty-city-riders",
      verifiedAt,
      freshness: "verified",
      marketStatus: "previous",
      marketPriceSourceLabel: "Honda Philippines official 2019 launch",
      marketPriceSourceUrl: "https://www.hondaph.com/motorcycle/news/honda-philippines-launches-supra-gtr150-the-speed-aggressor-bike-for-the-sporty-city-riders",
      marketPriceCheckedAt: verifiedAt,
      priceContext: "Honda Philippines launched the Supra GTR150 at ₱102,900 in 2019. The current Honda Philippines product selector no longer surfaces this model, so MotoIndex treats that amount as historical launch-price context rather than a 2026 new-bike quote.",
      transmission: "Manual",
      summary: "Previous-generation 150cc sport underbone with a six-speed DOHC engine, 121 kg curb weight, 786 mm seat, 4.5 L tank and front/rear disc brakes, retained for historical and used-bike research."
    },
  {
      id: "kawasaki-w175",
      alsoKnownAs: ["Kawasaki W 175"],
      make: "Kawasaki",
      makeSlug: "kawasaki",
      model: "W175",
      slug: "w175",
      generation: "Previous Philippine W175 generation",
      category: "Classic street bike",
      srp: 130000,
      engineCc: 177,
      powerHp: 13,
      torqueNm: 13.2,
      curbWeightKg: 135,
      seatHeightMm: 790,
      fuelTankL: 12,
      groundClearanceMm: 165,
      frontTire: "80/100-17",
      rearTire: "100/90-17",
      abs: "No ABS asserted for the historical Philippine model; front disc and rear drum",
      colors: ["Black"],
      searchVolume: 600,
      keywordDifficulty: 2,
      sourceLabel: "Philippine discontinued-model reference and historical W175 specification cross-check",
      sourceUrl: "https://www.zigwheels.ph/new-motorcycles/kawasaki/w175",
      verifiedAt,
      freshness: "verified",
      marketStatus: "discontinued",
      marketPriceSourceLabel: "ZigWheels Philippines historical W175 price reference",
      marketPriceSourceUrl: "https://www.zigwheels.ph/new-motorcycles/kawasaki/w175",
      marketPriceCheckedAt: verifiedAt,
      priceContext: "ZigWheels Philippines marks the W175 as discontinued and retains ₱130,000 as its historical Philippine price reference. Use that figure for generation context, not as a current new-bike quote.",
      transmission: "Manual",
      summary: "Discontinued Philippine 177cc classic road bike with 13 hp, 13.2 Nm, five-speed transmission, 790 mm seat, 12 L tank and historical ₱130,000 price reference."
    },
  {
      id: "kawasaki-ninja-250sl",
      alsoKnownAs: ["Ninja 250 SL", "Kawasaki 250SL"],
      make: "Kawasaki",
      makeSlug: "kawasaki",
      model: "Ninja 250SL",
      slug: "ninja-250sl",
      generation: "Previous Philippine 250SL generation",
      category: "Sport bike",
      srp: 195000,
      engineCc: 249,
      powerHp: 28,
      torqueNm: 22.6,
      curbWeightKg: 151,
      seatHeightMm: 780,
      fuelTankL: 11,
      groundClearanceMm: 165,
      frontTire: "100/80-17",
      rearTire: "130/70-17",
      abs: "ABS availability varied by variant; front and rear disc brakes",
      colors: [],
      searchVolume: 600,
      keywordDifficulty: 2,
      sourceLabel: "Philippine discontinued-model price and specification reference",
      sourceUrl: "https://www.carmudi.com.ph/new-motorcycles/kawasaki/ninja-250sl/standard/",
      verifiedAt,
      freshness: "verified",
      marketStatus: "discontinued",
      marketPriceSourceLabel: "Carmudi Philippines historical Ninja 250SL reference",
      marketPriceSourceUrl: "https://www.carmudi.com.ph/new-motorcycles/kawasaki/ninja-250sl/price/makati/",
      marketPriceCheckedAt: verifiedAt,
      priceContext: "Current Philippine comparison references mark the Ninja 250SL as discontinued and retain ₱195,000 as a historical price. Compare used units on year, condition, mileage, service history and documentation rather than the old SRP alone.",
      transmission: "Manual",
      summary: "Discontinued 249cc single-cylinder Ninja with 28 hp, 22.6 Nm, six-speed transmission, 780 mm seat, 151 kg curb weight and 11 L fuel tank."
    },
  {
      id: "yamaha-vega-force-i",
      alsoKnownAs: ["Yamaha Vega Force", "Vega Force i", "Vega Force FI"],
      make: "Yamaha",
      makeSlug: "yamaha",
      model: "Vega Force i",
      slug: "vega-force-i",
      generation: "Previous Philippine fuel-injected generation",
      category: "Underbone",
      srp: 68200,
      engineCc: 114,
      powerHp: 9.9,
      torqueNm: 9.9,
      curbWeightKg: 101,
      seatHeightMm: 765,
      fuelTankL: 4.1,
      groundClearanceMm: 150,
      frontTire: "70/90-17",
      rearTire: "80/90-17",
      abs: "No ABS; front disc and rear drum",
      colors: ["Red Metallic", "Blue", "Black Raven"],
      searchVolume: 500,
      keywordDifficulty: 1,
      sourceLabel: "Philippine discontinued Vega Force i specification and historical price reference",
      sourceUrl: "https://www.zigwheels.ph/new-motorcycles/yamaha/vega-force-i/standard",
      verifiedAt,
      freshness: "verified",
      marketStatus: "discontinued",
      marketPriceSourceLabel: "ZigWheels Philippines historical Vega Force i price reference",
      marketPriceSourceUrl: "https://www.zigwheels.ph/new-motorcycles/yamaha/vega-force-i/standard",
      marketPriceCheckedAt: verifiedAt,
      priceContext: "Philippine comparison references mark the Vega Force i as discontinued and retain ₱68,200 as its historical price. Use the page for owner, specification and used-bike research rather than current new-bike shopping.",
      transmission: "Manual",
      summary: "Discontinued Philippine 114cc fuel-injected underbone with 9.9 hp, 9.9 Nm, four-speed transmission, 765 mm seat, 101 kg curb weight and 4.1 L tank."
    },
  {
    id: "yamaha-yzf-r6",
    alsoKnownAs: ["Yamaha R6", "YZF-R6", "Yamaha YZF R6"],
    make: "Yamaha",
    makeSlug: "yamaha",
    model: "YZF-R6",
    slug: "yzf-r6",
    generation: "2017-2020 road-going generation",
    category: "Sport bike",
    srp: 749000,
    engineCc: 599,
    powerHp: 116.8,
    torqueNm: 61.7,
    curbWeightKg: 190,
    seatHeightMm: 850,
    fuelTankL: 17,
    groundClearanceMm: 130,
    frontTire: "120/70ZR17",
    rearTire: "180/55ZR17",
    abs: "ABS equipped; dual 320 mm front discs and 220 mm rear disc",
    colors: ["Race Blu", "Tech Black"],
    searchVolume: 0,
    keywordDifficulty: 0,
    sourceLabel: "Philippine Yamaha YZF-R6 launch price and specification reference with Yamaha 2020 specification cross-check",
    sourceUrl: "https://www.motoph.com/the-all-new-yamaha-yzf-r6-specifications-availability-and-price/",
    verifiedAt,
    freshness: "verified",
    marketStatus: "discontinued",
    marketPriceSourceLabel: "MotoPH Philippine YZF-R6 launch coverage",
    marketPriceSourceUrl: "https://www.motoph.com/the-all-new-yamaha-yzf-r6-specifications-availability-and-price/",
    marketPriceCheckedAt: verifiedAt,
    priceContext: "The Philippine YZF-R6 launched at ₱749,000. The road-going model is discontinued, so keep ₱749,000 as the last published local new-bike reference and verify actual used-unit pricing, condition and documentation separately.",
    transmission: "Manual",
    summary: "599cc inline-four supersport with 116.8 hp, 61.7 Nm, six-speed transmission, 850 mm seat, 190 kg curb weight, 17 L tank, ABS and the last published Philippine new-bike price of ₱749,000."
  }
];
