import type { Motorcycle } from "./types";

const verifiedAt = "2026-10-04";

// High-demand legacy/availability-gap models retained for historical price,
// used-bike and owner research. None of these are promoted into the current
// national catalog without current manufacturer evidence.
export const legacyModelCloseout2026: Motorcycle[] = [
  {
    id: "honda-supra-gtr-150",
    alsoKnownAs: ["Honda Supra GTR150", "Supra GTR 150", "Honda GTR150"],
    make: "Honda",
    makeSlug: "honda",
    model: "Supra GTR150",
    slug: "supra-gtr-150",
    generation: "Philippine-market 150cc generation",
    category: "Sport underbone",
    srp: 106900,
    engineCc: 150,
    powerHp: 15.42,
    torqueNm: 13.6,
    curbWeightKg: 118,
    seatHeightMm: 786,
    fuelTankL: 4.5,
    fuelConsumptionKmL: 42,
    groundClearanceMm: 146,
    frontTire: "90/80-17",
    rearTire: "120/70-17",
    abs: "No ABS listed; hydraulic front and rear disc brakes",
    colors: ["Valiant Red", "Black"],
    searchVolume: 1200,
    keywordDifficulty: 1,
    sourceLabel: "Current Philippine dealer listing with Honda Philippines historical model specification cross-check",
    sourceUrl: "https://wheeltek.com.ph/motorcycles/gtr150/",
    verifiedAt,
    freshness: "verified",
    marketStatus: "uncertain",
    marketPriceSourceLabel: "Wheeltek current Supra GTR150 listing",
    marketPriceSourceUrl: "https://wheeltek.com.ph/motorcycles/gtr150/",
    marketPriceCheckedAt: verifiedAt,
    priceContext: "Wheeltek currently lists the Supra GTR150 from ₱106,900, but MotoIndex did not find it in Honda Philippines' current national motorcycle catalog. Treat availability as dealer-stock dependent and confirm the exact model year before purchase.",
    transmission: "Manual",
    successorId: "honda-winner-x",
    summary: "150cc six-speed sport underbone with 15.42 hp, 13.6 Nm, 118 kg curb mass, 786 mm seat, 42 km/L published fuel-economy reference and dealer-level Philippine availability that should be confirmed before purchase."
  },
  {
    id: "kawasaki-w175",
    alsoKnownAs: ["Kawasaki W 175"],
    make: "Kawasaki",
    makeSlug: "kawasaki",
    model: "W175",
    slug: "w175",
    generation: "Previous Philippine W175 generation",
    category: "Classic street bike",
    srp: 130000,
    engineCc: 177,
    powerHp: 13,
    torqueNm: 13.2,
    curbWeightKg: 135,
    seatHeightMm: 790,
    fuelTankL: 12,
    groundClearanceMm: 165,
    frontTire: "80/100-17",
    rearTire: "100/90-17",
    abs: "No ABS asserted for the historical Philippine model; front disc and rear drum",
    colors: ["Black"],
    searchVolume: 600,
    keywordDifficulty: 2,
    sourceLabel: "Philippine discontinued-model reference and historical W175 specification cross-check",
    sourceUrl: "https://www.zigwheels.ph/new-motorcycles/kawasaki/w175",
    verifiedAt,
    freshness: "verified",
    marketStatus: "discontinued",
    marketPriceSourceLabel: "ZigWheels Philippines historical W175 price reference",
    marketPriceSourceUrl: "https://www.zigwheels.ph/new-motorcycles/kawasaki/w175",
    marketPriceCheckedAt: verifiedAt,
    priceContext: "ZigWheels Philippines marks the W175 as discontinued and retains ₱130,000 as its historical Philippine price reference. Use that figure for generation context, not as a current new-bike quote.",
    transmission: "Manual",
    summary: "Discontinued Philippine 177cc classic road bike with 13 hp, 13.2 Nm, five-speed transmission, 790 mm seat, 12 L tank and historical ₱130,000 price reference."
  },
  {
    id: "kawasaki-ninja-250sl",
    alsoKnownAs: ["Ninja 250 SL", "Kawasaki 250SL"],
    make: "Kawasaki",
    makeSlug: "kawasaki",
    model: "Ninja 250SL",
    slug: "ninja-250sl",
    generation: "Previous Philippine 250SL generation",
    category: "Sport bike",
    srp: 195000,
    engineCc: 249,
    powerHp: 28,
    torqueNm: 22.6,
    curbWeightKg: 151,
    seatHeightMm: 780,
    fuelTankL: 11,
    groundClearanceMm: 165,
    frontTire: "100/80-17",
    rearTire: "130/70-17",
    abs: "ABS availability varied by variant; front and rear disc brakes",
    colors: [],
    searchVolume: 600,
    keywordDifficulty: 2,
    sourceLabel: "Philippine discontinued-model price and specification reference",
    sourceUrl: "https://www.carmudi.com.ph/new-motorcycles/kawasaki/ninja-250sl/standard/",
    verifiedAt,
    freshness: "verified",
    marketStatus: "discontinued",
    marketPriceSourceLabel: "Carmudi Philippines historical Ninja 250SL reference",
    marketPriceSourceUrl: "https://www.carmudi.com.ph/new-motorcycles/kawasaki/ninja-250sl/price/makati/",
    marketPriceCheckedAt: verifiedAt,
    priceContext: "Current Philippine comparison references mark the Ninja 250SL as discontinued and retain ₱195,000 as a historical price. Compare used units on year, condition, mileage, service history and documentation rather than the old SRP alone.",
    transmission: "Manual",
    summary: "Discontinued 249cc single-cylinder Ninja with 28 hp, 22.6 Nm, six-speed transmission, 780 mm seat, 151 kg curb weight and 11 L fuel tank."
  },
  {
    id: "yamaha-vega-force-i",
    alsoKnownAs: ["Yamaha Vega Force", "Vega Force i", "Vega Force FI"],
    make: "Yamaha",
    makeSlug: "yamaha",
    model: "Vega Force i",
    slug: "vega-force-i",
    generation: "Previous Philippine fuel-injected generation",
    category: "Underbone",
    srp: 68200,
    engineCc: 114,
    powerHp: 9.9,
    torqueNm: 9.9,
    curbWeightKg: 101,
    seatHeightMm: 765,
    fuelTankL: 4.1,
    groundClearanceMm: 150,
    frontTire: "70/90-17",
    rearTire: "80/90-17",
    abs: "No ABS; front disc and rear drum",
    colors: ["Red Metallic", "Blue", "Black Raven"],
    searchVolume: 500,
    keywordDifficulty: 1,
    sourceLabel: "Philippine discontinued Vega Force i specification and historical price reference",
    sourceUrl: "https://www.zigwheels.ph/new-motorcycles/yamaha/vega-force-i/standard",
    verifiedAt,
    freshness: "verified",
    marketStatus: "discontinued",
    marketPriceSourceLabel: "ZigWheels Philippines historical Vega Force i price reference",
    marketPriceSourceUrl: "https://www.zigwheels.ph/new-motorcycles/yamaha/vega-force-i/standard",
    marketPriceCheckedAt: verifiedAt,
    priceContext: "Philippine comparison references mark the Vega Force i as discontinued and retain ₱68,200 as its historical price. Use the page for owner, specification and used-bike research rather than current new-bike shopping.",
    transmission: "Manual",
    summary: "Discontinued Philippine 114cc fuel-injected underbone with 9.9 hp, 9.9 Nm, four-speed transmission, 765 mm seat, 101 kg curb weight and 4.1 L tank."
  }
];
