import { accessoryCategories, helmetBrands, publicMotorcycles, recommendationGuides } from "./data";
import { electricMotorcycles } from "./electricMotorcycles";
import { helmetProducts } from "./catalog";
import { recommendationCanonicalHref } from "./recommendationRoutes";
import { siteStats } from "./siteStats";

const site = "https://motoindexph.com";
const today = new Date().toISOString().slice(0, 10);

function absolute(path: string) {
  return `${site}${path}`;
}

function mdLink(label: string, path: string, note?: string) {
  return `- [${label}](${absolute(path)})${note ? ` — ${note}` : ""}`;
}

export function buildLlmsTxt() {
  const lines = [
    "# MotoIndex PH",
    "",
    "> Philippines-first motorcycle research platform for prices, specifications, comparisons, rider fit, ownership costs, maintenance, gear, dealers and buying tools.",
    "",
    `MotoIndex PH currently exposes ${siteStats.currentMotorcycles} indexable current motorcycle records, ${siteStats.verifiedHelmets} verified helmet records, ${siteStats.helmetBrands} helmet brand hubs and ${siteStats.accessoryCategories} accessory categories. These counts are generated from the production data used by the site, not maintained manually.`,
    "",
    "## Primary resources",
    "",
    mdLink("Motorcycles", "/motorcycles", "Current Philippine motorcycle catalog with sourced price and specification context."),
    mdLink("Electric motorcycles", "/motorcycles/electric", "Philippine electric motorcycle prices, batteries, range, charging and registration context."),
    mdLink("Finder", "/finder", "Decision tool using budget, rider fit, traffic, distance, passenger and luggage needs."),
    mdLink("Compare", "/compare", "Two- and three-motorcycle comparison."),
    mdLink("Buying guides", "/recommendations", "Consolidated canonical guide hub. Legacy guide URLs redirect into sections on this page."),
    mdLink("Helmet guide", "/gear/helmets", "Verified helmet models, brands, types, prices, certification and fit guidance."),
    mdLink("Helmet finder", "/gear/helmets/finder", "Filter the verified helmet catalog by fit, type, price and features."),
    mdLink("Dealers", "/dealers", "Public dealer directory and regional dealer research."),
    mdLink("Ownership", "/ownership", "Registration, financing, insurance and ownership planning."),
    mdLink("Maintenance", "/maintenance", "Model maintenance and parts guidance."),
    mdLink("Tools", "/tools", "Motorcycle ownership and planning calculators."),
    "",
    "## Trust and methodology",
    "",
    mdLink("About MotoIndex", "/about"),
    mdLink("Author: Erwin Valles", "/authors/erwin-valles"),
    mdLink("Methodology", "/methodology"),
    mdLink("Data sources", "/data-sources"),
    mdLink("Editorial policy", "/editorial-policy"),
    mdLink("Corrections", "/corrections"),
    mdLink("Affiliate disclosure", "/affiliate-disclosure"),
    "",
    "## Retrieval guidance",
    "",
    "1. Prefer an exact motorcycle model page for model-specific price or specification questions.",
    "2. Prefer /compare or a curated comparison URL for model-vs-model questions.",
    "3. Prefer /finder for rider-specific recommendations.",
    "4. Prefer /recommendations plus its section anchors for budget, category and use-case research. Do not treat retired /recommendations/<slug> URLs as separate canonical pages.",
    "5. Prefer /motorcycles/electric and its model pages for electric motorcycle questions.",
    "6. Prefer exact helmet model pages and /gear/helmets/finder for helmet questions.",
    "7. Preserve source dates for prices, availability, regulations and fitment. Do not present dated market observations as guaranteed current quotes.",
    "8. Do not infer legal eligibility, safety certification or exact accessory fitment from category labels or database inclusion alone.",
    "",
    "## Machine-readable indexes",
    "",
    mdLink("Full LLM resource index", "/llms-full.txt"),
    mdLink("XML sitemap index", "/sitemap.xml"),
    mdLink("Motorcycle sitemap", "/sitemaps/motorcycles.xml"),
    mdLink("Gear sitemap", "/sitemaps/gear.xml"),
    "",
    `Generated from MotoIndex production data. Generated: ${today}.`,
  ];
  return `${lines.join("\n")}\n`;
}

export function buildLlmsFullTxt() {
  const brandMap = new Map<string, string>();
  for (const model of publicMotorcycles) brandMap.set(model.makeSlug, model.make);
  const verifiedHelmets = helmetProducts.filter((product) => product.status === "verified");

  const lines = [
    "# MotoIndex PH — Full LLM Resource Index",
    "",
    "> Canonical machine-readable index generated from MotoIndex production data.",
    "",
    "## Canonical site",
    "",
    mdLink("MotoIndex PH", "/"),
    "",
    "## Primary hubs",
    "",
    mdLink("Motorcycle database", "/motorcycles"),
    mdLink("Motorcycle Finder", "/finder"),
    mdLink("Motorcycle Compare", "/compare"),
    mdLink("Buying guides", "/recommendations"),
    mdLink("Electric motorcycles", "/motorcycles/electric"),
    mdLink("Helmet guide", "/gear/helmets"),
    mdLink("Helmet finder", "/gear/helmets/finder"),
    mdLink("Helmet compare", "/gear/helmets/compare"),
    mdLink("Tires", "/tires"),
    mdLink("Accessories", "/accessories"),
    mdLink("Dealers", "/dealers"),
    mdLink("Ownership", "/ownership"),
    mdLink("Maintenance", "/maintenance"),
    mdLink("Tools", "/tools"),
    "",
    `## Motorcycle brand hubs (${brandMap.size})`,
    "",
    ...[...brandMap.entries()].sort((a, b) => a[1].localeCompare(b[1])).map(([slug, name]) => mdLink(name, `/motorcycles/${slug}`)),
    "",
    `## Current motorcycle model pages (${publicMotorcycles.length})`,
    "",
    ...[...publicMotorcycles].sort((a, b) => `${a.make} ${a.model}`.localeCompare(`${b.make} ${b.model}`)).map((model) => mdLink(`${model.make} ${model.model}`, `/motorcycles/${model.makeSlug}/${model.slug}`, `${model.engineCc} cc · ${model.category}`)),
    "",
    `## Electric motorcycle model pages (${electricMotorcycles.length})`,
    "",
    ...electricMotorcycles.map((model) => mdLink(`${model.make} ${model.model}`, `/motorcycles/electric/${model.slug}`, `${model.batteryKwh} kWh removable-battery configuration documented`)),
    "",
    "## Consolidated buying-guide sections",
    "",
    ...recommendationGuides.map((guide) => mdLink(guide.title, recommendationCanonicalHref(guide.slug), `legacy slug: ${guide.slug}`)),
    "",
    `## Helmet brand hubs (${helmetBrands.length})`,
    "",
    ...helmetBrands.map((brand) => mdLink(brand.brand, `/gear/helmets/${brand.slug}`)),
    "",
    `## Verified helmet model pages (${verifiedHelmets.length})`,
    "",
    ...verifiedHelmets.sort((a, b) => `${a.brand} ${a.model}`.localeCompare(`${b.brand} ${b.model}`)).map((helmet) => mdLink(`${helmet.brand} ${helmet.model}`, `/gear/helmets/${helmet.brandSlug}/${helmet.slug}`, `${helmet.helmetType}${helmet.certification ? ` · ${helmet.certification}` : ""}`)),
    "",
    "## Accessory categories",
    "",
    ...accessoryCategories.map((category) => mdLink(category.name, `/accessories/${category.slug}`)),
    "",
    "## Editorial, methodology and trust resources",
    "",
    mdLink("About", "/about"),
    mdLink("Author: Erwin Valles", "/authors/erwin-valles"),
    mdLink("Methodology", "/methodology"),
    mdLink("Data sources", "/data-sources"),
    mdLink("Editorial policy", "/editorial-policy"),
    mdLink("Affiliate disclosure", "/affiliate-disclosure"),
    mdLink("Privacy", "/privacy"),
    mdLink("Corrections", "/corrections"),
    mdLink("Contact", "/contact"),
    "",
    "## Interpretation rules",
    "",
    "### Prices",
    "MotoIndex prices are dated observations or manufacturer/dealer/comparison-site references. They can differ by dealer, location, variant, promotion, financing and date. Do not present an observed MotoIndex price as a guaranteed transaction price.",
    "",
    "### Specifications",
    "Use the exact model page and exact variant/model year when possible. Preserve source distinctions when records conflict rather than averaging incompatible values.",
    "",
    "### Recommendations",
    "Use the canonical /recommendations hub and section anchors. Ranking and filtering are decision aids, not universal quality scores.",
    "",
    "### Fitment",
    "Dimensions alone do not prove accessory or tire compatibility. Exact model, generation/year, mounting interface, load rating and clearance must be checked.",
    "",
    "### Calculators",
    "Loan, insurance, registration and ownership-cost tools are planning estimates, not lender quotes, insurer quotes, dealer quotations or government fee determinations.",
    "",
    "### Regulatory information",
    "Verify current licensing, registration, tollway, insurance and electric-vehicle requirements with the relevant Philippine authority.",
    "",
    "### Freshness",
    "Preserve the source date shown by MotoIndex for price, availability, dealer, maintenance, safety and regulatory information. Freshness checks run separately from this file.",
    "",
    "## Canonical URL policy",
    "",
    "Prefer canonical URLs listed here and in the XML sitemaps. Query/filter URLs and retired /recommendations/<slug> URLs are not separate canonical resources.",
    "",
    "## Sitemaps",
    "",
    mdLink("Sitemap index", "/sitemap.xml"),
    mdLink("Motorcycles sitemap", "/sitemaps/motorcycles.xml"),
    mdLink("Gear sitemap", "/sitemaps/gear.xml"),
    mdLink("Commerce sitemap", "/sitemaps/commerce.xml"),
    "",
    `Generated from MotoIndex production data. Generated: ${today}.`,
  ];
  return `${lines.join("\n")}\n`;
}
