import type { Motorcycle } from "./types";

// Motortrade keyword-gap batch · checked 2026-10-01.
// Historical generations stay separate from current-model pricing so search
// demand for V1/legacy names does not overwrite current family records.
export const motortradeGapExpansion2026: Motorcycle[] = [
  {
    id: "yamaha-mio-soul-i-125",
    alsoKnownAs: ["Yamaha Mio Soul i125", "Mio Soul i 125", "Mio Soul i125"],
    make: "Yamaha",
    makeSlug: "yamaha",
    model: "Mio Soul i 125",
    slug: "mio-soul-i-125",
    generation: "Current",
    marketStatus: "current",
    category: "Commuter scooter",
    srp: 79900,
    engineCc: 125,
    powerHp: 9.3,
    torqueNm: 9.6,
    curbWeightKg: 96,
    seatHeightMm: 775,
    fuelTankL: 4.2,
    groundClearanceMm: 135,
    frontTire: "80/80-14",
    rearTire: "100/70-14",
    abs: "No ABS listed; front disc and rear drum",
    colors: [],
    searchVolume: 9700,
    keywordDifficulty: 0,
    sourceLabel: "Zigwheels Philippines current 2026 Mio Soul i 125 price and specification reference",
    sourceUrl: "https://www.zigwheels.ph/new-motorcycles/yamaha/mio-soul-i-125/specifications",
    verifiedAt: "2026-10-01",
    freshness: "verified",
    marketPriceHighPhp: 83900,
    marketPriceSourceLabel: "Zigwheels Philippines current 2026 Standard and S variant reference",
    marketPriceSourceUrl: "https://www.zigwheels.ph/new-motorcycles/yamaha/mio-soul-i-125",
    marketPriceCheckedAt: "2026-10-01",
    priceContext: "Current Philippine comparison listings show ₱79,900 for the Standard and ₱83,900 for the S variant. Confirm final branch pricing, stock and the exact variant before financing.",
    transmission: "Automatic",
    summary: "Current dealer-listed 125cc automatic scooter with a 775 mm seat, 96 kg standard-variant curb weight, 4.2 L tank and 14-inch tires."
  },
  {
    id: "honda-genio",
    alsoKnownAs: ["Honda Genio 110", "Genio 110"],
    make: "Honda",
    makeSlug: "honda",
    model: "Genio",
    slug: "genio",
    generation: "2019 Philippine generation",
    marketStatus: "previous",
    category: "Commuter scooter",
    srp: 72900,
    engineCc: 110,
    powerHp: 8.85,
    torqueNm: 9.3,
    curbWeightKg: 89,
    seatHeightMm: 740,
    fuelTankL: 4.2,
    groundClearanceMm: 147,
    frontTire: "80/90-14",
    rearTire: "90/90-14",
    abs: "No ABS listed; hydraulic front disc and rear drum",
    colors: ["Blue", "Red"],
    searchVolume: 8100,
    keywordDifficulty: 0,
    sourceLabel: "Top Gear Philippines 2019 Honda Genio buyer-guide price and specification reference",
    sourceUrl: "https://www.topgear.com.ph/index.php/buyers-guide/motorcycles/honda/genio",
    verifiedAt: "2026-10-01",
    freshness: "verified",
    priceContext: "Historical 2019 Philippine price reference. The Genio is kept as a previous-generation record for used-bike and specification research, not as a current new-bike quote.",
    transmission: "Automatic",
    summary: "Previous Philippine-market 110cc automatic scooter with an 89 kg wet weight, 740 mm seat, 4.2 L tank and 14-inch tires."
  },
  {
    id: "yamaha-aerox-v1",
    alsoKnownAs: ["Yamaha Mio Aerox 155", "Aerox V1", "Mio Aerox V1"],
    make: "Yamaha",
    makeSlug: "yamaha",
    model: "Aerox V1",
    slug: "aerox-v1",
    generation: "2017–2020 generation",
    marketStatus: "previous",
    category: "Sport scooter",
    srp: 99800,
    engineCc: 155.1,
    powerHp: 14.9,
    torqueNm: 13.8,
    curbWeightKg: 116,
    seatHeightMm: 790,
    fuelTankL: 4.6,
    groundClearanceMm: 142,
    frontTire: "110/80-14",
    rearTire: "140/70-14",
    abs: "No ABS on the original Philippine launch specification",
    colors: ["Race Blu", "Vibrant Orange", "Raven Black"],
    searchVolume: 7800,
    keywordDifficulty: 0,
    sourceLabel: "THM Motorcycles Philippines archived Mio Aerox 155 specification reference",
    sourceUrl: "https://www.thmmotorcycles.com.ph/viewdetails.php?action=0&id=429&pageNum=11&param=0",
    verifiedAt: "2026-10-01",
    freshness: "verified",
    priceContext: "Historical ₱99,800 Philippine launch SRP from Yamaha's 2017 Aerox 155 launch coverage. This is not a current new-bike or used-bike quote.",
    transmission: "Automatic",
    successorId: "yamaha-aerox-v2",
    summary: "First Philippine Mio Aerox 155 generation, commonly searched as Aerox V1, with a 790 mm seat, 116 kg curb weight, 4.6 L tank and wide 14-inch tires."
  },
  {
    id: "honda-dio",
    alsoKnownAs: ["Honda Dio 110", "Dio 110"],
    make: "Honda",
    makeSlug: "honda",
    model: "Dio",
    slug: "dio",
    generation: "2021 Philippine generation",
    marketStatus: "previous",
    category: "Commuter scooter",
    srp: 49900,
    engineCc: 109,
    powerHp: 7.89,
    torqueNm: 8.91,
    curbWeightKg: 104,
    seatHeightMm: 765,
    fuelTankL: 5.3,
    fuelConsumptionKmL: 58.3,
    groundClearanceMm: 158,
    frontTire: "90/100-10",
    rearTire: "90/100-10",
    abs: "No ABS; front and rear mechanical drum brakes",
    colors: ["Candy Jazzy Blue", "Sports Red", "Vibrant Orange"],
    searchVolume: 6900,
    keywordDifficulty: 0,
    sourceLabel: "Top Gear Philippines 2021 Honda Dio Philippine launch price and specification reference",
    sourceUrl: "https://www.topgear.com.ph/moto-sapiens/motorcycle-news/honda-dio-ph-launch-a3603-20210508",
    verifiedAt: "2026-10-01",
    freshness: "verified",
    priceContext: "Historical ₱49,900 Philippine launch price from May 2021. The Dio is kept as a previous-generation record and this figure should not be treated as a current new-bike quote.",
    transmission: "Automatic",
    summary: "Previous Philippine-market 109cc automatic scooter with 10-inch tubeless tires, a 765 mm seat, 104 kg curb weight and a published 58.3 km/L constant-speed figure."
  },
  {
    id: "yamaha-nmax-v1",
    alsoKnownAs: ["Yamaha NMAX 155 V1", "NMAX V1", "NMAX 155 V1"],
    make: "Yamaha",
    makeSlug: "yamaha",
    model: "NMAX V1",
    slug: "nmax-v1",
    generation: "2015–2019 generation",
    marketStatus: "previous",
    category: "Premium scooter",
    srp: 109000,
    engineCc: 155,
    powerHp: 14.8,
    torqueNm: 14.4,
    curbWeightKg: 127,
    seatHeightMm: 765,
    fuelTankL: 6.6,
    groundClearanceMm: 135,
    frontTire: "110/70-13",
    rearTire: "130/70-13",
    abs: "Variant-dependent; ABS variant listed at ₱119,000 in the 2019 Philippine reference",
    colors: ["Blue", "Midnight Black", "Gunmetal Gray"],
    searchVolume: 5900,
    keywordDifficulty: 0,
    sourceLabel: "Top Gear Philippines 2019 Yamaha NMAX price and specification reference",
    sourceUrl: "https://www.topgear.com.ph/index.php/buyers-guide/motorcycles/yamaha/nmax",
    verifiedAt: "2026-10-01",
    freshness: "verified",
    priceContext: "Historical 2019 Philippine reference: ₱109,000 Standard and ₱119,000 ABS. Use current used listings for today's value rather than these old new-bike prices.",
    transmission: "Automatic",
    successorId: "yamaha-nmax-v2",
    summary: "First-generation Philippine NMAX 155, commonly searched as NMAX V1, with a 765 mm seat, 127 kg wet weight, 6.6 L tank and optional ABS."
  }
];
