import type { SellerProfile, SellerType } from "./types";
import { sellerOffers } from "./offers";

const VERIFIED_ON = "2026-09-09";
const YAMAHA_METRO_MANILA = "https://find-dealer.yamaha-motor.com.ph/location/metro-manila";
const YAMAHA_MANILA_CITY = "https://find-dealer.yamaha-motor.com.ph/location/metro-manila/manila-city";
const YAMAHA_MANILA = "https://find-dealer.yamaha-motor.com.ph/location/metro-manila/manila";
const YAMAHA_SAN_FERNANDO = "https://find-dealer.yamaha-motor.com.ph/location/pampanga/san-fernando";
const YAMAHA_SAN_FERNANDO_CITY = "https://find-dealer.yamaha-motor.com.ph/location/pampanga/san-fernando-city";
const HONDA_DESMARK_SAN_FERNANDO = "https://desmark.com.ph/desmark-store-locator/";
const SUZUKI_MOTORCYCLECITY_SAN_FERNANDO = "https://mc.suzuki.com.ph/store-locations/suzuki-san-fernando-motorcyclecity-3s-shop/";
const KAWASAKI_DEALERS = "https://kawasaki.ph/dealers/motorcycle";

const verifiedDealers: SellerProfile[] = [
  { id:"seller-yamaha-motortrade-malate", name:"Yamaha 3S Shop - Motortrade Malate", slug:"yamaha-motortrade-malate", type:"dealer", city:"Manila", province:"Metro Manila", region:"National Capital Region", addressLabel:"No. 976 Quirino Avenue, Modesto Street, Malate, Manila 1007", website:YAMAHA_METRO_MANILA, phoneLabel:"+63 999 991 7219", description:"Yamaha 3S Shop operated by Motortrade in Malate, Manila. This branch is listed on Yamaha Motor Philippines' official dealer locator.", brands:["Yamaha"], categories:["Motorcycles","Parts and service"], isDemo:false, status:"verified", lastChecked:VERIFIED_ON, sourceLabel:"Yamaha Motor Philippines dealer locator", sourceUrl:YAMAHA_METRO_MANILA, verificationNote:"Branch name, address and phone were checked against Yamaha Motor Philippines' official dealer locator." },
  { id:"seller-yamaha-wheeltek-sampaloc", name:"Yamaha 3S Shop - Wheeltek Sampaloc", slug:"yamaha-wheeltek-sampaloc", type:"dealer", city:"Manila", province:"Metro Manila", region:"National Capital Region", addressLabel:"No. 1508 Didache Building, Valencia Street, España Boulevard, Sampaloc, Manila 1008", website:YAMAHA_METRO_MANILA, phoneLabel:"+63 931 140 3987", description:"Yamaha 3S Shop operated by Wheeltek in Sampaloc, Manila. This branch is listed on Yamaha Motor Philippines' official dealer locator.", brands:["Yamaha"], categories:["Motorcycles","Parts and service"], isDemo:false, status:"verified", lastChecked:VERIFIED_ON, sourceLabel:"Yamaha Motor Philippines dealer locator", sourceUrl:YAMAHA_METRO_MANILA, verificationNote:"Branch name, address and phone were checked against Yamaha Motor Philippines' official dealer locator." },
  { id:"seller-yamaha-transcycle-santa-ana", name:"Yamaha 3S Shop - Transcycle Santa Ana", slug:"yamaha-transcycle-santa-ana", type:"dealer", city:"Manila", province:"Metro Manila", region:"National Capital Region", addressLabel:"Ground Floor, New Panaderos Ext., Kalentong, Santa Ana, Manila 1009", website:YAMAHA_MANILA_CITY, phoneLabel:"+63 906 742 3410", description:"Yamaha 3S Shop operated by Transcycle in Santa Ana, Manila. This branch is listed on Yamaha Motor Philippines' official dealer locator.", brands:["Yamaha"], categories:["Motorcycles","Parts and service"], isDemo:false, status:"verified", lastChecked:VERIFIED_ON, sourceLabel:"Yamaha Motor Philippines dealer locator", sourceUrl:YAMAHA_MANILA_CITY, verificationNote:"Branch name, address and phone were checked against Yamaha Motor Philippines' official dealer locator." },
  { id:"seller-yamaha-megavia-nagtahan", name:"Yamaha 3S Shop - Megavia Nagtahan", slug:"yamaha-megavia-nagtahan", type:"dealer", city:"Manila", province:"Metro Manila", region:"National Capital Region", addressLabel:"No. 2000 Pandacan, corner Pres. Quirino and Jesus St., Nagtahan, Manila 1011", website:YAMAHA_MANILA_CITY, phoneLabel:"+63 998 841 2964", description:"Yamaha 3S Shop operated by Megavia Motor Co. in Nagtahan, Manila. This branch is listed on Yamaha Motor Philippines' official dealer locator.", brands:["Yamaha"], categories:["Motorcycles","Parts and service"], isDemo:false, status:"verified", lastChecked:VERIFIED_ON, sourceLabel:"Yamaha Motor Philippines dealer locator", sourceUrl:YAMAHA_MANILA_CITY, verificationNote:"Branch name, address and phone were checked against Yamaha Motor Philippines' official dealer locator." },
  { id:"seller-yamaha-megavia-tondo", name:"Yamaha 3S Shop - Megavia Tondo", slug:"yamaha-megavia-tondo", type:"dealer", city:"Manila", province:"Metro Manila", region:"National Capital Region", addressLabel:"No. 674 Padre Herrera St., Tondo, Manila 1012", website:YAMAHA_MANILA, phoneLabel:"+63 936 055 7857", description:"Yamaha 3S Shop operated by Megavia Motor Co. in Tondo, Manila. This branch is listed on Yamaha Motor Philippines' official dealer locator.", brands:["Yamaha"], categories:["Motorcycles","Parts and service"], isDemo:false, status:"verified", lastChecked:VERIFIED_ON, sourceLabel:"Yamaha Motor Philippines dealer locator", sourceUrl:YAMAHA_MANILA, verificationNote:"Branch name, address and phone were checked against Yamaha Motor Philippines' official dealer locator." },
  { id:"seller-yamaha-motortrade-tondo", name:"Yamaha 3S Shop - Motortrade Tondo", slug:"yamaha-motortrade-tondo", type:"dealer", city:"Manila", province:"Metro Manila", region:"National Capital Region", addressLabel:"No. 2886 Hermosa Street, Juan Luna, Tondo, Manila 1013", website:YAMAHA_METRO_MANILA, phoneLabel:"+63 999 992 1321", description:"Yamaha 3S Shop operated by Motortrade in Tondo, Manila. This branch is listed on Yamaha Motor Philippines' official dealer locator.", brands:["Yamaha"], categories:["Motorcycles","Parts and service"], isDemo:false, status:"verified", lastChecked:VERIFIED_ON, sourceLabel:"Yamaha Motor Philippines dealer locator", sourceUrl:YAMAHA_METRO_MANILA, verificationNote:"Branch name, address and phone were checked against Yamaha Motor Philippines' official dealer locator." },
  { id:"seller-yamaha-motortrade-tayuman", name:"Yamaha 3S Shop - Motortrade Tayuman", slug:"yamaha-motortrade-tayuman", type:"dealer", city:"Manila", province:"Metro Manila", region:"National Capital Region", addressLabel:"No. 1497 Tayuman Street, Sta. Cruz, Manila 1014", website:YAMAHA_MANILA_CITY, phoneLabel:"+63 999 992 3683", description:"Yamaha 3S Shop operated by Motortrade in Sta. Cruz, Manila. This branch is listed on Yamaha Motor Philippines' official dealer locator.", brands:["Yamaha"], categories:["Motorcycles","Parts and service"], isDemo:false, status:"verified", lastChecked:VERIFIED_ON, sourceLabel:"Yamaha Motor Philippines dealer locator", sourceUrl:YAMAHA_MANILA_CITY, verificationNote:"Branch name, address and phone were checked against Yamaha Motor Philippines' official dealer locator." },
  { id:"seller-yamaha-megavia-san-fernando", name:"Yamaha 3S Shop - Megavia San Fernando", slug:"yamaha-megavia-san-fernando", type:"dealer", city:"San Fernando", province:"Pampanga", region:"Central Luzon", addressLabel:"Ground Floor, Brgy. Dolores, MacArthur Highway, San Fernando City, Pampanga 2000", website:YAMAHA_SAN_FERNANDO_CITY, phoneLabel:"+63 921 894 7098", description:"Yamaha 3S Shop operated by Megavia Motor Co. in San Fernando, Pampanga. This branch is listed on Yamaha Motor Philippines' official dealer locator.", brands:["Yamaha"], categories:["Motorcycles","Parts and service"], isDemo:false, status:"verified", lastChecked:VERIFIED_ON, sourceLabel:"Yamaha Motor Philippines dealer locator", sourceUrl:YAMAHA_SAN_FERNANDO_CITY, verificationNote:"Branch name, address and phone were checked against Yamaha Motor Philippines' official dealer locator." },
  { id:"seller-yamaha-uemi-san-fernando", name:"Yamaha 3S Shop - UEMI San Fernando", slug:"yamaha-uemi-san-fernando", type:"dealer", city:"San Fernando", province:"Pampanga", region:"Central Luzon", addressLabel:"Ground Floor, MacArthur Highway, Brgy. Sindalan, San Fernando, Pampanga 2000", website:YAMAHA_SAN_FERNANDO, phoneLabel:"+63 917 508 1834", description:"Yamaha 3S Shop operated by United Excelsior Marketing in San Fernando, Pampanga. This branch is listed on Yamaha Motor Philippines' official dealer locator.", brands:["Yamaha"], categories:["Motorcycles","Parts and service"], isDemo:false, status:"verified", lastChecked:VERIFIED_ON, sourceLabel:"Yamaha Motor Philippines dealer locator", sourceUrl:YAMAHA_SAN_FERNANDO, verificationNote:"Branch name, address and phone were checked against Yamaha Motor Philippines' official dealer locator." },
  { id:"seller-desmark-honda-san-fernando-pampanga", name:"Desmark Honda 3S - San Fernando Pampanga", slug:"desmark-honda-san-fernando-pampanga", type:"dealer", city:"San Fernando", province:"Pampanga", region:"Central Luzon", addressLabel:"Lot 2 Block 7, Brgy. Juliana, San Fernando, Pampanga 2000", website:HONDA_DESMARK_SAN_FERNANDO, phoneLabel:"+63 968 861 2652", description:"Honda 3S branch operated by Desmark in San Fernando, Pampanga. Desmark's current branch locator lists the store, address and contact number.", brands:["Honda"], categories:["Motorcycles","Parts and service"], isDemo:false, status:"verified", lastChecked:VERIFIED_ON, sourceLabel:"Desmark official store locator", sourceUrl:HONDA_DESMARK_SAN_FERNANDO, verificationNote:"Branch name, Honda 3S status, address and contact number were checked against Desmark's official store locator." },
  { id:"seller-suzuki-motorcyclecity-san-fernando", name:"Suzuki San Fernando - MotorcycleCity 3S Shop", slug:"suzuki-motorcyclecity-san-fernando", type:"dealer", city:"San Fernando", province:"Pampanga", region:"Central Luzon", addressLabel:"General Hizon Avenue, San Fernando, Pampanga", website:SUZUKI_MOTORCYCLECITY_SAN_FERNANDO, phoneLabel:"+63 45 981 4959", description:"Suzuki MotorcycleCity 3S Shop in San Fernando, Pampanga. Suzuki Motorcycles Philippines publishes an official branch page for this store.", brands:["Suzuki"], categories:["Motorcycles","Parts and service"], isDemo:false, status:"verified", lastChecked:VERIFIED_ON, sourceLabel:"Suzuki Motorcycles Philippines branch page", sourceUrl:SUZUKI_MOTORCYCLECITY_SAN_FERNANDO, verificationNote:"The branch relationship was checked on Suzuki Motorcycles Philippines; the displayed address and phone were cross-checked against a current business listing because the official branch page omits those details." },
  { id:"seller-premiumbikes-san-fernando-pampanga", name:"Premiumbikes San Fernando Pampanga", slug:"premiumbikes-san-fernando-pampanga", type:"dealer", city:"San Fernando", province:"Pampanga", region:"Central Luzon", addressLabel:"Unit 1, Apt. J&G, Gopiao Building, 86 Dolores, San Fernando, Pampanga 2000", website:KAWASAKI_DEALERS, phoneLabel:"+63 998 840 4613", description:"Premiumbikes branch in San Fernando, Pampanga. Kawasaki Philippines includes Premiumbikes - San Fernando, Pampanga in its motorcycle dealer directory.", brands:["Kawasaki"], categories:["Motorcycles","Parts and service"], isDemo:false, status:"verified", lastChecked:VERIFIED_ON, sourceLabel:"Kawasaki Philippines motorcycle dealer directory", sourceUrl:KAWASAKI_DEALERS, verificationNote:"The Kawasaki dealer relationship was checked on Kawasaki Philippines; the displayed address and phone were cross-checked against a current business listing." }
];

const demoSellers: SellerProfile[] = [
  { id:"seller-demo-yamaha-a", name:"Demo Yamaha Dealer A", slug:"demo-yamaha-dealer-a", type:"dealer", city:"Quezon City", region:"Metro Manila", addressLabel:"Demo location - Quezon City", description:"Demo Yamaha dealer in Quezon City for testing seller pages and motorcycle offers.", brands:["Yamaha"], categories:["Motorcycles","Financing"], isDemo:true, status:"research" },
  { id:"seller-demo-yamaha-b", name:"Demo Yamaha Dealer B", slug:"demo-yamaha-dealer-b", type:"dealer", city:"Makati", region:"Metro Manila", addressLabel:"Demo location - Makati", description:"Demo Yamaha dealer in Makati for testing model offers and financing listings.", brands:["Yamaha"], categories:["Motorcycles","Financing"], isDemo:true, status:"research" },
  { id:"seller-demo-honda-a", name:"Demo Honda Dealer A", slug:"demo-honda-dealer-a", type:"dealer", city:"Cebu City", region:"Central Visayas", addressLabel:"Demo location - Cebu City", description:"Demo Honda dealer in Cebu City for testing local seller and quote pages.", brands:["Honda"], categories:["Motorcycles","Financing"], isDemo:true, status:"research" },
  { id:"seller-demo-multibrand", name:"Demo Multi-brand Dealer", slug:"demo-multibrand-dealer", type:"dealer", city:"Pasig", region:"Metro Manila", addressLabel:"Demo location - Pasig", description:"Demo multi-brand dealer in Pasig for testing motorcycle price comparisons.", brands:["Yamaha","Honda","Suzuki","Kawasaki"], categories:["Motorcycles","Financing"], isDemo:true, status:"research" },
  { id:"seller-demo-gear", name:"Demo Gear Retailer", slug:"demo-gear-retailer", type:"retailer", city:"Taguig", region:"Metro Manila", addressLabel:"Demo location - Taguig", description:"Demo riding-gear shop in Taguig for testing helmet and gear offers.", brands:["Shoei","HJC","KYT","Spyder"], categories:["Helmets","Riding gear"], isDemo:true, status:"research" },
  { id:"seller-demo-helmet-shop", name:"Demo Helmet Shop", slug:"demo-helmet-shop", type:"retailer", city:"Manila", region:"Metro Manila", addressLabel:"Demo location - Manila", description:"Demo helmet shop in Manila for testing brand and model price comparisons.", brands:["HJC","KYT","EVO","Spyder"], categories:["Helmets"], isDemo:true, status:"research" },
  { id:"seller-demo-tires", name:"Demo Tire Retailer", slug:"demo-tire-retailer", type:"retailer", city:"Mandaluyong", region:"Metro Manila", addressLabel:"Demo location - Mandaluyong", description:"Demo motorcycle tire retailer in Mandaluyong for testing size-specific prices.", brands:["Michelin","Pirelli","Dunlop"], categories:["Tires"], isDemo:true, status:"research" },
  { id:"seller-demo-tire-shop", name:"Demo Tire Shop", slug:"demo-tire-shop", type:"retailer", city:"Caloocan", region:"Metro Manila", addressLabel:"Demo location - Caloocan", description:"Demo tire shop in Caloocan for testing local tire prices and replacement searches.", brands:["Pirelli","Michelin","IRC"], categories:["Tires"], isDemo:true, status:"research" },
  { id:"seller-demo-accessories", name:"Demo Accessories Shop", slug:"demo-accessories-shop", type:"retailer", city:"Davao City", region:"Davao Region", addressLabel:"Demo location - Davao City", description:"Demo accessory shop in Davao City for testing top-box, rack and bracket offers.", brands:["GIVI","SHAD"], categories:["Top boxes","Accessories"], isDemo:true, status:"research" }
];

export const sellers: SellerProfile[] = [...verifiedDealers, ...demoSellers];
export const MIN_PUBLIC_DEALERS_PER_CITY = 3;
export function isPublicSeller(seller: SellerProfile){ return !seller.isDemo && seller.status === "verified" && Boolean(seller.sourceUrl && seller.lastChecked); }
export function publicSellers(){ return sellers.filter(isPublicSeller); }
export function getSeller(slug:string){ return sellers.find(s=>s.slug===slug); }
export function getPublicSeller(slug:string){ const seller=getSeller(slug); return seller && isPublicSeller(seller) ? seller : undefined; }
export function sellersByType(type:SellerType){ return sellers.filter(s=>s.type===type); }
export function publicSellersByType(type:SellerType){ return sellers.filter(s=>s.type===type && isPublicSeller(s)); }
export function dealerCities(){ return [...new Set(sellers.filter(s=>s.type==="dealer").map(s=>s.city))].sort(); }
export function publicDealerCities(){ return [...new Set(publicSellersByType("dealer").map(s=>s.city))].sort(); }
export function citySlug(city:string){ return city.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,""); }
export function dealersByCity(slug:string){ return sellers.filter(s=>s.type==="dealer" && citySlug(s.city)===slug); }
export function publicDealersByCity(slug:string){ return dealersByCity(slug).filter(isPublicSeller); }
export function publicDealerBrands(){ return [...new Set(publicSellersByType("dealer").flatMap(s=>s.brands))].sort(); }
export function offersForSeller(slug:string){ return sellerOffers.filter(o=>o.sellerSlug===slug && o.status!=="expired"); }
export function sellerCounts(){ return { total:sellers.length, dealers:sellers.filter(s=>s.type==="dealer").length, retailers:sellers.filter(s=>s.type==="retailer").length, cities:new Set(sellers.map(s=>s.city)).size }; }
