import type { TopBoxFitment } from "./types";

// Manufacturer fitment records checked through 2026-09-23. These edges are deliberately
// product + motorcycle specific; capacity heuristics are not treated as fitment.
export const topBoxFitments: TopBoxFitment[] = [
  {
    id: "sh39-aerox-155",
    topBoxId: "shad-sh39",
    topBoxLabel: "SHAD SH39",
    productHref: "/accessories/top-box/sh39",
    modelId: "yamaha-aerox-v3",
    rackCode: "Y0AE14IST",
    rackLabel: "SHAD Top Master Yamaha Aerox",
    plateRequirement: "Use the plate included with the SH39 on the bike-specific Top Master fitting.",
    modelYears: "Aerox 155: 2021-2026; Aerox Alpha: 2024-2026",
    status: "verified",
    sourceLabel: "SHAD official Yamaha Aerox fitment page",
    sourceUrl: "https://www.shad.es/tl/fitting-kits-for-cases-bags-and-moto-backrests/yamaha/top-master-yamaha-aerox/",
    lastChecked: "2026-08-25"
  },
  {
    id: "sh39-adv160",
    topBoxId: "shad-sh39",
    topBoxLabel: "SHAD SH39",
    productHref: "/accessories/top-box/sh39",
    modelId: "honda-adv-160",
    rackCode: "H0XD12IST",
    rackLabel: "SHAD Top Master Honda ADV 160",
    plateRequirement: "Use the plate included with the SH39 on the bike-specific Top Master fitting.",
    modelYears: "2022-2026",
    status: "verified",
    sourceLabel: "SHAD official Honda ADV 160 fitment page",
    sourceUrl: "https://www.shad.es/tl/fitting-kits-for-cases-bags-and-moto-backrests/honda/top-master-honda-adv-160/",
    lastChecked: "2026-08-25"
  },
  {
    id: "sh39-click160",
    topBoxId: "shad-sh39",
    topBoxLabel: "SHAD SH39",
    productHref: "/accessories/top-box/sh39",
    modelId: "honda-click-160",
    rackCode: "H0VR15IST",
    rackLabel: "SHAD top-case fitting kit Honda Click 125/150/160",
    plateRequirement: "Use the plate included with the SH39 on the bike-specific fitting kit.",
    modelYears: "Click/Vario 160: 2022-2026",
    marketNote: "SHAD catalogs the same platform as Click/Vario 160 by market; confirm the local model-year before ordering.",
    status: "verified",
    sourceLabel: "SHAD official Honda fitment catalog",
    sourceUrl: "https://www.shad.es/tl/for-your-motorbike/HONDA/",
    lastChecked: "2026-08-25"
  },
  {
    id: "sh39-pcx160",
    topBoxId: "shad-sh39",
    topBoxLabel: "SHAD SH39",
    productHref: "/accessories/top-box/sh39",
    modelId: "honda-pcx-160",
    rackCode: "H0IPC11ST",
    rackLabel: "SHAD Top Master Honda PCX",
    plateRequirement: "Use the plate included with the SH39 on the bike-specific Top Master fitting.",
    modelYears: "PCX: 2010-2026",
    marketNote: "SHAD lists the PCX family rather than a Philippines-specific PCX 160 trim; verify the exact year before ordering.",
    status: "verified",
    sourceLabel: "SHAD official Honda PCX fitment page",
    sourceUrl: "https://www.shad.es/en-id/fitting-kits-for-cases-bags-and-moto-backrests/honda-fitting-kits-for-cases-bags-and-moto-backrests/top-master-honda-pcx/",
    lastChecked: "2026-08-25"
  },
  {
    id: "sh39-fazzio",
    topBoxId: "shad-sh39",
    topBoxLabel: "SHAD SH39",
    productHref: "/accessories/top-box/sh39",
    modelId: "yamaha-fazzio",
    rackCode: "Y0IFZ11ST",
    rackLabel: "SHAD Top Master Yamaha Fazzio",
    plateRequirement: "Use the plate included with the SH39 on the Y0IFZ11ST Top Master fitting. SHAD states this fitting is not compatible with the big or aluminium mounting plates.",
    modelYears: "2022-2026",
    status: "verified",
    sourceLabel: "SHAD official Yamaha Fazzio fitment page",
    sourceUrl: "https://www.shad.es/en-id/fitting-kits-for-cases-bags-and-moto-backrests/yamaha-fitting-kits-for-cases-bags-and-moto-backrests/top-master-yamaha-fazzio/",
    lastChecked: "2026-09-23"
  },
  {
    id: "sh33-beat",
    topBoxId: "shad-sh33",
    topBoxLabel: "SHAD SH33",
    productHref: "/accessories/top-box/sh33",
    modelId: "honda-beat",
    rackCode: "H0IBT11ST",
    rackLabel: "SHAD Top Master Honda BeAT / Scoopy / Genio",
    plateRequirement: "Use the SH33 small mounting plate D1B29PAR on the H0IBT11ST fitting. SHAD limits this fitting to the small base plate and top cases up to SH34.",
    modelYears: "BeAT family: 2008-2026",
    marketNote: "SHAD groups BeAT, Scoopy and Genio on this fitting. Confirm the exact Philippine BeAT generation and mounting points before ordering.",
    status: "verified",
    sourceLabel: "SHAD official Honda BeAT / Scoopy / Genio fitment page",
    sourceUrl: "https://www.shad.es/en-id/fitting-kits-for-cases-bags-and-moto-backrests/honda-fitting-kits-for-cases-bags-and-moto-backrests/top-master-honda-beat-scoopy-genio/",
    lastChecked: "2026-09-23"
  },
  {
    id: "sh39-mio-gear",
    topBoxId: "shad-sh39",
    topBoxLabel: "SHAD SH39",
    productHref: "/accessories/top-box/sh39",
    modelId: "yamaha-mio-gear",
    rackCode: "Y0MZ16ST",
    rackLabel: "SHAD Top Master Yamaha Mio M3 125 / Gear 125",
    plateRequirement: "Use the plate included with the SH39 on the Y0MZ16ST Top Master fitting.",
    modelYears: "Gear: 2020-2025",
    marketNote: "SHAD currently lists Gear fitment through 2025. Reconfirm the rack before ordering for a later Philippine model year.",
    status: "verified",
    sourceLabel: "SHAD official Yamaha Mio M3 125 / Gear 125 fitment page",
    sourceUrl: "https://www.shad.es/tl/fitting-kits-for-cases-bags-and-moto-backrests/yamaha/top-master-yamaha-mio-m3-125-gear-125/",
    lastChecked: "2026-09-23"
  },
  {
    id: "sh39-mio-i125",
    topBoxId: "shad-sh39",
    topBoxLabel: "SHAD SH39",
    productHref: "/accessories/top-box/sh39",
    modelId: "yamaha-mio-i-125",
    rackCode: "Y0MZ16ST",
    rackLabel: "SHAD Top Master Yamaha Mio i125 / Gear 125",
    plateRequirement: "Use the plate included with the SH39 on the Y0MZ16ST Top Master fitting.",
    modelYears: "Mio i125: 2014-2025",
    marketNote: "SHAD currently lists Mio i125 fitment through 2025. Reconfirm the rack before ordering for a later Philippine model year.",
    status: "verified",
    sourceLabel: "SHAD official Yamaha Mio i125 / Gear 125 fitment page",
    sourceUrl: "https://www.shad.es/tl/fitting-kits-for-cases-bags-and-moto-backrests/yamaha/top-master-yamaha-mio-m3-125-gear-125/",
    lastChecked: "2026-09-23"
  },
  {
    id: "sh39-burgman-street",
    topBoxId: "shad-sh39",
    topBoxLabel: "SHAD SH39",
    productHref: "/accessories/top-box/sh39",
    modelId: "suzuki-burgman-street",
    rackCode: "S0BR14ST",
    rackLabel: "SHAD Top Case Fitting Kit Suzuki Burgman Street 125",
    plateRequirement: "Use the plate included with the SH39. SHAD states S0BR14ST is not compatible with the big or aluminium mounting plates.",
    modelYears: "2024-2026",
    status: "verified",
    sourceLabel: "SHAD official Suzuki Burgman Street 125 fitment page",
    sourceUrl: "https://www.shad.es/en/bags-and-moto-backrests/suzuki-bags-and-moto-backrests/top-case-fitting-kit-suzuki-burgman-street-125/",
    lastChecked: "2026-09-23"
  },
  {
    id: "sh39-avenis",
    topBoxId: "shad-sh39",
    topBoxLabel: "SHAD SH39",
    productHref: "/accessories/top-box/sh39",
    modelId: "suzuki-avenis",
    rackCode: "S0AV13IST",
    rackLabel: "SHAD Top Case Fitting Kit Suzuki Avenis 125",
    plateRequirement: "Use the plate included with the SH39 on the S0AV13IST fitting.",
    modelYears: "2023-2026",
    status: "verified",
    sourceLabel: "SHAD official Suzuki Avenis 125 fitment page",
    sourceUrl: "https://www.shad.es/en/bags-and-moto-backrests/suzuki-bags-and-moto-backrests/top-case-fitting-kit-suzuki-avenis-125/",
    lastChecked: "2026-09-23"
  },
  {
    id: "sh39-click125",
    topBoxId: "shad-sh39",
    topBoxLabel: "SHAD SH39",
    productHref: "/accessories/top-box/sh39",
    modelId: "honda-click-125i",
    rackCode: "H0VR15IST",
    rackLabel: "SHAD Top Case Fitting Kit Honda Click / Vario 125",
    plateRequirement: "Use the plate included with the SH39. SHAD states H0VR15IST is not compatible with the big or aluminium mounting plates.",
    modelYears: "Click/Vario 125: 2015-2026",
    marketNote: "SHAD catalogs this scooter family as Vario 125 in some markets. Confirm the exact Philippine Click125 generation and mounting points before ordering.",
    status: "verified",
    sourceLabel: "SHAD official Honda Click 125/150/160 fitment page",
    sourceUrl: "https://www.shad.es/en-id/fitting-kits-for-cases-bags-and-moto-backrests/honda-fitting-kits-for-cases-bags-and-moto-backrests/top-case-fitting-kit-honda-click-125-150-160/",
    lastChecked: "2026-09-23"
  },
  {
    id: "sh39-burgman-400",
    topBoxId: "shad-sh39",
    topBoxLabel: "SHAD SH39",
    productHref: "/accessories/top-box/sh39",
    modelId: "suzuki-burgman-400",
    rackCode: "S0BR47ST",
    rackLabel: "SHAD Top Case Fitting Kit Suzuki Burgman 400",
    plateRequirement: "Use the plate included with the SH39 on the S0BR47ST fitting.",
    modelYears: "2017-2026",
    status: "verified",
    sourceLabel: "SHAD official Suzuki Burgman 400 fitment page",
    sourceUrl: "https://www.shad.es/en/bags-and-moto-backrests/suzuki-bags-and-moto-backrests/top-case-fitting-kit-suzuki-burgman-400-2/",
    lastChecked: "2026-09-23"
  },
  {
    id: "sh39-cb650r",
    topBoxId: "shad-sh39",
    topBoxLabel: "SHAD SH39",
    productHref: "/accessories/top-box/sh39",
    modelId: "honda-cb650r",
    rackCode: "H0CR64ST",
    rackLabel: "SHAD Top Case Fitting Kit Honda CB650R / CBR650R",
    plateRequirement: "Use the plate included with the SH39 on the H0CR64ST fitting.",
    modelYears: "CB650R: 2024-2026",
    status: "verified",
    sourceLabel: "SHAD official Honda CB650R / CBR650R fitment page",
    sourceUrl: "https://www.shad.es/en/bags-and-moto-backrests/honda-bags-and-moto-backrests/top-case-fitting-kit-honda-cb650r-cbr650r/",
    lastChecked: "2026-09-23"
  },
  {
    id: "sh39-nx500",
    topBoxId: "shad-sh39",
    topBoxLabel: "SHAD SH39",
    productHref: "/accessories/top-box/sh39",
    modelId: "honda-nx500-e-clutch",
    rackCode: "H0CX55ST",
    rackLabel: "SHAD Top Case Fitting Kit Honda CB500X / NX500",
    plateRequirement: "Use the plate included with the SH39 on the H0CX55ST fitting.",
    modelYears: "NX500: 2023-2026",
    marketNote: "The SHAD fitment is model-family specific. Confirm the Philippine E-Clutch model year and any OEM rear-carrier configuration before ordering.",
    status: "verified",
    sourceLabel: "SHAD official Honda NX500 fitment catalog",
    sourceUrl: "https://www.shad.es/en/equipment/HONDA/NX-500/",
    lastChecked: "2026-09-23"
  },
  {
    id: "sh39-adv350",
    topBoxId: "shad-sh39",
    topBoxLabel: "SHAD SH39",
    productHref: "/accessories/top-box/sh39",
    modelId: "honda-adv-350",
    rackCode: "H0FR15IST",
    rackLabel: "SHAD Top Case Fitting Kit Honda Forza 125 / ADV350",
    plateRequirement: "Use the plate included with the SH39 on the H0FR15IST fitting.",
    modelYears: "ADV350: 2025-2026",
    status: "verified",
    sourceLabel: "SHAD official Philippines-market Honda ADV350 fitment catalog",
    sourceUrl: "https://www.shad.es/tl/for-your-motorbike/types/Maleta-superior-%28ST%29/HONDA/ADV-350/",
    lastChecked: "2026-09-23"
  },
  {
    id: "sh39-tmax-tech-max",
    topBoxId: "shad-sh39",
    topBoxLabel: "SHAD SH39",
    productHref: "/accessories/top-box/sh39",
    modelId: "yamaha-tmax",
    rackCode: "Y0TX52ST",
    rackLabel: "SHAD Top Case Fitting Kit Yamaha TMAX 560 Tech Max",
    plateRequirement: "Use the plate included with the SH39 on the Y0TX52ST fitting.",
    modelYears: "TMAX 560 Tech Max: 2022-2026",
    status: "verified",
    sourceLabel: "SHAD official Yamaha TMAX 560 Tech Max fitment page",
    sourceUrl: "https://www.shad.es/en/bags-and-moto-backrests/yamaha-bags-and-moto-backrests/top-case-fitting-kit-yamaha-tmax-560-tech-max/",
    lastChecked: "2026-09-23"
  },
  {
    id: "sh39-mio-gravis",
    topBoxId: "shad-sh39",
    topBoxLabel: "SHAD SH39",
    productHref: "/accessories/top-box/sh39",
    modelId: "yamaha-mio-gravis",
    rackCode: "Y0FG13IST",
    rackLabel: "SHAD Top Master Yamaha Mio Gravis",
    plateRequirement: "Use the plate included with the SH39 on the Y0FG13IST fitting. SHAD states this fitting is not compatible with the aluminium mounting plates.",
    modelYears: "2023-2025",
    marketNote: "The exact SHAD fitting page currently stops at 2025. Reconfirm the rack before ordering for a later Philippine model year.",
    status: "verified",
    sourceLabel: "SHAD official Yamaha Mio Gravis fitment page",
    sourceUrl: "https://www.shad.es/en-id/fitting-kits-for-cases-bags-and-moto-backrests/yamaha-fitting-kits-for-cases-bags-and-moto-backrests/top-master-yamaha-mio-gravis/",
    lastChecked: "2026-09-23"
  },
  {
    id: "sh39-sniper-155",
    topBoxId: "shad-sh39",
    topBoxLabel: "SHAD SH39",
    productHref: "/accessories/top-box/sh39",
    modelId: "yamaha-sniper-155",
    rackCode: "Y0IMX18ST",
    rackLabel: "SHAD Top Master Yamaha Sniper 155 / MX King 150",
    plateRequirement: "Use the plate included with the SH39 on the Y0IMX18ST fitting. SHAD states this fitting is not compatible with the big or aluminium mounting plates.",
    modelYears: "2015-2026",
    marketNote: "SHAD titles the fitting for Yamaha Sniper 155 while its compatibility table uses the regional MX King 150 name. Confirm the exact Philippine model year before ordering.",
    status: "verified",
    sourceLabel: "SHAD official Yamaha Sniper 155 fitment page",
    sourceUrl: "https://www.shad.es/en-id/fitting-kits-for-cases-bags-and-moto-backrests/yamaha-fitting-kits-for-cases-bags-and-moto-backrests/top-master-yamaha-sniper-155/",
    lastChecked: "2026-09-23"
  },
  {
    id: "sh39-xsr155",
    topBoxId: "shad-sh39",
    topBoxLabel: "SHAD SH39",
    productHref: "/accessories/top-box/sh39",
    modelId: "yamaha-xsr155",
    rackCode: "Y0IXS19ST",
    rackLabel: "SHAD Top Case Fitting Kit Yamaha XSR125 / XSR155",
    plateRequirement: "Use the plate included with the SH39 on the Y0IXS19ST fitting.",
    modelYears: "XSR155: 2019-2025",
    marketNote: "The exact SHAD XSR155 fitting table currently stops at 2025. Reconfirm the rack before ordering for a later Philippine model year.",
    status: "verified",
    sourceLabel: "SHAD official Yamaha XSR125 / XSR155 fitment page",
    sourceUrl: "https://www.shad.es/tl/fitting-kits-for-cases-bags-and-moto-backrests/yamaha/top-case-fitting-kit-yamaha-xsr-125-155/",
    lastChecked: "2026-09-23"
  },
  {
    id: "sh39-mt07",
    topBoxId: "shad-sh39",
    topBoxLabel: "SHAD SH39",
    productHref: "/accessories/top-box/sh39",
    modelId: "yamaha-mt-07",
    rackCode: "Y0MT75ST",
    rackLabel: "SHAD Top Case Fitting Kit Yamaha MT-07",
    plateRequirement: "Use the plate included with the SH39 on the Y0MT75ST fitting.",
    modelYears: "2025-2026",
    status: "verified",
    sourceLabel: "SHAD official Yamaha MT-07 fitment catalog",
    sourceUrl: "https://www.shad.es/en/for-your-motorbike/YAMAHA/MT07/",
    lastChecked: "2026-09-23"
  },
  {
    id: "sh39-cb150x",
    topBoxId: "shad-sh39",
    topBoxLabel: "SHAD SH39",
    productHref: "/accessories/top-box/sh39",
    modelId: "honda-cb150x",
    rackCode: "H0ICB16ST",
    rackLabel: "SHAD Top Master Honda CB150X",
    plateRequirement: "Use the plate included with the SH39 on the H0ICB16ST fitting. SHAD states this fitting is not compatible with aluminium mounting plates.",
    modelYears: "2021-2025",
    marketNote: "The exact SHAD CB150X fitting page currently stops at 2025. Reconfirm the rack before ordering for a later Philippine model year.",
    status: "verified",
    sourceLabel: "SHAD official Honda CB150R Streetfire / CB150X fitment page",
    sourceUrl: "https://www.shad.es/en-id/fitting-kits-for-cases-bags-and-moto-backrests/honda-fitting-kits-for-cases-bags-and-moto-backrests/top-master-honda-cb150r-streetfire-cb150x/",
    lastChecked: "2026-09-23"
  },
  {
    id: "sh39-transalp-750",
    topBoxId: "shad-sh39",
    topBoxLabel: "SHAD SH39",
    productHref: "/accessories/top-box/sh39",
    modelId: "honda-xl750-transalp",
    rackCode: "H0TR73ST",
    rackLabel: "SHAD Top Case Fitting Kit Honda XL750 Transalp",
    plateRequirement: "Use the plate included with the SH39 on the H0TR73ST fitting.",
    modelYears: "2023-2026",
    status: "verified",
    sourceLabel: "SHAD official Honda XL750 Transalp fitment page",
    sourceUrl: "https://www.shad.es/en/bags-and-moto-backrests/honda-bags-and-moto-backrests/top-case-fitting-kit-honda-transalp-xl-750/",
    lastChecked: "2026-09-23"
  },
  {
    id: "sh39-africa-twin-1100",
    topBoxId: "shad-sh39",
    topBoxLabel: "SHAD SH39",
    productHref: "/accessories/top-box/sh39",
    modelId: "honda-crf1100l-africa-twin",
    rackCode: "H0DV10ST",
    rackLabel: "SHAD Top Case Fitting Kit Honda Africa Twin CRF1100L",
    plateRequirement: "Use the plate included with the SH39 on the H0DV10ST fitting. SHAD states this fitting is not compatible with the small D1B29PAR plate; cases supplied with that small plate require the medium D1B40PAR instead.",
    modelYears: "CRF1100L Africa Twin: 2022-2026",
    status: "verified",
    sourceLabel: "SHAD official Honda Africa Twin CRF1100L / Adventure Sports fitment page",
    sourceUrl: "https://www.shad.es/en/bags-and-moto-backrests/honda-bags-and-moto-backrests/top-case-fitting-kit-africa-twin-crf-1100l-adventure-sport/",
    lastChecked: "2026-09-23"
  },
  {
    id: "sh39-z500",
    topBoxId: "shad-sh39",
    topBoxLabel: "SHAD SH39",
    productHref: "/accessories/top-box/sh39",
    modelId: "kawasaki-z500",
    rackCode: "K0Z554ST",
    rackLabel: "SHAD Top Case Fitting Kit Kawasaki Z500",
    plateRequirement: "Use the plate included with the SH39 on the K0Z554ST fitting.",
    modelYears: "2024-2025",
    marketNote: "SHAD's broader current catalog also surfaces Z500 for 2026, but the exact fitting detail table currently stops at 2025. Reconfirm the exact rack package before ordering for a 2026 Philippine unit.",
    status: "verified",
    sourceLabel: "SHAD official Kawasaki Z500 fitment page",
    sourceUrl: "https://www.shad.es/tl/fitting-kits-for-cases-bags-and-moto-backrests/kawasaki/top-case-fitting-kit-kawasaki-z500/",
    lastChecked: "2026-09-23"
  },
  {
    id: "sh39-vstrom-250-sx",
    topBoxId: "shad-sh39",
    topBoxLabel: "SHAD SH39",
    productHref: "/accessories/top-box/sh39",
    modelId: "suzuki-v-strom-250-sx",
    rackCode: "S0VS23IST",
    rackLabel: "SHAD Top Master Suzuki V-Strom 250 SX",
    plateRequirement: "Use the plate included with the SH39 on the S0VS23IST fitting.",
    modelYears: "2023-2026",
    status: "verified",
    sourceLabel: "SHAD official Suzuki V-Strom 250 SX fitment page",
    sourceUrl: "https://www.shad.es/en-id/fitting-kits-for-cases-bags-and-moto-backrests/suzuki-fitting-kits-for-cases-bags-and-moto-backrests/top-master-suzuki-v-strom-250-sx/",
    lastChecked: "2026-09-23"
  },
  {
    id: "sh33-burgman-street-ex",
    topBoxId: "shad-sh33",
    topBoxLabel: "SHAD SH33",
    productHref: "/accessories/top-box/sh33",
    modelId: "suzuki-burgman-street-ex",
    rackCode: "S0BR13IST",
    rackLabel: "SHAD Top Master Suzuki Burgman Street 125EX",
    plateRequirement: "Use the SH33 small mounting plate supplied with the case on the S0BR13IST fitting.",
    modelYears: "2023-2025",
    marketNote: "SHAD's broader current catalog also surfaces Burgman Street 125EX for 2026, but the exact fitting detail table currently stops at 2025. Reconfirm the rack before ordering for a 2026 Philippine unit.",
    status: "verified",
    sourceLabel: "SHAD official Suzuki Burgman Street 125EX fitment page",
    sourceUrl: "https://www.shad.es/tl/fitting-kits-for-cases-bags-and-moto-backrests/suzuki/top-master-suzuki-burgman-street-125x/",
    lastChecked: "2026-09-23"
  },
  {
    id: "sh39-nmax-v2",
    topBoxId: "shad-sh39",
    topBoxLabel: "SHAD SH39",
    productHref: "/accessories/top-box/sh39",
    modelId: "yamaha-nmax-v2",
    rackCode: "Y0INM19ST",
    rackLabel: "SHAD Top Master Yamaha NMAX 155",
    plateRequirement: "Use the plate included with the SH39 on the Y0INM19ST fitting. SHAD states the rack is not compatible with aluminium mounting plates.",
    modelYears: "MotoIndex NMAX V2: 2020-2021; SHAD NMAX 155 rack coverage: 2020-2024",
    marketNote: "This edge is intentionally limited to the MotoIndex NMAX V2 historical generation even though SHAD lists the NMAX 155 family through 2024.",
    status: "verified",
    sourceLabel: "SHAD official Yamaha NMAX 155 fitment page",
    sourceUrl: "https://www.shad.es/en-id/fitting-kits-for-cases-bags-and-moto-backrests/yamaha-fitting-kits-for-cases-bags-and-moto-backrests/top-master-yamaha-nmax-155/",
    lastChecked: "2026-09-23"
  },
  {
    id: "sh33-nmax-v2",
    topBoxId: "shad-sh33",
    topBoxLabel: "SHAD SH33",
    productHref: "/accessories/top-box/sh33",
    modelId: "yamaha-nmax-v2",
    rackCode: "Y0INM19ST",
    rackLabel: "SHAD Top Master Yamaha NMAX 155",
    plateRequirement: "Use the SH33 plate supplied with the case on the Y0INM19ST fitting; SHAD lists SH33 as a compatible product and excludes aluminium mounting plates.",
    modelYears: "MotoIndex NMAX V2: 2020-2021; SHAD NMAX 155 rack coverage: 2020-2024",
    marketNote: "This SH33 relationship follows the same historical NMAX V2 boundary as the SH39 edge.",
    status: "verified",
    sourceLabel: "SHAD official Yamaha NMAX 155 fitment page",
    sourceUrl: "https://www.shad.es/en-id/fitting-kits-for-cases-bags-and-moto-backrests/yamaha-fitting-kits-for-cases-bags-and-moto-backrests/top-master-yamaha-nmax-155/",
    lastChecked: "2026-09-23"
  },
  {
    id: "sh39-aerox-v2",
    topBoxId: "shad-sh39",
    topBoxLabel: "SHAD SH39",
    productHref: "/accessories/top-box/sh39",
    modelId: "yamaha-aerox-v2",
    rackCode: "Y0AE14IST",
    rackLabel: "SHAD Top Master Yamaha Aerox",
    plateRequirement: "Use the plate included with the SH39 on the Y0AE14IST fitting.",
    modelYears: "MotoIndex Aerox V2: 2021 generation; SHAD Aerox rack coverage: 2021-2026",
    marketNote: "MotoIndex keeps this edge on the historical Aerox V2 canonical rather than using SHAD's broad Aerox family years as a generation claim.",
    status: "verified",
    sourceLabel: "SHAD official Yamaha Aerox fitment page",
    sourceUrl: "https://www.shad.es/tl/fitting-kits-for-cases-bags-and-moto-backrests/yamaha/top-master-yamaha-aerox/",
    lastChecked: "2026-09-23"
  },
  {
    id: "sh33-aerox-v2",
    topBoxId: "shad-sh33",
    topBoxLabel: "SHAD SH33",
    productHref: "/accessories/top-box/sh33",
    modelId: "yamaha-aerox-v2",
    rackCode: "Y0AE14IST",
    rackLabel: "SHAD Top Master Yamaha Aerox",
    plateRequirement: "Use the SH33 plate supplied with the case on the Y0AE14IST fitting; SHAD lists SH33 as a compatible product for the Aerox rack.",
    modelYears: "MotoIndex Aerox V2: 2021 generation; SHAD Aerox rack coverage: 2021-2026",
    marketNote: "This SH33 relationship is attached only to the MotoIndex V2 historical canonical; it does not redefine later Aerox generations.",
    status: "verified",
    sourceLabel: "SHAD official Yamaha Aerox fitment page",
    sourceUrl: "https://www.shad.es/tl/fitting-kits-for-cases-bags-and-moto-backrests/yamaha/top-master-yamaha-aerox/",
    lastChecked: "2026-09-23"
  },
  {
    id: "sh39-click150i",
    topBoxId: "shad-sh39",
    topBoxLabel: "SHAD SH39",
    productHref: "/accessories/top-box/sh39",
    modelId: "honda-click-150i",
    rackCode: "H0VR15IST",
    rackLabel: "SHAD Top Case Fitting Kit Honda Click / Vario 125/150/160",
    plateRequirement: "Use the plate included with the SH39. SHAD states H0VR15IST is not compatible with the big or aluminium mounting plates.",
    modelYears: "Click150i MotoIndex generation: 2018-2022; SHAD Vario 150 coverage: 2015-2022",
    marketNote: "SHAD catalogs this family as Vario 150 in Indonesia; MotoIndex keeps the Philippine Click150i naming and generation boundary.",
    status: "verified",
    sourceLabel: "SHAD official Honda Click 125/150/160 fitment page",
    sourceUrl: "https://www.shad.es/en-id/fitting-kits-for-cases-bags-and-moto-backrests/honda-fitting-kits-for-cases-bags-and-moto-backrests/top-case-fitting-kit-honda-click-125-150-160/",
    lastChecked: "2026-09-23"
  },
  {
    id: "sh39-xmax",
    topBoxId: "shad-sh39",
    topBoxLabel: "SHAD SH39",
    productHref: "/accessories/top-box/sh39",
    modelId: "yamaha-xmax",
    rackCode: "Y0XM33ST",
    rackLabel: "SHAD Top Case Fitting Kit Yamaha XMAX 125/300 Tech",
    plateRequirement: "Use the plate included with the SH39 on the Y0XM33ST fitting.",
    modelYears: "XMAX 300: 2023-2025",
    marketNote: "MotoIndex's current Philippine XMAX is a 292cc XMAX 300-family model. SHAD's exact non-Tech XMAX 300 Y0XM33ST listing currently stops at 2025, so 2026 units require a rack recheck before ordering.",
    status: "verified",
    sourceLabel: "SHAD official Yamaha XMAX 300 fitment catalog",
    sourceUrl: "https://www.shad.es/en/for-your-motorbike/types/Maleta-superior-%28ST%29/YAMAHA/X--MAX-300/",
    lastChecked: "2026-09-23"
  },
  {
    id: "sh39-gixxer-sf250",
    topBoxId: "shad-sh39",
    topBoxLabel: "SHAD SH39",
    productHref: "/accessories/top-box/sh39",
    modelId: "suzuki-gixxer-sf250",
    rackCode: "S0GX22IST",
    rackLabel: "SHAD Top Master Suzuki Gixxer SF 250",
    plateRequirement: "Use the plate included with the SH39 on the S0GX22IST fitting.",
    modelYears: "2021-2025",
    marketNote: "The current MotoIndex Gixxer SF250 canonical remains current, but SHAD's exact top-master coverage stops at 2025. Reconfirm fitment for a 2026 Philippine unit.",
    status: "verified",
    sourceLabel: "SHAD official Suzuki Gixxer SF 250 fitment page",
    sourceUrl: "https://www.shad.es/en-id/for-your-motorbike/SUZUKI/GIXXER-SF-250/",
    lastChecked: "2026-09-23"
  },
  {
    id: "sh39-lexi155",
    topBoxId: "shad-sh39",
    topBoxLabel: "SHAD SH39",
    productHref: "/accessories/top-box/sh39",
    modelId: "yamaha-lexi-155",
    rackCode: "Y0LX14IST",
    rackLabel: "SHAD Top Master Yamaha Lexi LX 155",
    plateRequirement: "Use the plate included with the SH39 on the Y0LX14IST fitting. SHAD states this fitting is not compatible with aluminium mounting plates.",
    modelYears: "2024-2026",
    marketNote: "SHAD names the regional model Lexi LX 155; MotoIndex keeps the Philippine Lexi 155 name while retaining the exact rack code and years.",
    status: "verified",
    sourceLabel: "SHAD official Yamaha Lexi LX 155 fitment page",
    sourceUrl: "https://www.shad.es/en-id/fitting-kits-for-cases-bags-and-moto-backrests/yamaha-fitting-kits-for-cases-bags-and-moto-backrests/top-master-yamaha-lexi-lx-155/",
    lastChecked: "2026-09-23"
  },
  {
    id: "sh39-klx150",
    topBoxId: "shad-sh39",
    topBoxLabel: "SHAD SH39",
    productHref: "/accessories/top-box/sh39",
    modelId: "kawasaki-klx150",
    rackCode: "K0IKL18ST",
    rackLabel: "SHAD Top Master Kawasaki KLX150",
    plateRequirement: "Use the plate included with the SH39 on the K0IKL18ST fitting. SHAD states this rack is not compatible with the big or aluminium mounting plates.",
    modelYears: "2015-2026",
    status: "verified",
    sourceLabel: "SHAD official Kawasaki KLX150 fitment page",
    sourceUrl: "https://www.shad.es/en-id/fitting-kits-for-cases-bags-and-moto-backrests/kawasaki-fitting-kits-for-cases-bags-and-moto-backrests/top-master-kawasaki-klx-150/",
    lastChecked: "2026-09-23"
  },
  {
    id: "sh39-cb500-hornet",
    topBoxId: "shad-sh39",
    topBoxLabel: "SHAD SH39",
    productHref: "/accessories/top-box/sh39",
    modelId: "honda-cb500-hornet-e-clutch",
    rackCode: "H0CB59ST",
    rackLabel: "SHAD Top Case Fitting Kit Honda CB500F / CBR500R / CB500 Hornet",
    plateRequirement: "Use the plate included with the SH39 on the H0CB59ST fitting. SHAD states the top fitting is not compatible with the small D1B29PAR or aluminium plates.",
    modelYears: "CB500 Hornet family: 2023-2026",
    marketNote: "SHAD catalogs the CB500 Hornet family rather than the Philippine E-Clutch trim separately. Confirm any OEM rear-carrier configuration before ordering for the E-Clutch unit.",
    status: "verified",
    sourceLabel: "SHAD official Honda CB500 Hornet fitment catalog",
    sourceUrl: "https://www.shad.es/en/for-your-motorbike/HONDA/CB500-HORNET/",
    lastChecked: "2026-09-23"
  },
  {
    id: "sh33-fazzio",
    topBoxId: "shad-sh33",
    topBoxLabel: "SHAD SH33",
    productHref: "/accessories/top-box/sh33",
    modelId: "yamaha-fazzio",
    rackCode: "Y0IFZ11ST",
    rackLabel: "SHAD Top Master Yamaha Fazzio",
    plateRequirement: "Use the SH33 mounting plate supplied with the case on Y0IFZ11ST. SHAD explicitly lists SH33 as compatible with this fitting.",
    modelYears: "2022-2026",
    status: "verified",
    sourceLabel: "SHAD official Yamaha Fazzio fitment page",
    sourceUrl: "https://www.shad.es/tl/fitting-kits-for-cases-bags-and-moto-backrests/yamaha/top-master-yamaha-fazzio/",
    lastChecked: "2026-09-23"
  },
  {
    id: "sh33-mio-gear",
    topBoxId: "shad-sh33",
    topBoxLabel: "SHAD SH33",
    productHref: "/accessories/top-box/sh33",
    modelId: "yamaha-mio-gear",
    rackCode: "Y0MZ16ST",
    rackLabel: "SHAD Top Master Yamaha Mio M3 125 / Gear 125",
    plateRequirement: "Use the SH33 mounting plate supplied with the case on Y0MZ16ST. SHAD explicitly lists SH33 among the compatible products.",
    modelYears: "Gear: 2020-2025",
    marketNote: "SHAD currently lists Gear fitment through 2025. Reconfirm the rack before ordering for a later Philippine model year.",
    status: "verified",
    sourceLabel: "SHAD official Yamaha Mio M3 125 / Gear 125 fitment page",
    sourceUrl: "https://www.shad.es/tl/fitting-kits-for-cases-bags-and-moto-backrests/yamaha/top-master-yamaha-mio-m3-125-gear-125/",
    lastChecked: "2026-09-23"
  },
  {
    id: "sh33-burgman-street",
    topBoxId: "shad-sh33",
    topBoxLabel: "SHAD SH33",
    productHref: "/accessories/top-box/sh33",
    modelId: "suzuki-burgman-street",
    rackCode: "S0BR14ST",
    rackLabel: "SHAD Top Case Fitting Kit Suzuki Burgman Street 125",
    plateRequirement: "Use the SH33 mounting plate supplied with the case. SHAD lists SH33 as compatible and states S0BR14ST is not compatible with the big or aluminium mounting plates.",
    modelYears: "2024-2026",
    status: "verified",
    sourceLabel: "SHAD official Suzuki Burgman Street 125 fitment page",
    sourceUrl: "https://www.shad.es/en/bags-and-moto-backrests/suzuki-bags-and-moto-backrests/top-case-fitting-kit-suzuki-burgman-street-125/",
    lastChecked: "2026-09-23"
  },
  {
    id: "sh33-avenis",
    topBoxId: "shad-sh33",
    topBoxLabel: "SHAD SH33",
    productHref: "/accessories/top-box/sh33",
    modelId: "suzuki-avenis",
    rackCode: "S0AV13IST",
    rackLabel: "SHAD Top Case Fitting Kit Suzuki Avenis 125",
    plateRequirement: "Use the SH33 mounting plate supplied with the case on S0AV13IST. SHAD explicitly lists SH33 as compatible with the fitting.",
    modelYears: "2023-2026",
    status: "verified",
    sourceLabel: "SHAD official Suzuki Avenis 125 fitment page",
    sourceUrl: "https://www.shad.es/en/bags-and-moto-backrests/suzuki-bags-and-moto-backrests/top-case-fitting-kit-suzuki-avenis-125/",
    lastChecked: "2026-09-23"
  },
  {
    id: "sh33-click125",
    topBoxId: "shad-sh33",
    topBoxLabel: "SHAD SH33",
    productHref: "/accessories/top-box/sh33",
    modelId: "honda-click-125i",
    rackCode: "H0VR15IST",
    rackLabel: "SHAD Top Case Fitting Kit Honda Click / Vario 125",
    plateRequirement: "Use the SH33 mounting plate supplied with the case. SHAD explicitly lists SH33 and excludes the big and aluminium mounting plates on H0VR15IST.",
    modelYears: "Click/Vario 125: 2015-2026",
    marketNote: "SHAD catalogs this scooter family as Vario 125 in some markets. Confirm the exact Philippine Click125 generation and mounting points before ordering.",
    status: "verified",
    sourceLabel: "SHAD official Honda Click 125/150/160 fitment page",
    sourceUrl: "https://www.shad.es/en-id/fitting-kits-for-cases-bags-and-moto-backrests/honda-fitting-kits-for-cases-bags-and-moto-backrests/top-case-fitting-kit-honda-click-125-150-160/",
    lastChecked: "2026-09-23"
  },
  {
    id: "sh33-click150i",
    topBoxId: "shad-sh33",
    topBoxLabel: "SHAD SH33",
    productHref: "/accessories/top-box/sh33",
    modelId: "honda-click-150i",
    rackCode: "H0VR15IST",
    rackLabel: "SHAD Top Case Fitting Kit Honda Click / Vario 125/150/160",
    plateRequirement: "Use the SH33 mounting plate supplied with the case. SHAD explicitly lists SH33 and excludes the big and aluminium mounting plates on H0VR15IST.",
    modelYears: "Click150i MotoIndex generation: 2018-2022; SHAD Vario 150 coverage: 2015-2022",
    marketNote: "SHAD catalogs this family as Vario 150 in Indonesia; MotoIndex keeps the Philippine Click150i naming and generation boundary.",
    status: "verified",
    sourceLabel: "SHAD official Honda Click 125/150/160 fitment page",
    sourceUrl: "https://www.shad.es/en-id/fitting-kits-for-cases-bags-and-moto-backrests/honda-fitting-kits-for-cases-bags-and-moto-backrests/top-case-fitting-kit-honda-click-125-150-160/",
    lastChecked: "2026-09-23"
  },
  {
    id: "sh33-cb650r",
    topBoxId: "shad-sh33",
    topBoxLabel: "SHAD SH33",
    productHref: "/accessories/top-box/sh33",
    modelId: "honda-cb650r",
    rackCode: "H0CR64ST",
    rackLabel: "SHAD Top Case Fitting Kit Honda CB650R / CBR650R",
    plateRequirement: "Use the SH33 mounting plate supplied with the case on H0CR64ST. SHAD explicitly lists SH33 among the compatible products.",
    modelYears: "CB650R: 2024-2026",
    status: "verified",
    sourceLabel: "SHAD official Honda CB650R / CBR650R fitment page",
    sourceUrl: "https://www.shad.es/en/bags-and-moto-backrests/honda-bags-and-moto-backrests/top-case-fitting-kit-honda-cb650r-cbr650r/",
    lastChecked: "2026-09-23"
  },
  {
    id: "sh33-tmax-tech-max",
    topBoxId: "shad-sh33",
    topBoxLabel: "SHAD SH33",
    productHref: "/accessories/top-box/sh33",
    modelId: "yamaha-tmax",
    rackCode: "Y0TX52ST",
    rackLabel: "SHAD Top Case Fitting Kit Yamaha TMAX 560 Tech Max",
    plateRequirement: "Use the SH33 mounting plate supplied with the case on Y0TX52ST. SHAD explicitly lists SH33 among the compatible products.",
    modelYears: "TMAX 560 Tech Max: 2022-2026",
    status: "verified",
    sourceLabel: "SHAD official Yamaha TMAX 560 Tech Max fitment page",
    sourceUrl: "https://www.shad.es/fijaciones-de-maletas-bolsas-y-respaldos/yamaha/fijacion-para-maleta-superior-yamaha-tmax-560-tech-max/",
    lastChecked: "2026-09-23"
  },
  {
    id: "sh33-lexi155",
    topBoxId: "shad-sh33",
    topBoxLabel: "SHAD SH33",
    productHref: "/accessories/top-box/sh33",
    modelId: "yamaha-lexi-155",
    rackCode: "Y0LX14IST",
    rackLabel: "SHAD Top Master Yamaha Lexi LX 155",
    plateRequirement: "Use the SH33 mounting plate supplied with the case on Y0LX14IST. SHAD explicitly lists SH33 as a compatible product.",
    modelYears: "2024-2026",
    marketNote: "SHAD names the regional model Lexi LX 155; MotoIndex keeps the Philippine Lexi 155 name while retaining the exact rack code and years.",
    status: "verified",
    sourceLabel: "SHAD official Yamaha Lexi LX 155 fitment page",
    sourceUrl: "https://www.shad.es/en-id/fitting-kits-for-cases-bags-and-moto-backrests/yamaha-fitting-kits-for-cases-bags-and-moto-backrests/top-master-yamaha-lexi-lx-155/",
    lastChecked: "2026-09-23"
  },
  {
    id: "sh33-klx150",
    topBoxId: "shad-sh33",
    topBoxLabel: "SHAD SH33",
    productHref: "/accessories/top-box/sh33",
    modelId: "kawasaki-klx150",
    rackCode: "K0IKL18ST",
    rackLabel: "SHAD Top Master Kawasaki KLX150",
    plateRequirement: "Use the SH33 mounting plate supplied with the case. SHAD explicitly lists SH33 and states K0IKL18ST is not compatible with the big or aluminium mounting plates.",
    modelYears: "2015-2026",
    status: "verified",
    sourceLabel: "SHAD official Kawasaki KLX150 fitment page",
    sourceUrl: "https://www.shad.es/en-id/fitting-kits-for-cases-bags-and-moto-backrests/kawasaki-fitting-kits-for-cases-bags-and-moto-backrests/top-master-kawasaki-klx-150/",
    lastChecked: "2026-09-23"
  },
  {
    id: "sh33-aerox-v3",
    topBoxId: "shad-sh33",
    topBoxLabel: "SHAD SH33",
    productHref: "/accessories/top-box/sh33",
    modelId: "yamaha-aerox-v3",
    rackCode: "Y0AE14IST",
    rackLabel: "SHAD Top Master Yamaha Aerox",
    plateRequirement: "Use the SH33 mounting plate supplied with the case on Y0AE14IST. SHAD explicitly lists SH33 as compatible; the fitting excludes big and aluminium mounting plates.",
    modelYears: "Aerox 155: 2021-2026; Aerox Alpha: 2024-2026",
    marketNote: "MotoIndex keeps this relationship on the current Aerox V3 canonical while preserving SHAD's broader Aerox 155 / Aerox Alpha family coverage.",
    status: "verified",
    sourceLabel: "SHAD official Yamaha Aerox fitment page",
    sourceUrl: "https://www.shad.es/tl/fitting-kits-for-cases-bags-and-moto-backrests/yamaha/top-master-yamaha-aerox/",
    lastChecked: "2026-09-23"
  },
  {
    id: "sh33-adv160",
    topBoxId: "shad-sh33",
    topBoxLabel: "SHAD SH33",
    productHref: "/accessories/top-box/sh33",
    modelId: "honda-adv-160",
    rackCode: "H0XD12IST",
    rackLabel: "SHAD Top Master Honda ADV 160",
    plateRequirement: "Use the SH33 mounting plate supplied with the case on H0XD12IST. SHAD explicitly lists SH33 as a compatible product.",
    modelYears: "2022-2026",
    status: "verified",
    sourceLabel: "SHAD official Honda ADV 160 fitment page",
    sourceUrl: "https://www.shad.es/tl/fitting-kits-for-cases-bags-and-moto-backrests/honda/top-master-honda-adv-160/",
    lastChecked: "2026-09-23"
  },
  {
    id: "sh33-click160",
    topBoxId: "shad-sh33",
    topBoxLabel: "SHAD SH33",
    productHref: "/accessories/top-box/sh33",
    modelId: "honda-click-160",
    rackCode: "H0VR15IST",
    rackLabel: "SHAD top-case fitting kit Honda Click 125/150/160",
    plateRequirement: "Use the SH33 mounting plate supplied with the case on H0VR15IST. SHAD explicitly lists SH33 as compatible with the fitting.",
    modelYears: "Click/Vario 160: 2022-2026",
    marketNote: "SHAD catalogs this platform as Click/Vario 160 by market; MotoIndex keeps the Philippine Click160 naming and year boundary.",
    status: "verified",
    sourceLabel: "SHAD official Honda Click 125/150/160 fitment page",
    sourceUrl: "https://www.shad.es/tl/fitting-kits-for-cases-bags-and-moto-backrests/honda/top-case-fitting-kit-honda-click-125-150-160/",
    lastChecked: "2026-09-23"
  },
  {
    id: "sh33-pcx160",
    topBoxId: "shad-sh33",
    topBoxLabel: "SHAD SH33",
    productHref: "/accessories/top-box/sh33",
    modelId: "honda-pcx-160",
    rackCode: "H0IPC11ST",
    rackLabel: "SHAD Top Master Honda PCX",
    plateRequirement: "Use the SH33 mounting plate supplied with the case on H0IPC11ST. SHAD explicitly lists SH33 as compatible with the PCX fitting.",
    modelYears: "PCX: 2010-2026",
    marketNote: "SHAD lists the PCX family rather than a Philippines-specific PCX 160 trim; verify the exact local model year before ordering.",
    status: "verified",
    sourceLabel: "SHAD official Honda PCX fitment page",
    sourceUrl: "https://www.shad.es/tl/fitting-kits-for-cases-bags-and-moto-backrests/honda/top-master-honda-pcx/",
    lastChecked: "2026-09-23"
  },
  {
    id: "sh33-sniper-155",
    topBoxId: "shad-sh33",
    topBoxLabel: "SHAD SH33",
    productHref: "/accessories/top-box/sh33",
    modelId: "yamaha-sniper-155",
    rackCode: "Y0IMX18ST",
    rackLabel: "SHAD Top Master Yamaha Sniper 155 / MX King 150",
    plateRequirement: "Use the SH33 mounting plate supplied with the case on Y0IMX18ST. SHAD explicitly lists SH33 and excludes the big and aluminium mounting plates.",
    modelYears: "2015-2026",
    marketNote: "SHAD titles the fitting for Yamaha Sniper 155 while its compatibility table uses the regional MX King 150 name. Confirm the exact Philippine model year before ordering.",
    status: "verified",
    sourceLabel: "SHAD official Yamaha Sniper 155 fitment page",
    sourceUrl: "https://www.shad.es/en-id/fitting-kits-for-cases-bags-and-moto-backrests/yamaha-fitting-kits-for-cases-bags-and-moto-backrests/top-master-yamaha-sniper-155/",
    lastChecked: "2026-09-23"
  },
  {
    id: "sh33-cb150x",
    topBoxId: "shad-sh33",
    topBoxLabel: "SHAD SH33",
    productHref: "/accessories/top-box/sh33",
    modelId: "honda-cb150x",
    rackCode: "H0ICB16ST",
    rackLabel: "SHAD Top Master Honda CB150X",
    plateRequirement: "Use the SH33 mounting plate supplied with the case on H0ICB16ST. SHAD explicitly lists SH33; the fitting excludes aluminium mounting plates.",
    modelYears: "2021-2025",
    marketNote: "The exact SHAD CB150X fitting page currently stops at 2025. Reconfirm the rack before ordering for a later Philippine model year.",
    status: "verified",
    sourceLabel: "SHAD official Honda CB150R Streetfire / CB150X fitment page",
    sourceUrl: "https://www.shad.es/en-id/fitting-kits-for-cases-bags-and-moto-backrests/honda-fitting-kits-for-cases-bags-and-moto-backrests/top-master-honda-cb150r-streetfire-cb150x/",
    lastChecked: "2026-09-23"
  },
  {
    id: "sh33-z500",
    topBoxId: "shad-sh33",
    topBoxLabel: "SHAD SH33",
    productHref: "/accessories/top-box/sh33",
    modelId: "kawasaki-z500",
    rackCode: "K0Z554ST",
    rackLabel: "SHAD Top Case Fitting Kit Kawasaki Z500",
    plateRequirement: "Use the SH33 mounting plate supplied with the case on K0Z554ST. SHAD explicitly lists SH33 as a compatible product.",
    modelYears: "2024-2025",
    marketNote: "SHAD's broader current catalog surfaces Z500 for 2026, but the exact fitting detail table currently stops at 2025. Reconfirm the exact rack package before ordering for a 2026 Philippine unit.",
    status: "verified",
    sourceLabel: "SHAD official Kawasaki Z500 fitment page",
    sourceUrl: "https://www.shad.es/tl/fitting-kits-for-cases-bags-and-moto-backrests/kawasaki/top-case-fitting-kit-kawasaki-z500/",
    lastChecked: "2026-09-23"
  },
  {
    id: "sh33-vstrom-250-sx",
    topBoxId: "shad-sh33",
    topBoxLabel: "SHAD SH33",
    productHref: "/accessories/top-box/sh33",
    modelId: "suzuki-v-strom-250-sx",
    rackCode: "S0VS23IST",
    rackLabel: "SHAD Top Master Suzuki V-Strom 250 SX",
    plateRequirement: "Use the SH33 mounting plate supplied with the case on S0VS23IST. SHAD explicitly lists SH33 as a compatible product.",
    modelYears: "2023-2026",
    status: "verified",
    sourceLabel: "SHAD official Suzuki V-Strom 250 SX fitment page",
    sourceUrl: "https://www.shad.es/en-id/fitting-kits-for-cases-bags-and-moto-backrests/suzuki-fitting-kits-for-cases-bags-and-moto-backrests/top-master-suzuki-v-strom-250-sx/",
    lastChecked: "2026-09-23"
  },
  {
    id: "sh33-burgman-400",
    topBoxId: "shad-sh33",
    topBoxLabel: "SHAD SH33",
    productHref: "/accessories/top-box/sh33",
    modelId: "suzuki-burgman-400",
    rackCode: "S0BR47ST",
    rackLabel: "SHAD Top Case Fitting Kit Suzuki Burgman 400",
    plateRequirement: "Use the SH33 mounting plate supplied with the case on S0BR47ST. SHAD explicitly lists SH33; the fitting excludes aluminium mounting plates.",
    modelYears: "2017-2026",
    status: "verified",
    sourceLabel: "SHAD official Suzuki Burgman 400 fitment page",
    sourceUrl: "https://www.shad.es/en/bags-and-moto-backrests/suzuki-bags-and-moto-backrests/top-case-fitting-kit-suzuki-burgman-400-2/",
    lastChecked: "2026-09-23"
  },
  {
    id: "sh33-xmax",
    topBoxId: "shad-sh33",
    topBoxLabel: "SHAD SH33",
    productHref: "/accessories/top-box/sh33",
    modelId: "yamaha-xmax",
    rackCode: "Y0XM33ST",
    rackLabel: "SHAD Top Case Fitting Kit Yamaha XMAX 125/300 Tech",
    plateRequirement: "Use the SH33 mounting plate supplied with the case on Y0XM33ST. SHAD explicitly lists SH33 as a compatible product.",
    modelYears: "XMAX 300: 2023-2025",
    marketNote: "The exact non-Tech XMAX 300 Y0XM33ST table currently stops at 2025. Reconfirm fitment before ordering for a 2026 Philippine XMAX.",
    status: "verified",
    sourceLabel: "SHAD official Yamaha XMAX 125/300 Tech fitment page",
    sourceUrl: "https://www.shad.es/en/bags-and-moto-backrests/yamaha-bags-and-moto-backrests/top-case-fitting-kit-yamaha-xmax-125-300-tech/",
    lastChecked: "2026-09-23"
  },
  {
    id: "sh33-mio-i125",
    topBoxId: "shad-sh33",
    topBoxLabel: "SHAD SH33",
    productHref: "/accessories/top-box/sh33",
    modelId: "yamaha-mio-i-125",
    rackCode: "Y0MZ16ST",
    rackLabel: "SHAD Top Master Yamaha Mio i125 / Gear 125",
    plateRequirement: "Use the SH33 mounting plate supplied with the case on Y0MZ16ST. SHAD lists the compact case family on this fitting.",
    modelYears: "Mio i125: 2014-2025",
    marketNote: "SHAD currently lists Mio i125 fitment through 2025. Reconfirm the rack before ordering for a later Philippine model year.",
    status: "verified",
    sourceLabel: "SHAD official Yamaha Mio i125 / Gear 125 fitment page",
    sourceUrl: "https://www.shad.es/tl/fitting-kits-for-cases-bags-and-moto-backrests/yamaha/top-master-yamaha-mio-m3-125-gear-125/",
    lastChecked: "2026-09-23"
  },
  {
    id: "sh33-nx500",
    topBoxId: "shad-sh33",
    topBoxLabel: "SHAD SH33",
    productHref: "/accessories/top-box/sh33",
    modelId: "honda-nx500-e-clutch",
    rackCode: "H0CX55ST",
    rackLabel: "SHAD Top Case Fitting Kit Honda CB500X / NX500",
    plateRequirement: "Use the SH33 mounting plate supplied with the case on H0CX55ST.",
    modelYears: "NX500: 2023-2026",
    marketNote: "SHAD lists the NX500 model family rather than the Philippine E-Clutch trim separately. Confirm the exact local model year and OEM rear-carrier configuration before ordering.",
    status: "verified",
    sourceLabel: "SHAD official Honda NX500 fitment catalog",
    sourceUrl: "https://www.shad.es/en/equipment/HONDA/NX-500/",
    lastChecked: "2026-09-23"
  },
  {
    id: "sh33-adv350",
    topBoxId: "shad-sh33",
    topBoxLabel: "SHAD SH33",
    productHref: "/accessories/top-box/sh33",
    modelId: "honda-adv-350",
    rackCode: "H0FR15IST",
    rackLabel: "SHAD Top Case Fitting Kit Honda Forza 125 / ADV350",
    plateRequirement: "Use the SH33 mounting plate supplied with the case on H0FR15IST.",
    modelYears: "ADV350: 2025-2026",
    status: "verified",
    sourceLabel: "SHAD official Honda ADV350 fitment catalog",
    sourceUrl: "https://www.shad.es/tl/for-your-motorbike/types/Maleta-superior-%28ST%29/HONDA/ADV-350/",
    lastChecked: "2026-09-23"
  },
  {
    id: "sh33-mio-gravis",
    topBoxId: "shad-sh33",
    topBoxLabel: "SHAD SH33",
    productHref: "/accessories/top-box/sh33",
    modelId: "yamaha-mio-gravis",
    rackCode: "Y0FG13IST",
    rackLabel: "SHAD Top Master Yamaha Mio Gravis",
    plateRequirement: "Use the SH33 mounting plate supplied with the case on Y0FG13IST. SHAD states this fitting is not compatible with aluminium mounting plates.",
    modelYears: "2023-2025",
    marketNote: "The exact SHAD fitting page currently stops at 2025. Reconfirm the rack before ordering for a later Philippine model year.",
    status: "verified",
    sourceLabel: "SHAD official Yamaha Mio Gravis fitment page",
    sourceUrl: "https://www.shad.es/en-id/fitting-kits-for-cases-bags-and-moto-backrests/yamaha-fitting-kits-for-cases-bags-and-moto-backrests/top-master-yamaha-mio-gravis/",
    lastChecked: "2026-09-23"
  },
  {
    id: "sh33-xsr155",
    topBoxId: "shad-sh33",
    topBoxLabel: "SHAD SH33",
    productHref: "/accessories/top-box/sh33",
    modelId: "yamaha-xsr155",
    rackCode: "Y0IXS19ST",
    rackLabel: "SHAD Top Case Fitting Kit Yamaha XSR125 / XSR155",
    plateRequirement: "Use the SH33 mounting plate supplied with the case on Y0IXS19ST.",
    modelYears: "XSR155: 2019-2025",
    marketNote: "The exact SHAD XSR155 fitting table currently stops at 2025. Reconfirm the rack before ordering for a later Philippine model year.",
    status: "verified",
    sourceLabel: "SHAD official Yamaha XSR125 / XSR155 fitment page",
    sourceUrl: "https://www.shad.es/tl/fitting-kits-for-cases-bags-and-moto-backrests/yamaha/top-case-fitting-kit-yamaha-xsr-125-155/",
    lastChecked: "2026-09-23"
  },
  {
    id: "sh33-mt07",
    topBoxId: "shad-sh33",
    topBoxLabel: "SHAD SH33",
    productHref: "/accessories/top-box/sh33",
    modelId: "yamaha-mt-07",
    rackCode: "Y0MT75ST",
    rackLabel: "SHAD Top Case Fitting Kit Yamaha MT-07",
    plateRequirement: "Use the SH33 mounting plate supplied with the case on Y0MT75ST.",
    modelYears: "2025-2026",
    status: "verified",
    sourceLabel: "SHAD official Yamaha MT-07 fitment catalog",
    sourceUrl: "https://www.shad.es/en/for-your-motorbike/YAMAHA/MT07/",
    lastChecked: "2026-09-23"
  },
  {
    id: "sh33-transalp-750",
    topBoxId: "shad-sh33",
    topBoxLabel: "SHAD SH33",
    productHref: "/accessories/top-box/sh33",
    modelId: "honda-xl750-transalp",
    rackCode: "H0TR73ST",
    rackLabel: "SHAD Top Case Fitting Kit Honda XL750 Transalp",
    plateRequirement: "Use the SH33 mounting plate supplied with the case on H0TR73ST.",
    modelYears: "2023-2026",
    status: "verified",
    sourceLabel: "SHAD official Honda XL750 Transalp fitment page",
    sourceUrl: "https://www.shad.es/en/bags-and-moto-backrests/honda-bags-and-moto-backrests/top-case-fitting-kit-honda-transalp-xl-750/",
    lastChecked: "2026-09-23"
  },
  {
    id: "sh33-gixxer-sf250",
    topBoxId: "shad-sh33",
    topBoxLabel: "SHAD SH33",
    productHref: "/accessories/top-box/sh33",
    modelId: "suzuki-gixxer-sf250",
    rackCode: "S0GX22IST",
    rackLabel: "SHAD Top Master Suzuki Gixxer SF 250",
    plateRequirement: "Use the SH33 mounting plate supplied with the case on S0GX22IST.",
    modelYears: "2021-2025",
    marketNote: "The exact SHAD Gixxer SF 250 rack coverage currently stops at 2025. Reconfirm fitment for a later Philippine model year.",
    status: "verified",
    sourceLabel: "SHAD official Suzuki Gixxer SF 250 fitment page",
    sourceUrl: "https://www.shad.es/en-id/for-your-motorbike/SUZUKI/GIXXER-SF-250/",
    lastChecked: "2026-09-23"
  },


  {
    id: "sh29-fazzio",
    topBoxId: "shad-sh29",
    topBoxLabel: "SHAD SH29",
    productHref: "/accessories/top-box/sh29",
    modelId: "yamaha-fazzio",
    rackCode: "Y0IFZ11ST",
    rackLabel: "SHAD Top Master Yamaha Fazzio",
    plateRequirement: "Use the SH29 small mounting plate supplied with the case on Y0IFZ11ST. SHAD explicitly lists SH29 among the compatible products.",
    modelYears: "2022-2026",
    status: "verified",
    sourceLabel: "SHAD official Yamaha Fazzio fitment page",
    sourceUrl: "https://www.shad.es/tl/fitting-kits-for-cases-bags-and-moto-backrests/yamaha/top-master-yamaha-fazzio/",
    lastChecked: "2026-09-23"
  },
  {
    id: "sh29-aerox-v3",
    topBoxId: "shad-sh29",
    topBoxLabel: "SHAD SH29",
    productHref: "/accessories/top-box/sh29",
    modelId: "yamaha-aerox-v3",
    rackCode: "Y0AE14IST",
    rackLabel: "SHAD Top Master Yamaha Aerox",
    plateRequirement: "Use the SH29 small mounting plate supplied with the case on Y0AE14IST. SHAD explicitly lists SH29 and excludes the big and aluminium mounting plates.",
    modelYears: "Aerox 155: 2021-2026; Aerox Alpha: 2024-2026",
    marketNote: "MotoIndex keeps this relationship on the current Aerox V3 canonical while preserving SHAD's broader Aerox 155 / Aerox Alpha family coverage.",
    status: "verified",
    sourceLabel: "SHAD official Yamaha Aerox fitment page",
    sourceUrl: "https://www.shad.es/tl/fitting-kits-for-cases-bags-and-moto-backrests/yamaha/top-master-yamaha-aerox/",
    lastChecked: "2026-09-23"
  },
  {
    id: "sh39-nmax-v3",
    topBoxId: "shad-sh39",
    topBoxLabel: "SHAD SH39",
    productHref: "/accessories/top-box/sh39",
    modelId: "yamaha-nmax-v3",
    rackCode: "Y0NM14IST",
    rackLabel: "SHAD Top Master Yamaha NMAX Turbo / Neo",
    plateRequirement: "Use the plate included with the SH39 on the bike-specific Top Master fitting.",
    modelYears: "2025-2026",
    marketNote: "The 2025-2026 SHAD catalog names NMAX Turbo / Neo. Confirm that the rack code matches the exact Philippine NMAX variant before purchase.",
    status: "research",
    sourceLabel: "SHAD official Yamaha top-case fitment catalog",
    sourceUrl: "https://www.shad.es/tl/for-your-motorbike/types/Maleta-superior-%28ST%29/YAMAHA/",
    lastChecked: "2026-08-25"
  }
];

export function getTopBoxFitmentsForProduct(topBoxId: string) {
  return topBoxFitments.filter((fitment) => fitment.topBoxId === topBoxId);
}

export function getTopBoxFitmentsForModel(modelId: string) {
  return topBoxFitments.filter((fitment) => fitment.modelId === modelId);
}
