import type { TopBoxFitment } from "./types";

// Manufacturer fitment records checked through 2026-09-23. These edges are deliberately
// product + motorcycle specific; capacity heuristics are not treated as fitment.
export const topBoxFitments: TopBoxFitment[] = [
  {
    id: "sh39-aerox-155",
    topBoxId: "shad-sh39",
    topBoxLabel: "SHAD SH39",
    productHref: "/accessories/top-box/sh39",
    modelId: "yamaha-aerox-v3",
    rackCode: "Y0AE14IST",
    rackLabel: "SHAD Top Master Yamaha Aerox",
    plateRequirement: "Use the plate included with the SH39 on the bike-specific Top Master fitting.",
    modelYears: "Aerox 155: 2021-2026; Aerox Alpha: 2024-2026",
    status: "verified",
    sourceLabel: "SHAD official Yamaha Aerox fitment page",
    sourceUrl: "https://www.shad.es/tl/fitting-kits-for-cases-bags-and-moto-backrests/yamaha/top-master-yamaha-aerox/",
    lastChecked: "2026-08-25"
  },
  {
    id: "sh39-adv160",
    topBoxId: "shad-sh39",
    topBoxLabel: "SHAD SH39",
    productHref: "/accessories/top-box/sh39",
    modelId: "honda-adv-160",
    rackCode: "H0XD12IST",
    rackLabel: "SHAD Top Master Honda ADV 160",
    plateRequirement: "Use the plate included with the SH39 on the bike-specific Top Master fitting.",
    modelYears: "2022-2026",
    status: "verified",
    sourceLabel: "SHAD official Honda ADV 160 fitment page",
    sourceUrl: "https://www.shad.es/tl/fitting-kits-for-cases-bags-and-moto-backrests/honda/top-master-honda-adv-160/",
    lastChecked: "2026-08-25"
  },
  {
    id: "sh39-click160",
    topBoxId: "shad-sh39",
    topBoxLabel: "SHAD SH39",
    productHref: "/accessories/top-box/sh39",
    modelId: "honda-click-160",
    rackCode: "H0VR15IST",
    rackLabel: "SHAD top-case fitting kit Honda Click 125/150/160",
    plateRequirement: "Use the plate included with the SH39 on the bike-specific fitting kit.",
    modelYears: "Click/Vario 160: 2022-2026",
    marketNote: "SHAD catalogs the same platform as Click/Vario 160 by market; confirm the local model-year before ordering.",
    status: "verified",
    sourceLabel: "SHAD official Honda fitment catalog",
    sourceUrl: "https://www.shad.es/tl/for-your-motorbike/HONDA/",
    lastChecked: "2026-08-25"
  },
  {
    id: "sh39-pcx160",
    topBoxId: "shad-sh39",
    topBoxLabel: "SHAD SH39",
    productHref: "/accessories/top-box/sh39",
    modelId: "honda-pcx-160",
    rackCode: "H0IPC11ST",
    rackLabel: "SHAD Top Master Honda PCX",
    plateRequirement: "Use the plate included with the SH39 on the bike-specific Top Master fitting.",
    modelYears: "PCX: 2010-2026",
    marketNote: "SHAD lists the PCX family rather than a Philippines-specific PCX 160 trim; verify the exact year before ordering.",
    status: "verified",
    sourceLabel: "SHAD official Honda PCX fitment page",
    sourceUrl: "https://www.shad.es/en-id/fitting-kits-for-cases-bags-and-moto-backrests/honda-fitting-kits-for-cases-bags-and-moto-backrests/top-master-honda-pcx/",
    lastChecked: "2026-08-25"
  },
  {
    id: "sh39-fazzio",
    topBoxId: "shad-sh39",
    topBoxLabel: "SHAD SH39",
    productHref: "/accessories/top-box/sh39",
    modelId: "yamaha-fazzio",
    rackCode: "Y0IFZ11ST",
    rackLabel: "SHAD Top Master Yamaha Fazzio",
    plateRequirement: "Use the plate included with the SH39 on the Y0IFZ11ST Top Master fitting. SHAD states this fitting is not compatible with the big or aluminium mounting plates.",
    modelYears: "2022-2026",
    status: "verified",
    sourceLabel: "SHAD official Yamaha Fazzio fitment page",
    sourceUrl: "https://www.shad.es/en-id/fitting-kits-for-cases-bags-and-moto-backrests/yamaha-fitting-kits-for-cases-bags-and-moto-backrests/top-master-yamaha-fazzio/",
    lastChecked: "2026-09-23"
  },
  {
    id: "sh33-beat",
    topBoxId: "shad-sh33",
    topBoxLabel: "SHAD SH33",
    productHref: "/accessories/top-box/sh33",
    modelId: "honda-beat",
    rackCode: "H0IBT11ST",
    rackLabel: "SHAD Top Master Honda BeAT / Scoopy / Genio",
    plateRequirement: "Use the SH33 small mounting plate D1B29PAR on the H0IBT11ST fitting. SHAD limits this fitting to the small base plate and top cases up to SH34.",
    modelYears: "BeAT family: 2008-2026",
    marketNote: "SHAD groups BeAT, Scoopy and Genio on this fitting. Confirm the exact Philippine BeAT generation and mounting points before ordering.",
    status: "verified",
    sourceLabel: "SHAD official Honda BeAT / Scoopy / Genio fitment page",
    sourceUrl: "https://www.shad.es/en-id/fitting-kits-for-cases-bags-and-moto-backrests/honda-fitting-kits-for-cases-bags-and-moto-backrests/top-master-honda-beat-scoopy-genio/",
    lastChecked: "2026-09-23"
  },
  {
    id: "sh39-mio-gear",
    topBoxId: "shad-sh39",
    topBoxLabel: "SHAD SH39",
    productHref: "/accessories/top-box/sh39",
    modelId: "yamaha-mio-gear",
    rackCode: "Y0MZ16ST",
    rackLabel: "SHAD Top Master Yamaha Mio M3 125 / Gear 125",
    plateRequirement: "Use the plate included with the SH39 on the Y0MZ16ST Top Master fitting.",
    modelYears: "Gear: 2020-2025",
    marketNote: "SHAD currently lists Gear fitment through 2025. Reconfirm the rack before ordering for a later Philippine model year.",
    status: "verified",
    sourceLabel: "SHAD official Yamaha Mio M3 125 / Gear 125 fitment page",
    sourceUrl: "https://www.shad.es/tl/fitting-kits-for-cases-bags-and-moto-backrests/yamaha/top-master-yamaha-mio-m3-125-gear-125/",
    lastChecked: "2026-09-23"
  },
  {
    id: "sh39-mio-i125",
    topBoxId: "shad-sh39",
    topBoxLabel: "SHAD SH39",
    productHref: "/accessories/top-box/sh39",
    modelId: "yamaha-mio-i-125",
    rackCode: "Y0MZ16ST",
    rackLabel: "SHAD Top Master Yamaha Mio i125 / Gear 125",
    plateRequirement: "Use the plate included with the SH39 on the Y0MZ16ST Top Master fitting.",
    modelYears: "Mio i125: 2014-2025",
    marketNote: "SHAD currently lists Mio i125 fitment through 2025. Reconfirm the rack before ordering for a later Philippine model year.",
    status: "verified",
    sourceLabel: "SHAD official Yamaha Mio i125 / Gear 125 fitment page",
    sourceUrl: "https://www.shad.es/tl/fitting-kits-for-cases-bags-and-moto-backrests/yamaha/top-master-yamaha-mio-m3-125-gear-125/",
    lastChecked: "2026-09-23"
  },
  {
    id: "sh39-burgman-street",
    topBoxId: "shad-sh39",
    topBoxLabel: "SHAD SH39",
    productHref: "/accessories/top-box/sh39",
    modelId: "suzuki-burgman-street",
    rackCode: "S0BR14ST",
    rackLabel: "SHAD Top Case Fitting Kit Suzuki Burgman Street 125",
    plateRequirement: "Use the plate included with the SH39. SHAD states S0BR14ST is not compatible with the big or aluminium mounting plates.",
    modelYears: "2024-2026",
    status: "verified",
    sourceLabel: "SHAD official Suzuki Burgman Street 125 fitment page",
    sourceUrl: "https://www.shad.es/en/bags-and-moto-backrests/suzuki-bags-and-moto-backrests/top-case-fitting-kit-suzuki-burgman-street-125/",
    lastChecked: "2026-09-23"
  },
  {
    id: "sh39-avenis",
    topBoxId: "shad-sh39",
    topBoxLabel: "SHAD SH39",
    productHref: "/accessories/top-box/sh39",
    modelId: "suzuki-avenis",
    rackCode: "S0AV13IST",
    rackLabel: "SHAD Top Case Fitting Kit Suzuki Avenis 125",
    plateRequirement: "Use the plate included with the SH39 on the S0AV13IST fitting.",
    modelYears: "2023-2026",
    status: "verified",
    sourceLabel: "SHAD official Suzuki Avenis 125 fitment page",
    sourceUrl: "https://www.shad.es/en/bags-and-moto-backrests/suzuki-bags-and-moto-backrests/top-case-fitting-kit-suzuki-avenis-125/",
    lastChecked: "2026-09-23"
  },
  {
    id: "sh39-click125",
    topBoxId: "shad-sh39",
    topBoxLabel: "SHAD SH39",
    productHref: "/accessories/top-box/sh39",
    modelId: "honda-click-125i",
    rackCode: "H0VR15IST",
    rackLabel: "SHAD Top Case Fitting Kit Honda Click / Vario 125",
    plateRequirement: "Use the plate included with the SH39. SHAD states H0VR15IST is not compatible with the big or aluminium mounting plates.",
    modelYears: "Click/Vario 125: 2015-2026",
    marketNote: "SHAD catalogs this scooter family as Vario 125 in some markets. Confirm the exact Philippine Click125 generation and mounting points before ordering.",
    status: "verified",
    sourceLabel: "SHAD official Honda Click 125/150/160 fitment page",
    sourceUrl: "https://www.shad.es/en-id/fitting-kits-for-cases-bags-and-moto-backrests/honda-fitting-kits-for-cases-bags-and-moto-backrests/top-case-fitting-kit-honda-click-125-150-160/",
    lastChecked: "2026-09-23"
  },
  {
    id: "sh39-burgman-400",
    topBoxId: "shad-sh39",
    topBoxLabel: "SHAD SH39",
    productHref: "/accessories/top-box/sh39",
    modelId: "suzuki-burgman-400",
    rackCode: "S0BR47ST",
    rackLabel: "SHAD Top Case Fitting Kit Suzuki Burgman 400",
    plateRequirement: "Use the plate included with the SH39 on the S0BR47ST fitting.",
    modelYears: "2017-2026",
    status: "verified",
    sourceLabel: "SHAD official Suzuki Burgman 400 fitment page",
    sourceUrl: "https://www.shad.es/en/bags-and-moto-backrests/suzuki-bags-and-moto-backrests/top-case-fitting-kit-suzuki-burgman-400-2/",
    lastChecked: "2026-09-23"
  },
  {
    id: "sh39-cb650r",
    topBoxId: "shad-sh39",
    topBoxLabel: "SHAD SH39",
    productHref: "/accessories/top-box/sh39",
    modelId: "honda-cb650r",
    rackCode: "H0CR64ST",
    rackLabel: "SHAD Top Case Fitting Kit Honda CB650R / CBR650R",
    plateRequirement: "Use the plate included with the SH39 on the H0CR64ST fitting.",
    modelYears: "CB650R: 2024-2026",
    status: "verified",
    sourceLabel: "SHAD official Honda CB650R / CBR650R fitment page",
    sourceUrl: "https://www.shad.es/en/bags-and-moto-backrests/honda-bags-and-moto-backrests/top-case-fitting-kit-honda-cb650r-cbr650r/",
    lastChecked: "2026-09-23"
  },
  {
    id: "sh39-nx500",
    topBoxId: "shad-sh39",
    topBoxLabel: "SHAD SH39",
    productHref: "/accessories/top-box/sh39",
    modelId: "honda-nx500-e-clutch",
    rackCode: "H0CX55ST",
    rackLabel: "SHAD Top Case Fitting Kit Honda CB500X / NX500",
    plateRequirement: "Use the plate included with the SH39 on the H0CX55ST fitting.",
    modelYears: "NX500: 2023-2026",
    marketNote: "The SHAD fitment is model-family specific. Confirm the Philippine E-Clutch model year and any OEM rear-carrier configuration before ordering.",
    status: "verified",
    sourceLabel: "SHAD official Honda NX500 fitment catalog",
    sourceUrl: "https://www.shad.es/en/equipment/HONDA/NX-500/",
    lastChecked: "2026-09-23"
  },
  {
    id: "sh39-adv350",
    topBoxId: "shad-sh39",
    topBoxLabel: "SHAD SH39",
    productHref: "/accessories/top-box/sh39",
    modelId: "honda-adv-350",
    rackCode: "H0FR15IST",
    rackLabel: "SHAD Top Case Fitting Kit Honda Forza 125 / ADV350",
    plateRequirement: "Use the plate included with the SH39 on the H0FR15IST fitting.",
    modelYears: "ADV350: 2025-2026",
    status: "verified",
    sourceLabel: "SHAD official Philippines-market Honda ADV350 fitment catalog",
    sourceUrl: "https://www.shad.es/tl/for-your-motorbike/types/Maleta-superior-%28ST%29/HONDA/ADV-350/",
    lastChecked: "2026-09-23"
  },
  {
    id: "sh39-tmax-tech-max",
    topBoxId: "shad-sh39",
    topBoxLabel: "SHAD SH39",
    productHref: "/accessories/top-box/sh39",
    modelId: "yamaha-tmax",
    rackCode: "Y0TX52ST",
    rackLabel: "SHAD Top Case Fitting Kit Yamaha TMAX 560 Tech Max",
    plateRequirement: "Use the plate included with the SH39 on the Y0TX52ST fitting.",
    modelYears: "TMAX 560 Tech Max: 2022-2026",
    status: "verified",
    sourceLabel: "SHAD official Yamaha TMAX 560 Tech Max fitment page",
    sourceUrl: "https://www.shad.es/en/bags-and-moto-backrests/yamaha-bags-and-moto-backrests/top-case-fitting-kit-yamaha-tmax-560-tech-max/",
    lastChecked: "2026-09-23"
  },
  {
    id: "sh39-nmax-v3",
    topBoxId: "shad-sh39",
    topBoxLabel: "SHAD SH39",
    productHref: "/accessories/top-box/sh39",
    modelId: "yamaha-nmax-v3",
    rackCode: "Y0NM14IST",
    rackLabel: "SHAD Top Master Yamaha NMAX Turbo / Neo",
    plateRequirement: "Use the plate included with the SH39 on the bike-specific Top Master fitting.",
    modelYears: "2025-2026",
    marketNote: "The 2025-2026 SHAD catalog names NMAX Turbo / Neo. Confirm that the rack code matches the exact Philippine NMAX variant before purchase.",
    status: "research",
    sourceLabel: "SHAD official Yamaha top-case fitment catalog",
    sourceUrl: "https://www.shad.es/tl/for-your-motorbike/types/Maleta-superior-%28ST%29/YAMAHA/",
    lastChecked: "2026-08-25"
  }
];

export function getTopBoxFitmentsForProduct(topBoxId: string) {
  return topBoxFitments.filter((fitment) => fitment.topBoxId === topBoxId);
}

export function getTopBoxFitmentsForModel(modelId: string) {
  return topBoxFitments.filter((fitment) => fitment.modelId === modelId);
}
