import type { Motorcycle } from "./types";

// Fourth October 2026 keyword-gap wave from the supplied ZigWheels export.
// This wave prioritizes models that still have current official Philippine
// manufacturer pages so commercial intent can land on verified model entities.
const verifiedAt = "2026-10-03";

export const zigwheelsGapWave4_2026: Motorcycle[] = [
  {
    id: "suzuki-gixxer-sf-155",
    alsoKnownAs: ["Suzuki Gixxer SF155", "Gixxer SF 155", "Gixxer SF FI"],
    make: "Suzuki",
    makeSlug: "suzuki",
    model: "GIXXER SF 155",
    slug: "gixxer-sf-155",
    generation: "Current Philippine model",
    category: "Sport touring bike",
    srp: 116900,
    engineCc: 155,
    powerHp: 13.94,
    torqueNm: 14,
    curbWeightKg: 146,
    seatHeightMm: 795,
    fuelTankL: 12,
    fuelConsumptionKmL: 50.2,
    groundClearanceMm: 165,
    frontTire: "100/80-17",
    rearTire: "140/60R-17",
    abs: "No ABS listed on the current Philippine specification; front and rear disc brakes",
    colors: ["Metallic Triton Blue", "Glass Sparkle Black", "Pearl Mira Red"],
    searchVolume: 16370,
    keywordDifficulty: 0,
    sourceLabel: "Suzuki Motorcycles Philippines current GIXXER SF 155 product page",
    sourceUrl: "https://mc.suzuki.com.ph/motorcycles/backbone/gixxer-sf155/",
    verifiedAt,
    freshness: "verified",
    marketStatus: "current",
    marketPriceSourceLabel: "Suzuki Motorcycles Philippines",
    marketPriceSourceUrl: "https://mc.suzuki.com.ph/motorcycles/backbone/gixxer-sf155/",
    marketPriceCheckedAt: verifiedAt,
    priceContext: "Suzuki Motorcycles Philippines currently lists the GIXXER SF 155 at ₱116,900 SRP, subject to dealer pricing.",
    transmission: "Manual",
    summary: "Current 155cc faired Suzuki with 13.94 hp, 14 Nm, 50.2 km/L WMTC fuel economy, 795 mm seat and a 12 L tank."
  },
  {
    id: "suzuki-smash-carb",
    alsoKnownAs: ["Suzuki Smash 115", "Smash 115", "Suzuki Smash Carb"],
    make: "Suzuki",
    makeSlug: "suzuki",
    model: "Smash Carb",
    slug: "smash-carb",
    generation: "Current Philippine model",
    category: "Underbone",
    srp: 64400,
    engineCc: 109.7,
    powerHp: 7.51,
    torqueNm: 9,
    curbWeightKg: 91,
    seatHeightMm: 755,
    fuelTankL: 4.5,
    groundClearanceMm: 153,
    frontTire: "70/90-17",
    rearTire: "80/90-17",
    abs: "No ABS; Drum/Spokes and Disc/Mags variants are offered",
    colors: [],
    searchVolume: 13570,
    keywordDifficulty: 0,
    sourceLabel: "Suzuki Motorcycles Philippines current Smash Carb product page",
    sourceUrl: "https://mc.suzuki.com.ph/motorcycles/underbone/smash-carb/",
    verifiedAt,
    freshness: "verified",
    marketStatus: "current",
    marketPriceHighPhp: 69400,
    marketPriceSourceLabel: "Suzuki Motorcycles Philippines",
    marketPriceSourceUrl: "https://mc.suzuki.com.ph/motorcycles/underbone/smash-carb/",
    marketPriceCheckedAt: verifiedAt,
    priceContext: "Suzuki Philippines lists Smash Carb at ₱64,400 for Drum/Spokes and ₱69,400 for Disc/Mags. Searchers often call this family Smash 115 even though Suzuki's current technical sheet lists 109.7cc actual displacement.",
    transmission: "Manual",
    summary: "Current carbureted Smash underbone with 109.7cc actual displacement, 755 mm seat, 4.5 L tank and two Philippine brake/wheel variants."
  },
  {
    id: "kawasaki-klx150",
    alsoKnownAs: ["Kawasaki KLX 150", "KLX 150"],
    make: "Kawasaki",
    makeSlug: "kawasaki",
    model: "KLX150",
    slug: "klx150",
    generation: "Current Philippine model",
    category: "Dual-sport",
    srp: 134900,
    engineCc: 144,
    powerHp: 11.53,
    torqueNm: 11.3,
    curbWeightKg: 119,
    seatHeightMm: 865,
    fuelTankL: 6.9,
    groundClearanceMm: 295,
    frontTire: "2.75-21",
    rearTire: "4.10-18",
    abs: "No ABS listed; front and rear petal disc brakes",
    colors: [],
    searchVolume: 10050,
    keywordDifficulty: 0,
    sourceLabel: "Kawasaki Leisure Bikes Philippines current KLX150 product and price page",
    sourceUrl: "https://kawasakileisurebikes.ph/motorcycles/dual-purpose/klx150/",
    verifiedAt,
    freshness: "verified",
    marketStatus: "current",
    marketPriceSourceLabel: "Kawasaki Leisure Bikes Philippines",
    marketPriceSourceUrl: "https://kawasakileisurebikes.ph/motorcycles/dual-purpose/klx150/",
    marketPriceCheckedAt: verifiedAt,
    priceContext: "Kawasaki Leisure Bikes Philippines lists the KLX150 at ₱134,900 MSRP, excluding freight and registration fees.",
    transmission: "Manual",
    summary: "Current 144cc Philippine dual-sport with 21/18-inch wheels, 295 mm ground clearance, 865 mm seat and 119 kg curb mass."
  },
  {
    id: "honda-rs125-final-edition",
    alsoKnownAs: ["Honda RS125", "RS125 FI", "Honda RS125 FI"],
    make: "Honda",
    makeSlug: "honda",
    model: "RS125 Final Edition",
    slug: "rs125",
    generation: "2026 Philippine Final Edition",
    category: "Underbone",
    srp: 77000,
    engineCc: 125,
    powerHp: 9.55,
    torqueNm: 9.55,
    curbWeightKg: 104,
    seatHeightMm: 767,
    fuelTankL: 3.9,
    fuelConsumptionKmL: 67.5,
    groundClearanceMm: 135,
    frontTire: "70/90-17",
    rearTire: "80/90-17",
    abs: "No ABS; hydraulic front disc and rear drum",
    colors: ["Matte Axis Gray Metallic", "Pearl Sylvestris Gray"],
    searchVolume: 9900,
    keywordDifficulty: 0,
    sourceLabel: "Honda Philippines 2026 RS125 Final Edition announcement with official RS125 specification sheet",
    sourceUrl: "https://www.hondaph.com/motorcycle/news/honda-releases-its-rs125-final-edition",
    verifiedAt,
    freshness: "verified",
    marketStatus: "current",
    marketPriceSourceLabel: "Honda Philippines",
    marketPriceSourceUrl: "https://www.hondaph.com/motorcycle/news/honda-releases-its-rs125-final-edition",
    marketPriceCheckedAt: verifiedAt,
    priceContext: "Honda Philippines launched the RS125 Final Edition at ₱77,000 and says the limited 2026 model will remain available until March 2028, subject to the announced 20,000-unit run.",
    transmission: "Manual",
    summary: "Current limited-run 125cc RS125 Final Edition with PGM-FI, 67.5 km/L historical WMTC specification, 767 mm seat and ₱77,000 announced SRP."
  },
  {
    id: "suzuki-smash-fi",
    alsoKnownAs: ["Suzuki Smash FI", "Smash Fi 113"],
    make: "Suzuki",
    makeSlug: "suzuki",
    model: "Smash Fi",
    slug: "smash-fi",
    generation: "Current Philippine model",
    category: "Underbone",
    srp: 68400,
    engineCc: 113,
    powerHp: 9.25,
    torqueNm: 9.1,
    curbWeightKg: 94,
    seatHeightMm: 755,
    fuelTankL: 3.7,
    fuelConsumptionKmL: 68,
    groundClearanceMm: 145,
    frontTire: "70/90-17",
    rearTire: "80/90-17",
    abs: "No ABS; Drum/Spokes and Disc/Mags variants are offered",
    colors: [],
    searchVolume: 9090,
    keywordDifficulty: 0,
    sourceLabel: "Suzuki Motorcycles Philippines current Smash Fi product page",
    sourceUrl: "https://mc.suzuki.com.ph/motorcycles/underbone/smash-fi/",
    verifiedAt,
    freshness: "verified",
    marketStatus: "current",
    marketPriceHighPhp: 73400,
    marketPriceSourceLabel: "Suzuki Motorcycles Philippines",
    marketPriceSourceUrl: "https://mc.suzuki.com.ph/motorcycles/underbone/smash-fi/",
    marketPriceCheckedAt: verifiedAt,
    priceContext: "Suzuki Philippines currently lists Smash Fi at ₱68,400 for Drum/Spokes and ₱73,400 for Disc/Mags.",
    transmission: "Manual",
    summary: "Current 113cc fuel-injected Smash with 68 km/L WMTC fuel economy, 94 kg curb mass, 755 mm seat and two Philippine variants."
  },
  {
    id: "suzuki-gixxer-155",
    alsoKnownAs: ["Suzuki Gixxer FI", "Gixxer Fi", "Gixxer 155"],
    make: "Suzuki",
    makeSlug: "suzuki",
    model: "GIXXER 155",
    slug: "gixxer-155",
    generation: "Current Philippine model",
    category: "Naked street bike",
    srp: 106400,
    engineCc: 155,
    powerHp: 13.94,
    torqueNm: 14,
    curbWeightKg: 140,
    seatHeightMm: 795,
    fuelTankL: 12,
    fuelConsumptionKmL: 53.3,
    groundClearanceMm: 160,
    frontTire: "100/80-17",
    rearTire: "140/60R-17",
    abs: "No ABS listed on the current Philippine specification; front and rear disc brakes",
    colors: ["Metallic Triton Blue", "Glass Sparkle Black", "Pearl Mira Red"],
    searchVolume: 9060,
    keywordDifficulty: 0,
    sourceLabel: "Suzuki Motorcycles Philippines current GIXXER 155 product page",
    sourceUrl: "https://mc.suzuki.com.ph/motorcycles/backbone/gixxer-155/",
    verifiedAt,
    freshness: "verified",
    marketStatus: "current",
    marketPriceSourceLabel: "Suzuki Motorcycles Philippines",
    marketPriceSourceUrl: "https://mc.suzuki.com.ph/motorcycles/backbone/gixxer-155/",
    marketPriceCheckedAt: verifiedAt,
    priceContext: "Suzuki Motorcycles Philippines currently lists the GIXXER 155 at ₱106,400 SRP, subject to dealer pricing.",
    transmission: "Manual",
    summary: "Current 155cc naked Suzuki with 13.94 hp, 14 Nm, 53.3 km/L WMTC fuel economy, 795 mm seat and 12 L tank."
  },
  {
    id: "suzuki-burgman-400",
    alsoKnownAs: ["Suzuki Burgman 400", "Burgman400"],
    make: "Suzuki",
    makeSlug: "suzuki",
    model: "Burgman 400",
    slug: "burgman-400",
    generation: "Current Philippine model",
    category: "Maxi scooter",
    srp: 566000,
    engineCc: 400,
    powerHp: 30.04,
    torqueNm: 35,
    curbWeightKg: 218,
    seatHeightMm: 755,
    fuelTankL: 13.5,
    groundClearanceMm: 125,
    frontTire: "120/70-15",
    rearTire: "150/70-13",
    abs: "Standard Suzuki ABS with twin front discs and rear disc",
    colors: ["Metallic Matte Sword Silver"],
    searchVolume: 8780,
    keywordDifficulty: 0,
    sourceLabel: "Suzuki Motorcycles Philippines current Burgman 400 product page",
    sourceUrl: "https://mc.suzuki.com.ph/motorcycles/big-bike/burgman-400/",
    verifiedAt,
    freshness: "verified",
    marketStatus: "current",
    marketPriceSourceLabel: "Suzuki Motorcycles Philippines",
    marketPriceSourceUrl: "https://mc.suzuki.com.ph/motorcycles/big-bike/burgman-400/",
    marketPriceCheckedAt: verifiedAt,
    priceContext: "Suzuki Motorcycles Philippines currently lists the Burgman 400 at ₱566,000 SRP.",
    transmission: "Automatic",
    summary: "Current Philippine 400cc maxi scooter with 30.04 hp, 35 Nm, traction control, ABS, a 755 mm seat and 13.5 L tank."
  },
  {
    id: "suzuki-gixxer-sf250",
    alsoKnownAs: ["Suzuki Gixxer SF 250", "Gixxer SF250"],
    make: "Suzuki",
    makeSlug: "suzuki",
    model: "GIXXER SF250",
    slug: "gixxer-sf250",
    generation: "Current Philippine model",
    category: "Sport bike",
    srp: 192900,
    engineCc: 249,
    powerHp: 26.13,
    torqueNm: 22.6,
    curbWeightKg: 161,
    seatHeightMm: 800,
    fuelTankL: 12,
    fuelConsumptionKmL: 36.6,
    groundClearanceMm: 165,
    frontTire: "110/70-17",
    rearTire: "150/60R-17",
    abs: "Dual-channel ABS with front and rear disc brakes",
    colors: [],
    searchVolume: 7960,
    keywordDifficulty: 0,
    sourceLabel: "Suzuki Motorcycles Philippines current GIXXER SF250 product page",
    sourceUrl: "https://mc.suzuki.com.ph/motorcycles/backbone/gixxer-sf-250/",
    verifiedAt,
    freshness: "verified",
    marketStatus: "current",
    marketPriceSourceLabel: "Suzuki Motorcycles Philippines",
    marketPriceSourceUrl: "https://mc.suzuki.com.ph/motorcycles/backbone/gixxer-sf-250/",
    marketPriceCheckedAt: verifiedAt,
    priceContext: "Suzuki Motorcycles Philippines currently lists the GIXXER SF250 at ₱192,900 SRP, subject to dealer pricing.",
    transmission: "Manual",
    summary: "Current 249cc faired Suzuki with 26.13 hp, 22.6 Nm, six-speed transmission, dual-channel ABS, 800 mm seat and 12 L tank."
  }
];
