import type { Motorcycle } from "./types";

// Fifth October 2026 keyword-gap wave from the supplied ZigWheels export.
// This wave prioritizes strong current Philippine model intent with live
// manufacturer/distributor product pages and avoids thin modifier URLs.
const verifiedAt = "2026-10-03";

export const zigwheelsGapWave5_2026: Motorcycle[] = [
  {
    id: "keeway-cafe-racer-152",
    alsoKnownAs: ["Keeway CR152", "Cafe Racer 152", "Keeway 152"],
    make: "Keeway",
    makeSlug: "keeway",
    model: "Cafe Racer 152",
    slug: "cafe-racer-152",
    generation: "Current Philippine model",
    category: "Cafe racer",
    srp: 69900,
    engineCc: 149,
    powerHp: 11.26,
    torqueNm: 11.1,
    curbWeightKg: 108,
    seatHeightMm: 770,
    fuelTankL: 12.1,
    groundClearanceMm: 160,
    frontTire: "3.00-17",
    rearTire: "110/80-17",
    abs: "No ABS listed; 220 mm front disc and rear drum",
    colors: [],
    searchVolume: 10000,
    keywordDifficulty: 0,
    sourceLabel: "Keeway Philippines current Cafe Racer 152 product page",
    sourceUrl: "https://www.keeway.com/ph-en/products/cafe-racer-152",
    verifiedAt,
    freshness: "verified",
    marketStatus: "current",
    marketPriceSourceLabel: "Keeway Philippines current product page with ZigWheels PH price cross-check",
    marketPriceSourceUrl: "https://www.zigwheels.ph/new-motorcycles/keeway/cafe-racer-152/price",
    marketPriceCheckedAt: verifiedAt,
    priceContext: "Keeway Philippines currently displays a 69,900 price value on the Philippine Cafe Racer 152 product page; ZigWheels Philippines independently lists the same ₱69,900 SRP. Confirm the final dealer quote before purchase.",
    transmission: "Manual",
    summary: "Current 149cc Philippine cafe racer with an 11.26 hp-equivalent published output, 770 mm seat, 12.1 L tank, 17-inch wheels and ₱69,900 current price reference."
  },
  {
    id: "kymco-krv-180",
    alsoKnownAs: ["KYMCO KRV 180", "KRV 180i", "KRV 180 Moto"],
    make: "KYMCO",
    makeSlug: "kymco",
    model: "KRV 180",
    slug: "krv-180",
    generation: "Current Philippine KRV 180 range",
    category: "Sport scooter",
    srp: 179900,
    engineCc: 175.1,
    powerHp: 16.76,
    torqueNm: 15.48,
    curbWeightKg: 147,
    seatHeightMm: 795,
    fuelTankL: 7.2,
    frontTire: "110/70-13",
    rearTire: "130/70-13",
    abs: "Full ABS with traction control on current Philippine KRV 180 Belt and MOTO Chain variants",
    colors: [],
    searchVolume: 3600,
    keywordDifficulty: 0,
    sourceLabel: "KYMCO Philippines current KRV 180 Belt and MOTO Chain product pages",
    sourceUrl: "https://kymco.com.ph/product/krv-180-belt/",
    verifiedAt,
    freshness: "verified",
    marketStatus: "current",
    marketPriceHighPhp: 195900,
    marketPriceSourceLabel: "KYMCO Philippines",
    marketPriceSourceUrl: "https://kymco.com.ph/product/krv-180-moto-chain/",
    marketPriceCheckedAt: verifiedAt,
    priceContext: "KYMCO Philippines currently lists the KRV 180 Belt at ₱179,900 and the KRV 180 MOTO Chain at ₱195,900. Both use the same 175.1cc engine platform with ABS and TCS.",
    transmission: "Automatic",
    summary: "Current 175.1cc Philippine sport-scooter range with ABS, TCS, 13-inch wheels, 795 mm seat and Belt or MOTO Chain configurations."
  },
  {
    id: "kymco-xciting-vs-400",
    alsoKnownAs: ["KYMCO Xciting VS 400", "Xciting VS 400i", "Kymco 400cc scooter"],
    make: "KYMCO",
    makeSlug: "kymco",
    model: "XCITING VS 400 MMC",
    slug: "xciting-vs-400",
    generation: "Current Philippine MMC model",
    category: "Maxi scooter",
    srp: 389900,
    engineCc: 400.1,
    powerHp: 33.52,
    torqueNm: 37.5,
    curbWeightKg: 195,
    seatHeightMm: 805,
    fuelTankL: 12.5,
    frontTire: "120/70-15",
    rearTire: "150/70-14",
    abs: "Bosch ABS with traction control",
    colors: [],
    searchVolume: 2000,
    keywordDifficulty: 0,
    sourceLabel: "KYMCO Philippines current XCITING VS 400 MMC product page",
    sourceUrl: "https://kymco.com.ph/product/xciting-vs-400-mmc/",
    verifiedAt,
    freshness: "verified",
    marketStatus: "current",
    marketPriceSourceLabel: "KYMCO Philippines",
    marketPriceSourceUrl: "https://kymco.com.ph/product/xciting-vs-400-mmc/",
    marketPriceCheckedAt: verifiedAt,
    priceContext: "KYMCO Philippines currently lists the XCITING VS 400 MMC at ₱389,900. Older Xciting 400i and Xciting S 400i searches should be treated as predecessor context rather than copied as current model names.",
    transmission: "Automatic",
    summary: "Current 400.1cc Philippine maxi scooter with roughly 33.5 hp, 37.5 Nm, Bosch ABS, TCS, keyless operation, 805 mm seat and current MMC pricing."
  },
  {
    id: "kymco-like-125-italia",
    alsoKnownAs: ["KYMCO Like 125", "Like 125 Italia", "New Like 125 Italia"],
    make: "KYMCO",
    makeSlug: "kymco",
    model: "New Like 125 Italia",
    slug: "like-125-italia",
    generation: "Current Philippine model",
    category: "Retro scooter",
    srp: 89900,
    engineCc: 124.6,
    powerHp: 9.39,
    torqueNm: 9.5,
    curbWeightKg: 115,
    seatHeightMm: 790,
    fuelTankL: 5.5,
    frontTire: "110/70-12",
    rearTire: "120/70-12",
    abs: "Front and rear disc brakes; the current Philippine product page does not list ABS",
    colors: ["Pearly White", "Light Blue", "Golden"],
    searchVolume: 2000,
    keywordDifficulty: 0,
    sourceLabel: "KYMCO Philippines current New Like 125 Italia product page",
    sourceUrl: "https://kymco.com.ph/product/new-like-125-italia-mmc/",
    verifiedAt,
    freshness: "verified",
    marketStatus: "current",
    marketPriceSourceLabel: "KYMCO Philippines",
    marketPriceSourceUrl: "https://kymco.com.ph/product/new-like-125-italia-mmc/",
    marketPriceCheckedAt: verifiedAt,
    priceContext: "KYMCO Philippines currently lists the New Like 125 Italia at ₱89,900 SRP.",
    transmission: "Automatic",
    summary: "Current 124.6cc retro scooter with CVT, 790 mm seat, 12-inch wheels, dual disc brakes and ₱89,900 official Philippine SRP."
  },
  {
    id: "benelli-302s",
    alsoKnownAs: ["Benelli 302 S", "302S"],
    make: "Benelli",
    makeSlug: "benelli",
    model: "302S",
    slug: "302s",
    generation: "Current Philippine model",
    category: "Naked street bike",
    srp: 222800,
    engineCc: 300,
    powerHp: 37.54,
    torqueNm: 25.6,
    curbWeightKg: 204,
    seatHeightMm: 795,
    fuelTankL: 16,
    groundClearanceMm: 140,
    frontTire: "120/70 ZR17",
    rearTire: "160/60 ZR17",
    abs: "Dual front discs and rear disc; ABS is listed on current-market 302S references",
    colors: [],
    searchVolume: 1800,
    keywordDifficulty: 0,
    sourceLabel: "Benelli Philippines current 302S product and technical specification",
    sourceUrl: "https://www.benelli.com/ph-en/products/302s-2",
    verifiedAt,
    freshness: "verified",
    marketStatus: "current",
    marketPriceSourceLabel: "Benelli Philippines current product value with ZigWheels PH price cross-check",
    marketPriceSourceUrl: "https://www.zigwheels.ph/new-motorcycles/benelli/302-s/price",
    marketPriceCheckedAt: verifiedAt,
    priceContext: "Benelli's Philippine product page displays a 222,800 price value and ZigWheels Philippines independently lists ₱222,800 SRP. Confirm the final dealer quote and exact ABS equipment before purchase.",
    transmission: "Manual",
    summary: "Current 300cc parallel-twin naked bike with roughly 37.5 hp, 25.6 Nm, 795 mm seat, 16 L tank and current ₱222,800 Philippine price reference."
  },
  {
    id: "benelli-rfs-150i",
    alsoKnownAs: ["Benelli RFS150i", "RFS 150i"],
    make: "Benelli",
    makeSlug: "benelli",
    model: "RFS 150i",
    slug: "rfs-150i",
    generation: "Current Philippine model",
    category: "Sport underbone",
    srp: 88800,
    engineCc: 149.8,
    powerHp: 15.15,
    torqueNm: 13.5,
    curbWeightKg: 131,
    seatHeightMm: 787,
    fuelTankL: 4.8,
    groundClearanceMm: 160,
    frontTire: "70/90-17",
    rearTire: "110/70-17",
    abs: "Front and rear disc brakes; Philippine third-party listings conflict on ABS, so verify the exact dealer unit",
    colors: [],
    searchVolume: 1400,
    keywordDifficulty: 0,
    sourceLabel: "Benelli Philippines current RFS 150i product and technical specification",
    sourceUrl: "https://www.benelli.com/ph-en/products/rfs-150i",
    verifiedAt,
    freshness: "verified",
    marketStatus: "current",
    marketPriceSourceLabel: "Benelli Philippines current product value with ZigWheels PH price cross-check",
    marketPriceSourceUrl: "https://www.zigwheels.ph/new-motorcycles/benelli/rfs-150i/price",
    marketPriceCheckedAt: verifiedAt,
    priceContext: "Benelli's Philippine product page displays an 88,800 price value and ZigWheels Philippines lists ₱88,800 SRP. ABS information is inconsistent across Philippine references, so MotoIndex does not assert it without checking the exact dealer unit.",
    transmission: "Manual",
    summary: "Current 149.8cc six-speed sport underbone with roughly 15.2 hp, 13.5 Nm, 787 mm seat, 17-inch wheels and current ₱88,800 Philippine price reference."
  },
  {
    id: "benelli-trk-502x",
    alsoKnownAs: ["Benelli TRK502X", "TRK 502 X", "TRK502X"],
    make: "Benelli",
    makeSlug: "benelli",
    model: "TRK 502 X",
    slug: "trk-502x",
    generation: "Current Philippine model",
    category: "Adventure touring",
    srp: 399000,
    engineCc: 500,
    powerHp: 46.94,
    torqueNm: 46,
    curbWeightKg: 213,
    seatHeightMm: 860,
    fuelTankL: 20,
    groundClearanceMm: 210,
    frontTire: "110/80 R19",
    rearTire: "150/70 R17",
    abs: "ABS with dual front discs and rear disc",
    colors: [],
    searchVolume: 1000,
    keywordDifficulty: 0,
    sourceLabel: "Benelli Philippines current TRK 502 X product and technical specification",
    sourceUrl: "https://www.benelli.com/ph-en/products/trk-502x",
    verifiedAt,
    freshness: "verified",
    marketStatus: "current",
    marketPriceSourceLabel: "Benelli Philippines current product value with ZigWheels PH price cross-check",
    marketPriceSourceUrl: "https://www.zigwheels.ph/new-motorcycles/benelli/trk502x/price",
    marketPriceCheckedAt: verifiedAt,
    priceContext: "Benelli's Philippine product page displays a 399,000 price value and ZigWheels Philippines independently lists ₱399,000 SRP. Confirm the exact model year and dealer quote before purchase.",
    transmission: "Manual",
    summary: "Current 500cc parallel-twin adventure-tourer with roughly 47 hp, 46 Nm, 19/17-inch wheels, ABS, 20 L tank and current ₱399,000 Philippine price reference."
  }
];
