import type { Motorcycle } from "./types";

// Third October 2026 search-gap wave from the supplied ZigWheels keyword export.
// This wave focuses on distinct historical entities with durable owner/used-bike
// intent. Current-model aliases stay on their existing canonical pages.
const verifiedAt = "2026-10-02";

export const zigwheelsGapWave3_2026: Motorcycle[] = [
  {
    id: "honda-pcx150",
    alsoKnownAs: ["Honda PCX 150", "PCX 150"],
    make: "Honda",
    makeSlug: "honda",
    model: "PCX150",
    slug: "pcx150",
    generation: "2018–2019 Philippine PCX150 generation",
    category: "Premium scooter",
    srp: 133900,
    engineCc: 150,
    powerHp: 14.48,
    torqueNm: 13.6,
    curbWeightKg: 131,
    seatHeightMm: 762,
    fuelTankL: 8,
    groundClearanceMm: 137,
    frontTire: "100/80-14",
    rearTire: "120/70-14",
    abs: "Front ABS with rear drum brake",
    colors: ["Red", "Silver"],
    searchVolume: 12210,
    keywordDifficulty: 0,
    sourceLabel: "TopGear Philippines 2019 PCX150 buyer's guide and specification record",
    sourceUrl: "https://www.topgear.com.ph/buyers-guide/motorcycles/honda/pcx150/2019/overview",
    verifiedAt,
    freshness: "verified",
    marketStatus: "previous",
    priceContext: "Historical Philippine starting price of ₱133,900 for the PCX150 generation. Current new-bike shopping belongs on the PCX160 page.",
    transmission: "Automatic",
    successorId: "honda-pcx-160",
    summary: "Previous 150cc Philippine PCX generation with front ABS, an 8 L tank, 14-inch front wheel and historical ₱133,900 price context."
  },
  {
    id: "yamaha-tricity",
    alsoKnownAs: ["Yamaha Tricity 125", "Tricity 125"],
    make: "Yamaha",
    makeSlug: "yamaha",
    model: "Tricity",
    slug: "tricity",
    generation: "Philippine 125cc Tricity launch generation",
    category: "Three-wheel scooter",
    srp: 146000,
    engineCc: 124.8,
    powerHp: 11,
    torqueNm: 10.4,
    curbWeightKg: 152,
    seatHeightMm: 780,
    fuelTankL: 6.6,
    groundClearanceMm: 120,
    frontTire: "90/80-14",
    rearTire: "110/90-12",
    abs: "Unified braking system on the Philippine launch model; no ABS claim stored for this generation",
    colors: ["Matte Red", "White"],
    searchVolume: 11450,
    keywordDifficulty: 0,
    sourceLabel: "Yamaha Tricity Philippine brochure specification",
    sourceUrl: "https://imgcdn.zigwheels.ph/brochures/86/1095/yamaha-tricity.pdf",
    verifiedAt,
    freshness: "verified",
    marketStatus: "discontinued",
    marketPriceSourceLabel: "TopGear Philippines Yamaha Motor Philippines launch coverage",
    marketPriceSourceUrl: "https://www.topgear.com.ph/news/car-news/yamaha-ph-launches-tricity-scooter",
    marketPriceCheckedAt: verifiedAt,
    priceContext: "Historical Philippine launch price of ₱146,000 for the 125cc Tricity. MotoIndex found no current Yamaha Philippines national product-page listing for this generation.",
    transmission: "Automatic",
    summary: "Discontinued Philippine 124.8cc three-wheel scooter with Yamaha's Leaning Multi Wheel layout, a 780 mm seat, 6.6 L tank and historical ₱146,000 launch price."
  },
  {
    id: "honda-cb150r",
    alsoKnownAs: ["Honda CB150R Streetfire", "CB150R Streetfire"],
    make: "Honda",
    makeSlug: "honda",
    model: "CB150R",
    slug: "cb150r",
    generation: "2016 Philippine CB150R Streetfire",
    category: "Naked street bike",
    srp: 116800,
    engineCc: 149.16,
    powerHp: 17,
    torqueNm: 13.8,
    curbWeightKg: 133,
    seatHeightMm: 797,
    fuelTankL: 12,
    groundClearanceMm: 169,
    frontTire: "100/80-17",
    rearTire: "130/70-17",
    abs: "No ABS listed; hydraulic disc brakes front and rear",
    colors: [],
    searchVolume: 7990,
    keywordDifficulty: 0,
    sourceLabel: "Philippine CB150R Streetfire dealer specification with PH owner's-manual cross-check",
    sourceUrl: "https://www.thmmotorcycles.com.ph/viewdetails.php?action=0&id=403&pageNum=11&param=0",
    verifiedAt,
    freshness: "verified",
    marketStatus: "discontinued",
    marketPriceSourceLabel: "Historical Philippine CB150R Streetfire price reference",
    marketPriceSourceUrl: "https://www.zigwheels.ph/compare-motorcycles/honda-cb150r-streetfire-vs-honda-cbr150r-2016-2018",
    marketPriceCheckedAt: verifiedAt,
    priceContext: "Historical Philippine price reference of ₱116,800. Current comparison sources mark the CB150R out of production, so this page is for specifications, ownership and used-bike research.",
    transmission: "Manual",
    summary: "Discontinued Philippine 149.16cc six-speed naked bike with 17 hp, dual disc brakes, a 797 mm seat and a 12 L tank."
  },
  {
    id: "honda-wave-dash-110",
    alsoKnownAs: ["Honda Wave Dash", "Wave Dash 110"],
    make: "Honda",
    makeSlug: "honda",
    model: "Wave Dash 110",
    slug: "wave-dash-110",
    generation: "2013–2015 Philippine Wave Dash generation",
    category: "Underbone",
    srp: 65200,
    engineCc: 110.1,
    powerHp: 8.3,
    torqueNm: 9,
    curbWeightKg: 103,
    seatHeightMm: 669,
    fuelTankL: 3.7,
    fuelConsumptionKmL: 67,
    groundClearanceMm: 147,
    frontTire: "70/90-17",
    rearTire: "80/90-17",
    abs: "No ABS; hydraulic front disc and rear drum",
    colors: ["Victory Red", "Candy Lightning Blue"],
    searchVolume: 6690,
    keywordDifficulty: 0,
    sourceLabel: "Archived Philippine Wave Dash 110 specification and discontinued-model record",
    sourceUrl: "https://www.zigwheels.ph/new-motorcycles/honda/wave-dash-110/standard",
    verifiedAt,
    freshness: "verified",
    marketStatus: "discontinued",
    priceContext: "Historical Philippine price reference of ₱65,200. The Wave Dash 110 is discontinued and should not be treated as a current dealer-new motorcycle.",
    transmission: "Manual",
    summary: "Discontinued 110.1cc Philippine underbone with four-speed transmission, 17-inch wheels, front disc brake and historical ₱65,200 price context."
  }
];
