import type { Motorcycle } from "./types";

// Sixth October 2026 keyword-gap wave from the supplied ZigWheels export.
// Current-market claims use official Philippine manufacturer/distributor pages
// where possible. Historical and retailer-only availability stays explicit.
const verifiedAt = "2026-10-03";

export const zigwheelsGapWave6_2026: Motorcycle[] = [
  {
    id: "honda-dio",
    alsoKnownAs: ["Honda DIO", "Honda Dio 110"],
    make: "Honda",
    makeSlug: "honda",
    model: "DIO",
    slug: "dio",
    generation: "Previous Philippine DIO generation",
    category: "Commuter scooter",
    srp: 49900,
    engineCc: 109,
    powerHp: 7.89,
    torqueNm: 8.91,
    curbWeightKg: 104,
    seatHeightMm: 765,
    fuelTankL: 5.3,
    fuelConsumptionKmL: 58.3,
    groundClearanceMm: 158,
    frontTire: "90/100-10",
    rearTire: "90/100-10",
    abs: "No ABS; front and rear drum brakes",
    colors: ["Candy Jazzy Blue", "Sports Red", "Vibrant Orange"],
    searchVolume: 13030,
    keywordDifficulty: 0,
    sourceLabel: "Honda Philippines historical DIO launch and specification reference",
    sourceUrl: "https://www.hondaph.com/motorcycle/news/the-all-new-dio-a-scooter-youll-surely-love",
    verifiedAt,
    freshness: "verified",
    marketStatus: "discontinued",
    marketPriceHighPhp: 62400,
    marketPriceSourceLabel: "Later Philippine comparison-site historical price reference",
    marketPriceSourceUrl: "https://www.zigwheels.ph/new-motorcycles/honda/dio",
    marketPriceCheckedAt: verifiedAt,
    priceContext: "Honda Philippines launched the DIO at ₱49,900. Later Philippine comparison listings reached roughly ₱62,400, but the model is no longer part of Honda Philippines' current lineup, so this page is for historical specifications, owners and used-bike research.",
    transmission: "Automatic",
    summary: "Discontinued 109cc Philippine DIO with 58.3 km/L published fuel economy, 765 mm seat, 10-inch tubeless tires and historical Philippine pricing."
  },
  {
    id: "bristol-adx-160",
    alsoKnownAs: ["Bristol ADX160", "ADX 160"],
    make: "Bristol",
    makeSlug: "bristol",
    model: "ADX 160",
    slug: "adx-160",
    generation: "Current Philippine model",
    category: "Adventure scooter",
    srp: 178800,
    engineCc: 155.6,
    powerHp: 13,
    torqueNm: 14,
    curbWeightKg: 151,
    seatHeightMm: 790,
    fuelTankL: 11,
    frontTire: "110/80-14",
    rearTire: "130/70-13",
    abs: "ABS",
    colors: [],
    searchVolume: 8200,
    keywordDifficulty: 0,
    sourceLabel: "Bristol Motorcycles Philippines current ADX160 product page with current Philippine specification cross-check",
    sourceUrl: "https://www.bristol-motorcycles.com/adx160",
    verifiedAt,
    freshness: "verified",
    marketStatus: "current",
    marketPriceSourceLabel: "Current Philippine ADX 160 market reference",
    marketPriceSourceUrl: "https://www.zigwheels.ph/new-motorcycles/bristol/adx-160/price",
    marketPriceCheckedAt: verifiedAt,
    priceContext: "Bristol markets the model as ADX 160. Its published bore and stroke calculate to roughly 155.6cc, consistent with current Philippine specification references. Current Philippine comparison listings place the SRP at ₱178,800.",
    transmission: "Automatic",
    summary: "Current Philippine adventure-style scooter with roughly 155.6cc actual displacement, CVT, ABS, 790 mm seat, 11 L tank and current ₱178,800 market reference."
  },
  {
    id: "suzuki-avenis",
    alsoKnownAs: ["Suzuki Avenis 125", "Avenis"],
    make: "Suzuki",
    makeSlug: "suzuki",
    model: "Avenis",
    slug: "avenis",
    generation: "Current Philippine model",
    category: "Commuter scooter",
    srp: 81400,
    engineCc: 124,
    powerHp: 8.58,
    torqueNm: 10,
    curbWeightKg: 106,
    seatHeightMm: 780,
    fuelTankL: 5.2,
    fuelConsumptionKmL: 54,
    groundClearanceMm: 160,
    frontTire: "90/90-12",
    rearTire: "90/100-10",
    abs: "No ABS; front disc and rear drum with Combined Brake System",
    colors: ["Metallic Matte Stellar Blue", "Metallic Matte Black", "Pearl Brilliant White"],
    searchVolume: 8040,
    keywordDifficulty: 0,
    sourceLabel: "Suzuki Motorcycles Philippines current Avenis product page",
    sourceUrl: "https://mc.suzuki.com.ph/motorcycles/scooter/avenis/",
    verifiedAt,
    freshness: "verified",
    marketStatus: "current",
    marketPriceSourceLabel: "Suzuki Motorcycles Philippines",
    marketPriceSourceUrl: "https://mc.suzuki.com.ph/motorcycles/scooter/avenis/",
    marketPriceCheckedAt: verifiedAt,
    priceContext: "Suzuki Motorcycles Philippines currently lists the Avenis at ₱81,400 SRP.",
    transmission: "Automatic",
    summary: "Current 124cc Philippine scooter with 54 km/L WMTC fuel economy, 780 mm seat, Combined Brake System and ₱81,400 official SRP."
  },
  {
    id: "ktm-390-duke",
    alsoKnownAs: ["KTM Duke 390", "390 Duke"],
    make: "KTM",
    makeSlug: "ktm",
    model: "390 Duke",
    slug: "390-duke",
    generation: "Current Philippine 373cc generation",
    category: "Naked street bike",
    srp: 289000,
    engineCc: 373.3,
    powerHp: 43.5,
    torqueNm: 37,
    curbWeightKg: 167,
    seatHeightMm: 830,
    fuelTankL: 13.5,
    frontTire: "110/70-17",
    rearTire: "150/60-17",
    abs: "Bosch dual-channel ABS with Supermoto mode",
    colors: ["Orange", "White"],
    searchVolume: 7930,
    keywordDifficulty: 0,
    sourceLabel: "KTM Philippines current 390 Duke product page with 373.3cc generation technical cross-check",
    sourceUrl: "https://www.ktm.com/en-ph/models/naked-bike/2023-ktm-390-duke.html",
    verifiedAt,
    freshness: "verified",
    marketStatus: "current",
    marketPriceSourceLabel: "Current Philippine 390 Duke price reference",
    marketPriceSourceUrl: "https://www.zigwheels.ph/new-motorcycles/ktm/duke-390/price",
    marketPriceCheckedAt: verifiedAt,
    priceContext: "KTM Philippines currently maintains the 373cc 390 Duke generation in its Philippine model catalog. Current Philippine comparison listings place the price at ₱289,000; confirm the exact model year and dealer quote before purchase.",
    transmission: "Manual",
    summary: "Current Philippine 373.3cc 390 Duke generation with roughly 43.5 hp, 37 Nm, six-speed transmission, Bosch ABS and an 830 mm technical-spec seat height."
  },
  {
    id: "kawasaki-z900-se",
    alsoKnownAs: ["Kawasaki Z900 SE", "Z900SE"],
    make: "Kawasaki",
    makeSlug: "kawasaki",
    model: "Z900 SE",
    slug: "z900-se",
    generation: "Current Philippine model",
    category: "Naked street bike",
    srp: 618000,
    engineCc: 948,
    powerHp: 123.6,
    torqueNm: 98.6,
    curbWeightKg: 213,
    seatHeightMm: 800,
    fuelTankL: 17,
    groundClearanceMm: 145,
    frontTire: "120/70 ZR17",
    rearTire: "180/55 ZR17",
    abs: "ABS with Brembo front braking hardware",
    colors: [],
    searchVolume: 6710,
    keywordDifficulty: 0,
    sourceLabel: "Kawasaki Leisure Bikes Philippines current Z900 SE product and price page",
    sourceUrl: "https://kawasakileisurebikes.ph/motorcycles/sports/z900-se/",
    verifiedAt,
    freshness: "verified",
    marketStatus: "current",
    marketPriceSourceLabel: "Kawasaki Leisure Bikes Philippines",
    marketPriceSourceUrl: "https://kawasakileisurebikes.ph/motorcycles/sports/z900-se/",
    marketPriceCheckedAt: verifiedAt,
    priceContext: "Kawasaki Leisure Bikes Philippines currently lists the Z900 SE at ₱618,000 MSRP, excluding freight and registration fees.",
    transmission: "Manual",
    summary: "Current 948cc Philippine Z900 SE with 123.6 hp, 98.6 Nm, Brembo braking hardware, upgraded suspension, 17 L tank and ₱618,000 official MSRP."
  },
  {
    id: "keeway-superlight-200",
    alsoKnownAs: ["Keeway SuperLight 200", "Superlight 200"],
    make: "Keeway",
    makeSlug: "keeway",
    model: "SuperLight 200",
    slug: "superlight-200",
    generation: "Previous Philippine model",
    category: "Cruiser",
    srp: 88000,
    engineCc: 197,
    powerHp: 12.73,
    torqueNm: 13.9,
    curbWeightKg: 137,
    seatHeightMm: 730,
    fuelTankL: 14,
    groundClearanceMm: 120,
    frontTire: "110/90-16",
    rearTire: "130/90-15",
    abs: "No ABS; front disc and rear drum",
    colors: ["Black", "Red", "Green"],
    searchVolume: 5620,
    keywordDifficulty: 0,
    sourceLabel: "Historical Philippine SuperLight 200 specification and market reference",
    sourceUrl: "https://www.zigwheels.ph/new-motorcycles/keeway/superlight-200",
    verifiedAt,
    freshness: "verified",
    marketStatus: "discontinued",
    priceContext: "Historical Philippine pricing was approximately ₱88,000. Current comparison sources mark the SuperLight 200 out of production, so this page is for historical specifications, owners and used-bike research rather than a current new-bike quote.",
    transmission: "Manual",
    summary: "Discontinued 197cc cruiser with a low 730 mm seat, five-speed gearbox, 14 L tank and historical Philippine pricing retained for owner and used-bike research."
  },
  {
    id: "tvs-ntorq-125",
    alsoKnownAs: ["TVS NTORQ 125", "Ntorq 125 Race Edition"],
    make: "TVS",
    makeSlug: "tvs",
    model: "NTORQ 125",
    slug: "ntorq-125",
    generation: "Philippine-market NTORQ 125",
    category: "Sport scooter",
    srp: 71900,
    engineCc: 124.8,
    powerHp: 9.39,
    torqueNm: 10.6,
    curbWeightKg: 111,
    seatHeightMm: 770,
    fuelTankL: 5.8,
    groundClearanceMm: 155,
    frontTire: "100/80-12",
    rearTire: "110/80-12",
    abs: "No ABS claim for the Philippine reference; 220 mm front disc with SBT and 130 mm rear drum",
    colors: ["Matte Red", "Metallic Blue", "Metallic Gray"],
    searchVolume: 7120,
    keywordDifficulty: 0,
    sourceLabel: "TVS Motor Philippine NTORQ launch history with current technical specification",
    sourceUrl: "https://www.tvsmotor.com/media/press-release/tvs-motor-company-launches-tvs-apacherr-310-and-tvs-ntorq-125-in-the-philippines",
    verifiedAt,
    freshness: "verified",
    marketStatus: "uncertain",
    marketPriceSourceLabel: "Premiumbikes Philippines local retailer listing",
    marketPriceSourceUrl: "https://premiumbikes.ph/product/tvs-ntorq-125-2/",
    marketPriceCheckedAt: verifiedAt,
    priceContext: "TVS officially launched the NTORQ 125 in the Philippines and later introduced the Race Edition. A Philippine retailer lists ₱71,900 but currently shows the unit sold out, so MotoIndex treats present-day national availability and pricing as needing verification.",
    transmission: "Automatic",
    summary: "124.8cc Philippine-market sport scooter with 12-inch wheels, SBT braking, 155 mm ground clearance and local retailer pricing that should be rechecked before purchase."
  }
];
