import type { Motorcycle } from "./types";

// October 2026 expansion based on uncovered Philippine search demand from the
// ZigWheels organic-keyword export supplied on 2026-10-02.
// searchVolume stores the clean primary keyword volume from that export, not
// an aggregate of overlapping keyword variants. Historical models remain
// explicitly marked previous/discontinued instead of being presented as current.
const verifiedAt = "2026-10-02";

export const zigwheelsGapExpansion2026: Motorcycle[] = [
  {
    id: "yamaha-mio-sporty",
    alsoKnownAs: ["Mio Sporty", "Yamaha Mio Sporty Euro 3"],
    make: "Yamaha",
    makeSlug: "yamaha",
    model: "Mio Sporty",
    slug: "mio-sporty",
    generation: "Philippine Euro 3 dealer-inventory model",
    category: "Commuter scooter",
    srp: 73900,
    engineCc: 114,
    powerHp: 7.6,
    torqueNm: 7.2,
    curbWeightKg: 94,
    seatHeightMm: 745,
    fuelTankL: 4.1,
    groundClearanceMm: 125,
    frontTire: "70/90-14",
    rearTire: "80/90-14",
    abs: "No ABS listed; hydraulic front disc and mechanical rear drum",
    colors: ["Cyan", "Magenta", "Matte Black", "Matte Blue"],
    searchVolume: 17000,
    keywordDifficulty: 0,
    sourceLabel: "Motortrade Philippines current Mio Sporty Euro 3 dealer listing with Wheeltek cross-check",
    sourceUrl: "https://motortrade.com.ph/motorcycles/yamaha-mio-sporty-euro-3/",
    verifiedAt,
    freshness: "verified",
    marketStatus: "uncertain",
    marketPriceSourceLabel: "Wheeltek Philippines",
    marketPriceSourceUrl: "https://wheeltek.com.ph/vehicles/mio-sporty/",
    marketPriceCheckedAt: verifiedAt,
    priceContext: "Motortrade and Wheeltek both list the Mio Sporty at ₱73,900 in 2026. MotoIndex treats national-model status as uncertain because dealer inventory remains visible while the current Yamaha main-line catalog status was not independently confirmed.",
    transmission: "Automatic",
    summary: "Philippine dealer-listed 114cc automatic Mio Sporty with a 745 mm seat, 4.1 L tank and historical/current-inventory search demand kept separate from newer Mio models."
  },
  {
    id: "yamaha-yzf-r15-v3",
    alsoKnownAs: ["Yamaha R15", "R15 V3", "YZF R15 V3"],
    make: "Yamaha",
    makeSlug: "yamaha",
    model: "YZF-R15 V3",
    slug: "yzf-r15-v3",
    generation: "Previous Philippine YZF-R15 generation",
    category: "Sport bike",
    srp: 164000,
    engineCc: 155,
    powerHp: 19,
    torqueNm: 14.7,
    curbWeightKg: 137,
    seatHeightMm: 815,
    fuelTankL: 11,
    groundClearanceMm: 170,
    frontTire: "100/80-17",
    rearTire: "140/70-17",
    abs: "Front and rear disc brakes; ABS was not listed for this Philippine generation",
    colors: ["Black", "Race Blue"],
    searchVolume: 11000,
    keywordDifficulty: 40,
    sourceLabel: "Archived Philippine Yamaha YZF-R15 V3 specification and price record",
    sourceUrl: "https://www.zigwheels.ph/new-motorcycles/yamaha/yzf-r15/standard",
    verifiedAt,
    freshness: "verified",
    marketStatus: "previous",
    priceContext: "Historical Philippine YZF-R15 price reference. This generation is discontinued; current Yamaha sport-bike research should also check the YZF-R15M.",
    transmission: "Manual",
    successorId: "yamaha-yzf-r15m",
    summary: "Previous 155cc YZF-R15 generation with a six-speed manual gearbox, 815 mm seat and historical ₱164,000 Philippine price reference."
  },
  {
    id: "yamaha-sniper-150",
    alsoKnownAs: ["Sniper 150", "Sniper 150 MXi"],
    make: "Yamaha",
    makeSlug: "yamaha",
    model: "Sniper 150",
    slug: "sniper-150",
    generation: "Previous Philippine Sniper generation",
    category: "Sport underbone",
    srp: 99800,
    engineCc: 149.7,
    powerHp: 15.4,
    torqueNm: 13.8,
    curbWeightKg: 118,
    seatHeightMm: 780,
    fuelTankL: 4.2,
    groundClearanceMm: 155,
    frontTire: "90/80-17",
    rearTire: "120/70-17",
    abs: "No ABS listed; hydraulic single disc brakes front and rear",
    colors: [],
    searchVolume: 8600,
    keywordDifficulty: 0,
    sourceLabel: "TopGear Philippines 2019 Sniper 150 road test and specification reference",
    sourceUrl: "https://www.topgear.com.ph/moto-sapiens/motorcycle-review/first-ride-2019-yamaha-sniper-150-a3853-20190422",
    verifiedAt,
    freshness: "verified",
    marketStatus: "previous",
    priceContext: "Historical ₱99,800 Philippine price for the Sniper 150 generation. The current successor in MotoIndex is the Sniper 155.",
    transmission: "Manual",
    successorId: "yamaha-sniper-155",
    summary: "Previous 149.7cc Philippine Sniper generation with 15.4 hp, a five-speed gearbox and strong owner-search demand that remains distinct from the current Sniper 155."
  },
  {
    id: "kawasaki-ninja-zx-6r",
    alsoKnownAs: ["Kawasaki ZX-6R", "ZX6R", "Ninja ZX6R"],
    make: "Kawasaki",
    makeSlug: "kawasaki",
    model: "Ninja ZX-6R",
    slug: "ninja-zx-6r",
    generation: "Current Philippine model",
    category: "Super sport",
    srp: 707000,
    engineCc: 636,
    powerHp: 122.03,
    torqueNm: 68,
    curbWeightKg: 198,
    seatHeightMm: 830,
    fuelTankL: 17,
    frontTire: "120/70 ZR17",
    rearTire: "180/55 ZR17",
    abs: "Kawasaki Intelligent anti-lock Brake System (KIBS)",
    colors: [],
    searchVolume: 2700,
    keywordDifficulty: 24,
    sourceLabel: "Kawasaki Leisure Bikes Philippines current Ninja ZX-6R model and specification",
    sourceUrl: "https://kawasakileisurebikes.ph/motorcycles/supersports/ninja-zx-6r/",
    verifiedAt,
    freshness: "verified",
    marketStatus: "current",
    marketPriceSourceLabel: "Kawasaki Leisure Bikes Philippines",
    marketPriceSourceUrl: "https://kawasakileisurebikes.ph/motorcycles/supersports/ninja-zx-6r/",
    marketPriceCheckedAt: verifiedAt,
    priceContext: "Kawasaki Leisure Bikes Philippines lists the Ninja ZX-6R at ₱707,000 MSRP, excluding freight and other regional charges.",
    transmission: "Manual",
    summary: "Current 636cc Philippine Ninja supersport with 122.03 hp, KIBS, a 17 L tank, 830 mm seat and published ₱707,000 MSRP."
  },
  {
    id: "suzuki-hayabusa",
    alsoKnownAs: ["Suzuki GSX1300R Hayabusa", "GSX1300R"],
    make: "Suzuki",
    makeSlug: "suzuki",
    model: "Hayabusa",
    slug: "hayabusa",
    generation: "Current Philippine model",
    category: "Hyper sport",
    srp: 1235000,
    engineCc: 1340,
    powerHp: 187,
    torqueNm: 150,
    curbWeightKg: 262,
    seatHeightMm: 800,
    fuelTankL: 20,
    groundClearanceMm: 125,
    frontTire: "120/70ZR17",
    rearTire: "190/50ZR17",
    abs: "ABS-equipped Brembo Stylema front brakes and Nissin rear brake",
    colors: [],
    searchVolume: 900,
    keywordDifficulty: 0,
    sourceLabel: "Suzuki Philippines current Hayabusa product page and specification",
    sourceUrl: "https://mc.suzuki.com.ph/motorcycles/big-bike/hayabusa/",
    verifiedAt,
    freshness: "verified",
    marketStatus: "current",
    marketPriceSourceLabel: "Suzuki Philippines",
    marketPriceSourceUrl: "https://mc.suzuki.com.ph/motorcycles/big-bike/hayabusa/",
    marketPriceCheckedAt: verifiedAt,
    priceContext: "Suzuki Philippines lists the current Hayabusa at ₱1,235,000 SRP.",
    transmission: "Manual",
    summary: "Current Philippine 1,340cc Hayabusa with roughly 187 hp from Suzuki's published 139.44 kW figure, 150 Nm, a 20 L tank and ABS-equipped braking."
  },
  {
    id: "honda-xr150l",
    alsoKnownAs: ["Honda XR150L", "XR 150L"],
    make: "Honda",
    makeSlug: "honda",
    model: "XR150L",
    slug: "xr150l",
    generation: "2025 Philippine model",
    category: "Dual-sport",
    srp: 97900,
    engineCc: 149,
    powerHp: 11.7,
    torqueNm: 12.1,
    curbWeightKg: 130,
    seatHeightMm: 825,
    fuelTankL: 12,
    fuelConsumptionKmL: 36.7,
    groundClearanceMm: 245,
    frontTire: "90/90-19",
    rearTire: "110/90-17",
    abs: "No ABS listed; front disc and rear drum",
    colors: [],
    searchVolume: 800,
    keywordDifficulty: 0,
    sourceLabel: "Honda Philippines 2025 XR150L launch and specification reference",
    sourceUrl: "https://www.hondaph.com/motorcycle/news/honda-philippines-unleashes-power-and-innovation-at-the-action-packed-inside-racing-bikefest-2025",
    verifiedAt,
    freshness: "verified",
    marketStatus: "current",
    marketPriceHighPhp: 98500,
    marketPriceSourceLabel: "Guanzon Merchandising Corporation current XR150L dealer listing",
    marketPriceSourceUrl: "https://www.guanzongroup.com.ph/product/xr150l/",
    marketPriceCheckedAt: verifiedAt,
    priceContext: "Honda Philippines launched the XR150L at ₱97,900 in March 2025. A current Guanzon dealer listing shows ₱98,500, so confirm the branch quote before purchase.",
    transmission: "Manual",
    summary: "Current Philippine 149cc dual-sport with a 19/17-inch wheel setup, 245 mm ground clearance, 825 mm seat and large 12 L tank."
  },
  {
    id: "yamaha-mt-03",
    alsoKnownAs: ["Yamaha MT03", "MT03"],
    make: "Yamaha",
    makeSlug: "yamaha",
    model: "MT-03",
    slug: "mt-03",
    generation: "Current Philippine dealer model",
    category: "Naked street bike",
    srp: 289000,
    engineCc: 321,
    powerHp: 41.4,
    torqueNm: 29.6,
    curbWeightKg: 168,
    seatHeightMm: 780,
    fuelTankL: 14,
    groundClearanceMm: 160,
    frontTire: "110/70R17",
    rearTire: "140/70R17",
    abs: "ABS-equipped current Philippine dealer model",
    colors: ["Midnight Black", "Ice Storm"],
    searchVolume: 1000,
    keywordDifficulty: 3,
    sourceLabel: "Guanzon Merchandising Corporation current Yamaha MT-03 dealer specification",
    sourceUrl: "https://www.guanzongroup.com.ph/product/mt-03/",
    verifiedAt,
    freshness: "verified",
    marketStatus: "current",
    marketPriceSourceLabel: "Guanzon Merchandising Corporation",
    marketPriceSourceUrl: "https://www.guanzongroup.com.ph/product/mt-03/",
    marketPriceCheckedAt: verifiedAt,
    priceContext: "Current Guanzon dealer reference lists the Yamaha MT-03 at ₱289,000; branch pricing can change.",
    transmission: "Manual",
    summary: "Current Philippine dealer-listed 321cc MT-03 with 41.4 hp, ABS, a 780 mm seat, 168 kg curb weight and 14 L tank."
  },
  {
    id: "yamaha-mt-09",
    alsoKnownAs: ["Yamaha MT09", "MT09"],
    make: "Yamaha",
    makeSlug: "yamaha",
    model: "MT-09",
    slug: "mt-09",
    generation: "Current Philippine model",
    category: "Naked street bike",
    srp: 799000,
    engineCc: 890,
    powerHp: 117,
    torqueNm: 93,
    curbWeightKg: 189,
    seatHeightMm: 825,
    fuelTankL: 14,
    fuelConsumptionKmL: 20,
    groundClearanceMm: 140,
    frontTire: "120/70 ZR17",
    rearTire: "180/55 ZR17",
    abs: "ABS with dual front disc and rear disc brakes",
    colors: ["Tech Black", "Ice Fluo"],
    searchVolume: 1000,
    keywordDifficulty: 4,
    sourceLabel: "Current Philippine MT-09 price/specification listing with Yamaha Philippines after-sales model support cross-check",
    sourceUrl: "https://www.zigwheels.ph/new-motorcycles/yamaha/mt-09/specifications",
    verifiedAt,
    freshness: "verified",
    marketStatus: "current",
    marketPriceSourceLabel: "Current Philippine MT-09 price listing",
    marketPriceSourceUrl: "https://www.zigwheels.ph/new-motorcycles/yamaha/mt-09/price",
    marketPriceCheckedAt: verifiedAt,
    priceContext: "Current Philippine reference lists the Yamaha MT-09 at ₱799,000. Yamaha Philippines after-sales materials also list MT-09 support.",
    transmission: "Manual",
    summary: "Current 890cc Philippine MT-09 with 117 hp, 93 Nm, ABS, a 189 kg curb weight, 825 mm seat and 14 L tank."
  },
  {
    id: "honda-rs150r",
    alsoKnownAs: ["Honda RS 150R", "RS150R", "RS 150"],
    make: "Honda",
    makeSlug: "honda",
    model: "RS150R",
    slug: "rs150r",
    generation: "Previous Philippine RS150R generation",
    category: "Sport underbone",
    srp: 97300,
    engineCc: 149.76,
    powerHp: 15.42,
    torqueNm: 13.5,
    curbWeightKg: 119,
    seatHeightMm: 786,
    fuelTankL: 4.5,
    groundClearanceMm: 149,
    frontTire: "90/80-17",
    rearTire: "120/70-17",
    abs: "No ABS listed for the Philippine RS150R generation; hydraulic disc brakes front and rear",
    colors: ["Valiant Red", "Matte Gunpowder Black Metallic"],
    searchVolume: 1000,
    keywordDifficulty: 0,
    sourceLabel: "Honda Philippines historical RS150R reference with contemporary Philippine specification cross-check",
    sourceUrl: "https://www.hondaph.com/motorcycle/news/honda-ph-celebrates-one-dream-showcases-latest-models-in-the-riders-convention-2018-visayas-leg",
    verifiedAt,
    freshness: "verified",
    marketStatus: "discontinued",
    marketPriceSourceLabel: "Historical Philippine price/specification reference",
    marketPriceSourceUrl: "https://www.topgear.com.ph/buyers-guide/motorcycles/honda/rs150r/2019/specs",
    marketPriceCheckedAt: verifiedAt,
    priceContext: "Historical Philippine RS150R price reference. The model is discontinued, so this page preserves owner and used-market research rather than presenting the price as a current SRP.",
    transmission: "Manual",
    summary: "Discontinued Philippine 150cc sport underbone with a six-speed manual gearbox; retained for strong price, specs and owner-research demand."
  },
  {
    id: "honda-scoopy",
    alsoKnownAs: ["Honda Scoopy 110", "Scoopy"],
    make: "Honda",
    makeSlug: "honda",
    model: "Scoopy",
    slug: "scoopy",
    generation: "Historical Philippine-market Scoopy",
    category: "Retro scooter",
    srp: 69800,
    engineCc: 110,
    powerHp: 8.1,
    torqueNm: 8.27,
    curbWeightKg: 96,
    seatHeightMm: 744,
    fuelTankL: 4.2,
    fuelConsumptionKmL: 59,
    groundClearanceMm: 150,
    frontTire: "80/90-14",
    rearTire: "90/90-14",
    abs: "No ABS listed; front disc and rear drum",
    colors: ["Blue Crystal", "Red", "Black", "White", "Gray", "Orange", "Pink", "Silver Black"],
    searchVolume: 2300,
    keywordDifficulty: 7,
    sourceLabel: "Historical Philippine Honda Scoopy price and specification record",
    sourceUrl: "https://www.kamote.ph/motorcycle/honda-scoopy",
    verifiedAt,
    freshness: "verified",
    marketStatus: "discontinued",
    priceContext: "Historical Philippine price reference only. MotoIndex found no current Honda Philippines Scoopy catalog listing for this update.",
    transmission: "Automatic",
    summary: "Historical 110cc Philippine Scoopy retained for price, specification and ownership searches; it is not presented as a current Honda Philippines model."
  },
  {
    id: "honda-cbr500r",
    alsoKnownAs: ["Honda CBR 500R", "CBR 500R"],
    make: "Honda",
    makeSlug: "honda",
    model: "CBR500R",
    slug: "cbr500r",
    generation: "Philippine 2021-generation reference",
    category: "Sport bike",
    srp: 364000,
    engineCc: 471,
    powerHp: 46.9,
    torqueNm: 43.2,
    curbWeightKg: 192,
    seatHeightMm: 789,
    fuelTankL: 17.1,
    fuelConsumptionKmL: 28.6,
    groundClearanceMm: 130,
    frontTire: "120/70-17",
    rearTire: "160/60-17",
    abs: "2-channel ABS",
    colors: ["Grand Prix Red", "Matte Gunpowder Black Metallic"],
    searchVolume: 1300,
    keywordDifficulty: 12,
    sourceLabel: "Honda Philippines CBR500R launch and specification reference",
    sourceUrl: "https://www.hondaph.com/big-bike/news/the-all-new-cbr500r-arrives-in-ph",
    verifiedAt,
    freshness: "verified",
    marketStatus: "uncertain",
    marketPriceHighPhp: 389000,
    marketPriceSourceLabel: "Honda DES current dealer listing",
    marketPriceSourceUrl: "https://hondades.com/product/cbr150rk/",
    marketPriceCheckedAt: verifiedAt,
    priceContext: "Honda Philippines launched this CBR500R generation at ₱364,000. A current Honda dealer listing shows ₱389,000, but MotoIndex has not confirmed current national-catalog status, so availability should be checked before purchase.",
    transmission: "Manual",
    summary: "471cc Philippine CBR500R reference with 2-channel ABS, 28.6 km/L published fuel economy, a 789 mm seat and current dealer inventory evidence."
  }
];
