import type { Motorcycle } from "./types";

// Second October 2026 search-gap wave from the supplied ZigWheels keyword export.
// Dealer-visible models that are not confirmed on a current manufacturer catalogue
// stay "uncertain"; discontinued models keep historical pricing explicit.
const verifiedAt = "2026-10-02";

export const zigwheelsGapWave2_2026: Motorcycle[] = [
  {
    id: "suzuki-gsx-r150",
    alsoKnownAs: ["Suzuki GSXR150", "GSX R150"],
    make: "Suzuki",
    makeSlug: "suzuki",
    model: "GSX-R150",
    slug: "gsx-r150",
    generation: "Philippine dealer-listed GSX-R150",
    category: "Sport bike",
    srp: 156224,
    engineCc: 147.3,
    powerHp: 18.9,
    torqueNm: 14,
    curbWeightKg: 131,
    seatHeightMm: 785,
    fuelTankL: 11,
    groundClearanceMm: 160,
    frontTire: "90/80-17",
    rearTire: "130/70-17",
    abs: "No ABS listed; front and rear disc brakes",
    colors: ["MotoGP Blue", "Black / Red"],
    searchVolume: 10440,
    keywordDifficulty: 0,
    sourceLabel: "Motortrade Philippines current GSX-R150 dealer listing with Suzuki Philippines launch specification cross-check",
    sourceUrl: "https://motortrade.com.ph/motorcycles/suzuki-gsx-r150/",
    verifiedAt,
    freshness: "verified",
    marketStatus: "uncertain",
    marketPriceSourceLabel: "Suzuki Philippines historical launch reference",
    marketPriceSourceUrl: "https://mc.suzuki.com.ph/suzuki-philippines-in-full-force-during-motorsiklo-xklusibos-8th-anniversary-with-the-royal-arrival-of-its-news-products/",
    marketPriceCheckedAt: verifiedAt,
    priceContext: "Motortrade currently displays ₱156,224 for the GSX-R150, close to Suzuki Philippines' historical ₱156,000 launch price. Confirm current model year, branch stock and final quote because MotoIndex has not confirmed a current Suzuki national-catalog listing.",
    transmission: "Manual",
    summary: "147.3cc liquid-cooled six-speed sport bike with 18.9 hp, 14 Nm, 785 mm seat, 11 L tank and current Philippine dealer visibility."
  },
  {
    id: "suzuki-gsx-s150",
    alsoKnownAs: ["Suzuki GSXS150", "GSX S150"],
    make: "Suzuki",
    makeSlug: "suzuki",
    model: "GSX-S150",
    slug: "gsx-s150",
    generation: "Philippine dealer-listed GSX-S150",
    category: "Naked street bike",
    srp: 112800,
    engineCc: 147.3,
    powerHp: 18.9,
    torqueNm: 14,
    curbWeightKg: 130,
    seatHeightMm: 785,
    fuelTankL: 11,
    groundClearanceMm: 155,
    frontTire: "90/80-17",
    rearTire: "130/70-17",
    abs: "No ABS listed; front and rear disc brakes",
    colors: ["MotoGP Blue", "Black", "Silver"],
    searchVolume: 8640,
    keywordDifficulty: 0,
    sourceLabel: "Motortrade Philippines current GSX-S150 dealer listing with Suzuki Philippines specification cross-check",
    sourceUrl: "https://suzuki.motortrade.com.ph/motorcycles/suzuki-gsx-s150/",
    verifiedAt,
    freshness: "verified",
    marketStatus: "uncertain",
    marketPriceHighPhp: 124800,
    marketPriceSourceLabel: "Motortrade Philippines",
    marketPriceSourceUrl: "https://suzuki.motortrade.com.ph/motorcycles/suzuki-gsx-s150/",
    marketPriceCheckedAt: verifiedAt,
    priceContext: "The current Motortrade GSX-S150 page contains both ₱112,800 and ₱124,800 figures. MotoIndex preserves that discrepancy as a range and recommends confirming the exact branch quote and model code before purchase.",
    transmission: "Manual",
    summary: "147.3cc naked GSX sibling with 18.9 hp, 14 Nm, 785 mm seat, 130 kg wet weight and current Philippine dealer inventory evidence."
  },
  {
    id: "suzuki-skydrive-crossover",
    alsoKnownAs: ["Suzuki SkyDrive Crossover", "Skydrive Crossover 113"],
    make: "Suzuki",
    makeSlug: "suzuki",
    model: "Skydrive Crossover",
    slug: "skydrive-crossover",
    generation: "Current Philippine model",
    category: "Dual-purpose scooter",
    srp: 73900,
    engineCc: 113,
    powerHp: 9.0,
    torqueNm: 8.7,
    curbWeightKg: 94,
    seatHeightMm: 740,
    fuelTankL: 3.6,
    groundClearanceMm: 150,
    frontTire: "80/90-14",
    rearTire: "90/90-14",
    abs: "No ABS listed; front disc and rear drum",
    colors: ["Pearl Ash Blue", "Strong Red", "Solid Black"],
    searchVolume: 8440,
    keywordDifficulty: 0,
    sourceLabel: "Suzuki Philippines 2025 Skydrive Crossover price reference with current Motortrade specification cross-check",
    sourceUrl: "https://mc.suzuki.com.ph/suzuki-does-the-classiest-off-road-adventure-with-dirty-business-vi/",
    verifiedAt,
    freshness: "verified",
    marketStatus: "current",
    marketPriceSourceLabel: "Motortrade Philippines",
    marketPriceSourceUrl: "https://motortrade.com.ph/motorcycles/suzuki-skydrive-crossover/",
    marketPriceCheckedAt: verifiedAt,
    priceContext: "Suzuki Philippines referenced the Skydrive Crossover at ₱73,900 and Motortrade currently lists the same ₱73,900 SRP with an indicative financing example.",
    transmission: "Automatic",
    summary: "Current 113cc automatic dual-purpose scooter with 94 kg curb weight, 740 mm seat, 150 mm ground clearance and 14-inch tubeless tires."
  },
  {
    id: "yamaha-xtz-125",
    alsoKnownAs: ["Yamaha XTZ125", "XTZ125"],
    make: "Yamaha",
    makeSlug: "yamaha",
    model: "XTZ 125",
    slug: "xtz-125",
    generation: "Philippine dealer-listed XTZ125",
    category: "Dual-sport",
    srp: 89900,
    engineCc: 124,
    powerHp: 10.1,
    torqueNm: 9.9,
    curbWeightKg: 118,
    seatHeightMm: 840,
    fuelTankL: 11,
    groundClearanceMm: 260,
    frontTire: "80/90-21",
    rearTire: "110/80-18",
    abs: "No ABS listed; front disc and rear drum",
    colors: [],
    searchVolume: 9580,
    keywordDifficulty: 0,
    sourceLabel: "Wheeltek Philippines current XTZ 125 dealer specification with Yamaha Philippines after-sales model support",
    sourceUrl: "https://wheeltek.com.ph/vehicles/xtz-125/",
    verifiedAt,
    freshness: "verified",
    marketStatus: "uncertain",
    marketPriceSourceLabel: "Wheeltek Philippines",
    marketPriceSourceUrl: "https://wheeltek.com.ph/vehicles/xtz-125/",
    marketPriceCheckedAt: verifiedAt,
    priceContext: "Wheeltek currently lists the XTZ 125 from ₱89,900. Yamaha Philippines after-sales material still names XTZ 125, but MotoIndex has not confirmed a current Yamaha national product-page listing, so verify branch stock and model year.",
    transmission: "Manual",
    summary: "Dealer-listed 124cc dual-sport with 21/18-inch wheels, 260 mm ground clearance, 840 mm seat, 118 kg curb weight and an 11 L tank."
  },
  {
    id: "honda-zoomer-x",
    alsoKnownAs: ["Honda Zoomer X", "Zoomer X"],
    make: "Honda",
    makeSlug: "honda",
    model: "Zoomer-X",
    slug: "zoomer-x",
    generation: "Previous Philippine Zoomer-X generation",
    category: "Lifestyle scooter",
    srp: 93900,
    engineCc: 108.2,
    powerHp: 8.68,
    torqueNm: 9.3,
    curbWeightKg: 106,
    seatHeightMm: 763.5,
    fuelTankL: 4.4,
    groundClearanceMm: 135,
    frontTire: "100/90-12",
    rearTire: "110/90-12",
    abs: "Combined Brake System (CBS); no ABS listed",
    colors: ["Marigold Yellow", "Crypton Silver Metallic"],
    searchVolume: 9580,
    keywordDifficulty: 0,
    sourceLabel: "TopGear Philippines coverage of Honda Philippines' fuel-injected Zoomer-X launch",
    sourceUrl: "https://www.topgear.com.ph/news/car-news/honda-launches-greener-generation-s-scooters",
    verifiedAt,
    freshness: "verified",
    marketStatus: "discontinued",
    priceContext: "Historical ₱93,900 Philippine launch price. Zoomer-X is not part of Honda Philippines' current 2026 core lineup, so use this page for historical specs and used-bike research rather than a new-bike SRP.",
    transmission: "Automatic",
    summary: "Discontinued 108.2cc lifestyle scooter with 12-inch tires, 763.5 mm seat and historical Philippine pricing retained for owner and used-market research."
  },
  {
    id: "yamaha-sight",
    alsoKnownAs: ["Yamaha Sight 115", "Sight 115"],
    make: "Yamaha",
    makeSlug: "yamaha",
    model: "Sight",
    slug: "sight",
    generation: "Previous Philippine Sight 115 generation",
    category: "Underbone",
    srp: 59900,
    engineCc: 114,
    powerHp: 8.58,
    torqueNm: 9.5,
    curbWeightKg: 96,
    seatHeightMm: 775,
    fuelTankL: 4,
    groundClearanceMm: 155,
    frontTire: "70/90-17",
    rearTire: "80/90-17",
    abs: "No ABS listed; front disc and rear drum on cast-wheel variant",
    colors: ["Black Raven", "Red Metallic", "Yellow Hornet"],
    searchVolume: 8600,
    keywordDifficulty: 0,
    sourceLabel: "Philippine Yamaha Sight launch specification archived by Motorcycle Philippines",
    sourceUrl: "https://www.motorcyclephilippines.com/yamaha/yamaha-sight/",
    verifiedAt,
    freshness: "verified",
    marketStatus: "discontinued",
    marketPriceHighPhp: 62900,
    marketPriceSourceLabel: "Historical Philippine Sight price range",
    marketPriceSourceUrl: "https://www.zigwheels.ph/new-motorcycles/yamaha/sight/price",
    marketPriceCheckedAt: verifiedAt,
    priceContext: "Historical Philippine pricing was ₱59,900 for spoke wheels and ₱62,900 for the cast-wheel variant. Current comparison listings mark the Sight discontinued.",
    summary: "Discontinued 114cc fuel-injected underbone with a four-speed semi-automatic gearbox, 775 mm seat and 96 kg curb weight."
  },
  {
    id: "yamaha-sz",
    alsoKnownAs: ["Yamaha SZ16", "Yamaha SZ 150"],
    make: "Yamaha",
    makeSlug: "yamaha",
    model: "SZ",
    slug: "sz",
    generation: "Previous Philippine SZ generation",
    category: "Standard street bike",
    srp: 73400,
    engineCc: 149.3,
    powerHp: 11.9,
    torqueNm: 12.8,
    curbWeightKg: 133,
    seatHeightMm: 800,
    fuelTankL: 14,
    groundClearanceMm: 165,
    frontTire: "2.75-17",
    rearTire: "100/90-17",
    abs: "No ABS listed; front disc and rear drum",
    colors: ["Black", "Red", "Green"],
    searchVolume: 7440,
    keywordDifficulty: 0,
    sourceLabel: "Archived Philippine Yamaha SZ specification with Yamaha Philippines after-sales model support",
    sourceUrl: "https://www.zigwheels.ph/new-motorcycles/yamaha/sz/standard",
    verifiedAt,
    freshness: "verified",
    marketStatus: "discontinued",
    priceContext: "Historical Philippine SZ price reference of ₱73,400. Current comparison sources mark this generation out of production, while Yamaha Philippines still references SZ in after-sales material.",
    transmission: "Manual",
    summary: "Discontinued 149.3cc five-speed standard motorcycle with a large 14 L tank, 800 mm seat and 133 kg curb weight."
  },
  {
    id: "vespa-s-125",
    alsoKnownAs: ["Vespa S125", "Vespa S 125 i-get"],
    make: "Vespa",
    makeSlug: "vespa",
    model: "S 125",
    slug: "s-125",
    generation: "Current Philippine model",
    category: "Retro scooter",
    srp: 160000,
    engineCc: 124,
    powerHp: 10.2,
    torqueNm: 10.2,
    curbWeightKg: 105,
    seatHeightMm: 785,
    fuelTankL: 7.5,
    groundClearanceMm: 155,
    frontTire: "110/70-12",
    rearTire: "120/70-12",
    abs: "Front disc and rear drum; confirm exact Philippine safety-equipment configuration with the dealer",
    colors: [],
    searchVolume: 8510,
    keywordDifficulty: 0,
    sourceLabel: "Vespa Philippines current S 125 product page with APAC technical-sheet cross-check",
    sourceUrl: "https://www.vespa.com/ph_EN/models/s/",
    verifiedAt,
    freshness: "verified",
    marketStatus: "current",
    marketPriceSourceLabel: "Vespa Philippines",
    marketPriceSourceUrl: "https://www.vespa.com/ph_EN/models/s/",
    marketPriceCheckedAt: verifiedAt,
    priceContext: "Vespa Philippines currently lists the S 125 at ₱160,000 recommended retail price. Confirm final dealer charges and the exact local braking/safety specification before purchase.",
    transmission: "Automatic",
    summary: "Current Philippine 124cc Vespa entry model with CVT, 785 mm seat and ₱160,000 recommended retail price."
  }
];
