import type { Motorcycle } from "./types";

// Third October 2026 search-gap wave from the supplied ZigWheels keyword export.
// Current vs historical status is explicit so old Philippine prices never appear
// as current new-bike SRPs.
const verifiedAt = "2026-10-03";

export const zigwheelsGapWave3_2026: Motorcycle[] = [
  {
    id: "benelli-panarea-125",
    alsoKnownAs: ["Benelli Panarea125", "Panarea 125"],
    make: "Benelli",
    makeSlug: "benelli",
    model: "Panarea 125",
    slug: "panarea-125",
    generation: "Current Philippine model",
    category: "Retro scooter",
    srp: 95000,
    engineCc: 124,
    powerHp: 8.45,
    torqueNm: 9.2,
    curbWeightKg: 104,
    seatHeightMm: 760,
    fuelTankL: 4.6,
    groundClearanceMm: 135,
    frontTire: "100/90-12",
    rearTire: "110/90-12",
    abs: "No ABS stated on the official Benelli specification; front disc and rear drum",
    colors: ["Brown", "Maroon", "Red", "Blue", "Yellow"],
    searchVolume: 12970,
    keywordDifficulty: 0,
    sourceLabel: "Benelli Philippines current Panarea 125 product specification",
    sourceUrl: "https://www.benelli.com/ph-en/products/panarea-125",
    verifiedAt,
    freshness: "verified",
    marketStatus: "current",
    marketPriceSourceLabel: "Kamote.ph Philippine market reference",
    marketPriceSourceUrl: "https://www.kamote.ph/motorcycle/benelli-panarea-125",
    marketPriceCheckedAt: verifiedAt,
    priceContext: "Benelli Philippines currently maintains a Philippine Panarea 125 product page but does not publish a peso price there. MotoIndex stores ₱95,000 as a dated Philippine market reference and recommends confirming the dealer quote before purchase.",
    transmission: "Automatic",
    summary: "Current 124cc retro scooter with CVT, 104 kg curb weight, 760 mm seat, 4.6 L tank and an official Benelli Philippines model page."
  },
  {
    id: "honda-pcx150",
    alsoKnownAs: ["Honda PCX 150", "PCX 150"],
    make: "Honda",
    makeSlug: "honda",
    model: "PCX150",
    slug: "pcx150",
    generation: "Previous Philippine PCX150 generation",
    category: "Premium scooter",
    srp: 133900,
    engineCc: 150,
    powerHp: 14,
    torqueNm: 13.6,
    curbWeightKg: 131,
    seatHeightMm: 764,
    fuelTankL: 8,
    groundClearanceMm: 137,
    frontTire: "100/80-14",
    rearTire: "120/70-14",
    abs: "Front ABS with rear drum on the Philippine Standard reference",
    colors: ["Pearl White", "Black Metallic"],
    searchVolume: 12210,
    keywordDifficulty: 0,
    sourceLabel: "Historical Philippine PCX150 specification and price record",
    sourceUrl: "https://www.zigwheels.ph/new-motorcycles/honda/pcx150/standard",
    verifiedAt,
    freshness: "verified",
    marketStatus: "discontinued",
    marketPriceSourceLabel: "Honda Motor World historical Philippine dealer listing",
    marketPriceSourceUrl: "https://hondamotorworld.com/motorcycles/the-new-pcx150/",
    marketPriceCheckedAt: verifiedAt,
    priceContext: "₱133,900 is a historical Philippine PCX150 price reference. The PCX150 is discontinued, so current new-bike research belongs on the PCX160 page.",
    transmission: "Automatic",
    successorId: "honda-pcx-160",
    summary: "Discontinued 150cc PCX generation with a 764 mm seat, 131 kg curb weight, 8 L tank and front ABS; retained for owner, used-bike and predecessor research."
  },
  {
    id: "yamaha-tricity",
    alsoKnownAs: ["Yamaha Tricity 125", "Tricity 125"],
    make: "Yamaha",
    makeSlug: "yamaha",
    model: "Tricity 125",
    slug: "tricity",
    generation: "2015 Philippine Tricity 125",
    category: "Leaning multi-wheel scooter",
    srp: 146000,
    engineCc: 124.8,
    powerHp: 10.9,
    torqueNm: 10.4,
    curbWeightKg: 152,
    seatHeightMm: 780,
    fuelTankL: 6.6,
    groundClearanceMm: 120,
    frontTire: "90/80-14",
    rearTire: "110/90-12",
    abs: "Unified Braking System with dual front discs and one rear disc; no ABS claim for the Philippine 125cc launch model",
    colors: ["Matte Red", "White"],
    searchVolume: 11450,
    keywordDifficulty: 0,
    sourceLabel: "Motorcycle Philippines road test of the Philippine-market Tricity 125",
    sourceUrl: "https://www.motorcyclephilippines.com/articles/three-wheeled-wonder-yamaha-tricity/",
    verifiedAt,
    freshness: "verified",
    marketStatus: "discontinued",
    priceContext: "Historical Philippine launch SRP of ₱146,000 for the 125cc Tricity. Later overseas Tricity generations use different engines and specifications and should not be mixed into this record.",
    transmission: "Automatic",
    summary: "Discontinued Philippine 124.8cc leaning multi-wheel scooter with two front wheels, CVT, 152 kg curb weight and a 780 mm seat."
  },
  {
    id: "honda-wave125-alpha",
    alsoKnownAs: ["Honda Wave 125 Alpha", "Wave125 Alpha", "Wave 125"],
    make: "Honda",
    makeSlug: "honda",
    model: "Wave125 Alpha",
    slug: "wave125-alpha",
    generation: "Previous Philippine Wave125 Alpha generation",
    category: "Underbone",
    srp: 60900,
    engineCc: 124.8,
    powerHp: 8.71,
    torqueNm: 10.7,
    curbWeightKg: 100,
    seatHeightMm: 778,
    fuelTankL: 3.7,
    fuelConsumptionKmL: 70,
    groundClearanceMm: 157,
    frontTire: "2.50-17",
    rearTire: "2.75-17",
    abs: "No ABS; front disc and rear drum",
    colors: ["Black", "Red", "White", "Orange"],
    searchVolume: 9400,
    keywordDifficulty: 0,
    sourceLabel: "Historical Philippine Wave125 Alpha specification and buyer-guide record",
    sourceUrl: "https://www.zigwheels.ph/motorcycle-feature-stories/honda-wave-125-alpha-all-you-need-to-know",
    verifiedAt,
    freshness: "verified",
    marketStatus: "discontinued",
    marketPriceSourceLabel: "Historical Philippine buyer-guide price reference",
    marketPriceSourceUrl: "https://www.zigwheels.ph/motorcycle-feature-stories/honda-wave-125-alpha-all-you-need-to-know",
    marketPriceCheckedAt: verifiedAt,
    priceContext: "₱60,900 is a historical Philippine Wave125 Alpha price. The model is discontinued; the page remains useful for specifications, owners, parts research and used-bike shopping.",
    transmission: "Manual",
    summary: "Discontinued 124.8cc Philippine underbone with a four-speed transmission, roughly 100 kg published weight, 778 mm seat and 3.7 L fuel tank."
  },
  {
    id: "italjet-dragster-200",
    alsoKnownAs: ["Italjet Dragster", "Dragster 200"],
    make: "Italjet",
    makeSlug: "italjet",
    model: "Dragster 200",
    slug: "dragster-200",
    generation: "Current Philippine model",
    category: "Sport scooter",
    srp: 360000,
    engineCc: 181,
    powerHp: 17.5,
    torqueNm: 15.5,
    curbWeightKg: 124,
    seatHeightMm: 770,
    fuelTankL: 9,
    groundClearanceMm: 130,
    frontTire: "120/70-12",
    rearTire: "140/60-13",
    abs: "ABS with Brembo front and rear disc brakes",
    colors: ["Red", "Yellow", "Black"],
    searchVolume: 7490,
    keywordDifficulty: 0,
    sourceLabel: "Italjet current Dragster 200 technical specification with Philippine price cross-check",
    sourceUrl: "https://italjet.com/collections/italjet-dragster-125-300",
    verifiedAt,
    freshness: "verified",
    marketStatus: "current",
    marketPriceSourceLabel: "Current Philippine Dragster 200 market reference",
    marketPriceSourceUrl: "https://www.zigwheels.ph/new-motorcycles/italjet/dragster/price",
    marketPriceCheckedAt: verifiedAt,
    priceContext: "Current Philippine comparison references list the Dragster 200 at ₱360,000. Italjet's current global technical sheet identifies the 200-class engine as 181cc, so MotoIndex keeps actual displacement separate from the marketing name.",
    transmission: "Automatic",
    summary: "Current Philippine-market Dragster 200 search entity using Italjet's 181cc technical specification, with ABS, Brembo brakes, a 770 mm seat and current ₱360,000 market reference."
  },
  {
    id: "benelli-motobi-200-evo",
    alsoKnownAs: ["Benelli Motobi 200 EVO", "Motobi 200"],
    make: "Benelli",
    makeSlug: "benelli",
    model: "Motobi 200 Evo",
    slug: "motobi-200-evo",
    generation: "Philippine-market reference",
    category: "Cruiser",
    srp: 125000,
    engineCc: 197,
    powerHp: 12.7,
    torqueNm: 13.9,
    curbWeightKg: 156,
    seatHeightMm: 715,
    fuelTankL: 11.8,
    groundClearanceMm: 150,
    frontTire: "90/90-17",
    rearTire: "130/90-15",
    abs: "No ABS listed; front and rear disc brakes",
    colors: ["Black", "Green", "Silver"],
    searchVolume: 6790,
    keywordDifficulty: 0,
    sourceLabel: "Benelli Philippine Motobi 200 Evo technical specification",
    sourceUrl: "https://front30-staging.benelli.com/ph-en/products/motobi-200-evo/",
    verifiedAt,
    freshness: "verified",
    marketStatus: "uncertain",
    marketPriceSourceLabel: "Kamote.ph Philippine market reference",
    marketPriceSourceUrl: "https://www.kamote.ph/motorcycle/benelli-motobi-200-evo",
    marketPriceCheckedAt: verifiedAt,
    priceContext: "Benelli's Philippine technical page remains accessible but does not publish a current peso price. MotoIndex stores ₱125,000 as a dated secondary market reference and treats present-day new-bike availability as needing verification.",
    transmission: "Manual",
    summary: "197cc low-seat cruiser with a five-speed gearbox, 715 mm seat and 11.8 L tank; current Philippine new-bike availability should be verified before relying on the stored market price."
  },
  {
    id: "honda-cb150r",
    alsoKnownAs: ["Honda CB150R Streetfire", "CB150R Streetfire"],
    make: "Honda",
    makeSlug: "honda",
    model: "CB150R",
    slug: "cb150r",
    generation: "Previous Philippine CB150R Streetfire generation",
    category: "Naked street bike",
    srp: 116800,
    engineCc: 149.16,
    powerHp: 17,
    torqueNm: 13.8,
    curbWeightKg: 136,
    seatHeightMm: 797,
    fuelTankL: 12,
    groundClearanceMm: 169,
    frontTire: "100/80-17",
    rearTire: "130/70-17",
    abs: "No ABS asserted for the Philippine historical record; front and rear disc brakes",
    colors: [],
    searchVolume: 7990,
    keywordDifficulty: 0,
    sourceLabel: "Historical Philippine CB150R Streetfire specification record",
    sourceUrl: "https://www.zigwheels.ph/new-motorcycles/honda/cb150r-streetfire/standard",
    verifiedAt,
    freshness: "verified",
    marketStatus: "discontinued",
    priceContext: "Historical Philippine price reference retained for owner and used-bike research. MotoIndex does not treat the currently sold Indonesian CB150R Streetfire as proof of a current Honda Philippines model.",
    transmission: "Manual",
    summary: "Discontinued Philippine 149.16cc CB150R Streetfire record with a six-speed gearbox, 797 mm seat, 12 L tank and 17-inch tires."
  }
];
