import type { Motorcycle } from "./types";

// Seventh October 2026 ZigWheels keyword-gap wave.
// Current-market claims prefer first-party Philippine evidence. Models that still
// appear in comparison listings without equally clear current manufacturer
// catalog evidence stay availability-to-verify rather than being asserted current.
const verifiedAt = "2026-10-03";

export const zigwheelsGapWave7_2026: Motorcycle[] = [
  {
    id: "kawasaki-ninja-zx-10r",
    alsoKnownAs: ["Kawasaki ZX-10R", "ZX10R", "Ninja ZX10R"],
    make: "Kawasaki",
    makeSlug: "kawasaki",
    model: "Ninja ZX-10R",
    slug: "ninja-zx-10r",
    generation: "Current Philippine model",
    category: "Supersport",
    srp: 999800,
    engineCc: 998,
    powerHp: 200.21,
    torqueNm: 114.9,
    curbWeightKg: 207,
    seatHeightMm: 835,
    fuelTankL: 17,
    frontTire: "120/70 ZR17",
    rearTire: "190/55 ZR17",
    abs: "KIBS ABS with supersport electronic rider aids",
    colors: [],
    searchVolume: 3100,
    keywordDifficulty: 0,
    sourceLabel: "Kawasaki Leisure Bikes Philippines current Ninja ZX-10R product and price page",
    sourceUrl: "https://www.kawasakileisurebikes.ph/motorcycles/supersports/ninja-zx-10r/",
    verifiedAt,
    freshness: "verified",
    marketStatus: "current",
    marketPriceSourceLabel: "Kawasaki Leisure Bikes Philippines",
    marketPriceSourceUrl: "https://www.kawasakileisurebikes.ph/motorcycles/supersports/ninja-zx-10r/",
    marketPriceCheckedAt: verifiedAt,
    priceContext: "Kawasaki Leisure Bikes Philippines currently lists the Ninja ZX-10R at ₱999,800 MSRP. The published engine output is 200.21 hp, or 210.27 hp with RAM Air.",
    transmission: "Manual",
    summary: "Current 998cc Philippine supersport with 200.21 hp published output, 114.9 Nm, 835 mm seat, 17 L tank and ₱999,800 official MSRP."
  },
  {
    id: "yamaha-mt-15",
    alsoKnownAs: ["Yamaha MT15", "MT 15"],
    make: "Yamaha",
    makeSlug: "yamaha",
    model: "MT-15",
    slug: "mt-15",
    generation: "Philippine-market MT-15",
    category: "Naked street bike",
    srp: 180000,
    engineCc: 155,
    powerHp: 19,
    torqueNm: 14.7,
    curbWeightKg: 133,
    seatHeightMm: 810,
    fuelTankL: 10,
    groundClearanceMm: 155,
    frontTire: "110/70-17",
    rearTire: "140/70-17",
    abs: "No ABS listed in the current Philippine comparison-market specification",
    colors: [],
    searchVolume: 1800,
    keywordDifficulty: 0,
    sourceLabel: "Current Philippine MT-15 market and specification reference",
    sourceUrl: "https://www.zigwheels.ph/new-motorcycles/yamaha/mt-15",
    verifiedAt,
    freshness: "verified",
    marketStatus: "uncertain",
    marketPriceSourceLabel: "Current Philippine comparison-market price reference",
    marketPriceSourceUrl: "https://www.zigwheels.ph/new-motorcycles/yamaha/mt-15/price",
    marketPriceCheckedAt: verifiedAt,
    priceContext: "Current Philippine comparison listings show the MT-15 at ₱180,000, but MotoIndex did not locate equally clear current Yamaha Motor Philippines catalog evidence for this model during this check. Confirm current authorized-dealer availability before purchase.",
    transmission: "Manual",
    summary: "155cc Philippine-market naked bike with 19 hp, 14.7 Nm, six-speed transmission, 810 mm seat and current comparison-market pricing that still needs authorized-dealer verification."
  },
  {
    id: "yamaha-mt-10-sp",
    alsoKnownAs: ["Yamaha MT10 SP", "MT 10 SP"],
    make: "Yamaha",
    makeSlug: "yamaha",
    model: "MT-10 SP",
    slug: "mt-10-sp",
    generation: "Current Philippine model",
    category: "Hypernaked",
    srp: 1099000,
    engineCc: 998,
    powerHp: 163.6,
    torqueNm: 112,
    curbWeightKg: 214,
    seatHeightMm: 835,
    fuelTankL: 17,
    groundClearanceMm: 135,
    frontTire: "120/70 ZR17",
    rearTire: "190/55 ZR17",
    abs: "ABS with electronic rider-aid package",
    colors: [],
    searchVolume: 900,
    keywordDifficulty: 0,
    sourceLabel: "Yamaha Motor Philippines aftersales current-model ecosystem with Philippine market specification cross-check",
    sourceUrl: "https://aftersales.yamaha-motor.com.ph/discover-your-oil-copy/",
    verifiedAt,
    freshness: "verified",
    marketStatus: "current",
    marketPriceSourceLabel: "Current Philippine MT-10 SP price reference",
    marketPriceSourceUrl: "https://www.zigwheels.ph/new-motorcycles/yamaha/mt-10-sp/price",
    marketPriceCheckedAt: verifiedAt,
    priceContext: "Yamaha Motor Philippines' current aftersales model selector includes MT10 SP. Current Philippine comparison listings place the MT-10 SP at ₱1,099,000; confirm the final authorized-dealer quote before purchase.",
    transmission: "Manual",
    summary: "Current 998cc Philippine hypernaked with 163.6 hp, 112 Nm, 835 mm seat, 17 L tank, ABS and a ₱1.099M current Philippine price reference."
  },
  {
    id: "yamaha-tenere-700",
    alsoKnownAs: ["Yamaha Ténéré 700", "Tenere 700", "T7"],
    make: "Yamaha",
    makeSlug: "yamaha",
    model: "Ténéré 700",
    slug: "tenere-700",
    generation: "Current Philippine model",
    category: "Adventure touring",
    srp: 669000,
    engineCc: 689,
    powerHp: 72,
    torqueNm: 68,
    curbWeightKg: 204,
    seatHeightMm: 875,
    fuelTankL: 16,
    groundClearanceMm: 240,
    frontTire: "90/90-21",
    rearTire: "150/70-18",
    abs: "Adventure braking package; confirm exact current-model ABS settings with the dealer",
    colors: [],
    searchVolume: 700,
    keywordDifficulty: 0,
    sourceLabel: "Yamaha Motor Philippines aftersales current-model ecosystem with Philippine market specification cross-check",
    sourceUrl: "https://aftersales.yamaha-motor.com.ph/discover-your-oil-copy/",
    verifiedAt,
    freshness: "verified",
    marketStatus: "current",
    marketPriceSourceLabel: "Current Philippine Ténéré 700 price reference",
    marketPriceSourceUrl: "https://www.zigwheels.ph/new-motorcycles/yamaha/tenere-700/price",
    marketPriceCheckedAt: verifiedAt,
    priceContext: "Yamaha Motor Philippines' current aftersales model selector includes TÉNÉRÉ 700. Current Philippine comparison listings place the model at ₱669,000; confirm the current dealer quote and exact model-year electronics before purchase.",
    transmission: "Manual",
    summary: "Current 689cc Philippine adventure bike with 72 hp, 68 Nm, 21/18-inch wheels, 240 mm ground clearance, 875 mm seat and a 16 L tank."
  },
  {
    id: "yamaha-xsr900",
    alsoKnownAs: ["Yamaha XSR 900", "XSR 900"],
    make: "Yamaha",
    makeSlug: "yamaha",
    model: "XSR900",
    slug: "xsr900",
    generation: "Current Philippine model",
    category: "Sport heritage",
    srp: 729000,
    engineCc: 890,
    powerHp: 117,
    torqueNm: 93,
    curbWeightKg: 193,
    seatHeightMm: 810,
    fuelTankL: 14,
    groundClearanceMm: 140,
    frontTire: "120/70 ZR17",
    rearTire: "180/55 ZR17",
    abs: "ABS with current-generation electronic rider aids",
    colors: [],
    searchVolume: 1800,
    keywordDifficulty: 0,
    sourceLabel: "Yamaha Motor Philippines current aftersales model reference with Philippine market specification cross-check",
    sourceUrl: "https://aftersales.yamaha-motor.com.ph/discover-your-oil-copy/",
    verifiedAt,
    freshness: "verified",
    marketStatus: "current",
    marketPriceSourceLabel: "Current Philippine XSR900 price reference",
    marketPriceSourceUrl: "https://www.zigwheels.ph/new-motorcycles/yamaha/xsr900/price",
    marketPriceCheckedAt: verifiedAt,
    priceContext: "Yamaha Motor Philippines' current aftersales content references XSR900. Current Philippine comparison listings place the XSR900 at ₱729,000; confirm the final authorized-dealer quote before purchase.",
    transmission: "Manual",
    summary: "Current 890cc Philippine sport-heritage triple with 117 hp, 93 Nm, 810 mm seat, 14 L tank and current ₱729,000 market reference."
  },
  {
    id: "yamaha-sr400",
    alsoKnownAs: ["Yamaha SR 400"],
    make: "Yamaha",
    makeSlug: "yamaha",
    model: "SR400",
    slug: "sr400",
    generation: "2019 Philippine-market generation",
    category: "Classic street bike",
    srp: 329000,
    engineCc: 399,
    powerHp: 22.9,
    torqueNm: 27.4,
    curbWeightKg: 174,
    seatHeightMm: 785,
    fuelTankL: 12,
    groundClearanceMm: 130,
    frontTire: "90/100-18",
    rearTire: "110/90-18",
    abs: "No ABS listed; front disc and rear drum",
    colors: ["Galaxy Blue Metallic"],
    searchVolume: 900,
    keywordDifficulty: 0,
    sourceLabel: "Philippine SR400 historical/current-market comparison reference",
    sourceUrl: "https://www.zigwheels.ph/new-motorcycles/yamaha/sr400",
    verifiedAt,
    freshness: "verified",
    marketStatus: "uncertain",
    marketPriceSourceLabel: "Philippine comparison-market SR400 price reference",
    marketPriceSourceUrl: "https://www.zigwheels.ph/new-motorcycles/yamaha/sr400/price",
    marketPriceCheckedAt: verifiedAt,
    priceContext: "Philippine comparison listings still show ₱329,000, but the same source identifies the latest Philippine model as the 2019 model year. MotoIndex therefore treats new-unit availability and the quoted price as needing direct dealer verification.",
    transmission: "Manual",
    summary: "399cc classic single-cylinder SR400 with a 785 mm seat, 12 L tank and 2019-generation Philippine specifications; current new-unit availability needs verification."
  },
  {
    id: "honda-crf250-rally",
    alsoKnownAs: ["Honda CRF250L Rally", "CRF 250 Rally"],
    make: "Honda",
    makeSlug: "honda",
    model: "CRF250 Rally",
    slug: "crf250-rally",
    generation: "Previous Philippine 250cc Rally generation",
    category: "Dual-sport adventure",
    srp: 284900,
    engineCc: 250,
    powerHp: 22.8,
    torqueNm: 22,
    curbWeightKg: 144,
    seatHeightMm: 874,
    fuelTankL: 10.1,
    groundClearanceMm: 270,
    frontTire: "3.00-21",
    rearTire: "120/80-18",
    abs: "Variant/model-year dependent; historical Philippine references include disc brakes and later ABS variants",
    colors: ["Red"],
    searchVolume: 3500,
    keywordDifficulty: 0,
    sourceLabel: "Historical Philippine CRF250 Rally buyer-guide specification and launch coverage",
    sourceUrl: "https://www.topgear.com.ph/buyers-guide/motorcycles/honda/crf250-rally",
    verifiedAt,
    freshness: "verified",
    marketStatus: "discontinued",
    successorId: "honda-crf300-rally",
    marketPriceSourceLabel: "2019 Philippine historical buyer-guide price",
    marketPriceSourceUrl: "https://www.topgear.com.ph/buyers-guide/motorcycles/honda/crf250-rally",
    marketPriceCheckedAt: verifiedAt,
    priceContext: "The stored ₱284,900 figure is a historical 2019 Philippine price, not a current dealer quote. The CRF250 Rally is discontinued in the Philippines; current new-bike research should move to the CRF300 Rally.",
    transmission: "Manual",
    summary: "Discontinued 250cc Philippine rally-style dual sport with historical ₱284,900 pricing, 21/18-inch wheels and CRF300 Rally as the current successor research path."
  }
];
