"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
export type PriceRow = { id: string; model: string; brand: string; category: string; engine: number; price: number; priceLabel: string; href: string };
export function PriceList({ rows }: { rows: PriceRow[] }) {
  const [query,setQuery]=useState("");const [brand,setBrand]=useState("");const [sort,setSort]=useState("model");const [descending,setDescending]=useState(false);const [page,setPage]=useState(1);const [ready,setReady]=useState(false);
  useEffect(()=>setReady(true),[]);
  const brands=[...new Set(rows.map(row=>row.brand))].sort();
  const filtered=useMemo(()=>rows.filter(row=>(!brand||row.brand===brand)&&`${row.model} ${row.brand} ${row.category}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>{const direction=descending?-1:1; if(sort==="price")return(a.price-b.price)*direction;if(sort==="engine")return(a.engine-b.engine)*direction;return String(a[sort as "model"|"brand"|"category"]).localeCompare(String(b[sort as "model"|"brand"|"category"]))*direction;}),[rows,brand,query,sort,descending]);
  const pageCount=Math.max(1,Math.ceil(filtered.length/18));
  function order(key:string){setDescending(sort===key?!descending:false);setSort(key);setPage(1);}
  return <div className="wf-price-list"><div className="wf-filter-tabs" role="group" aria-label="Filter prices by brand"><button aria-pressed={!brand} onClick={()=>{setBrand("");setPage(1);}}>All brands</button>{brands.map(value=><button key={value} aria-pressed={brand===value} onClick={()=>{setBrand(value);setPage(1);}}>{value}</button>)}</div><div className="wf-controls"><label className="wf-search"><span className="sr-only">Search price list</span><input type="search" value={query} placeholder="Search models..." onChange={e=>{setQuery(e.target.value);setPage(1);}} /></label><button type="button" className="button" onClick={()=>window.print()}>Download price list PDF</button></div><p role="status">{filtered.length} current models{ready?` · Page ${page} of ${pageCount}`:""}</p><div className="wf-table-scroll"><table className="wf-price-table"><caption className="sr-only">Current Philippine motorcycle prices and specifications</caption><thead><tr>{[["model","Model"],["brand","Brand"],["category","Category"],["engine","Displacement (cc)"],["price","SRP (₱)"]].map(([key,label])=><th key={key} scope="col" aria-sort={sort===key?(descending?"descending":"ascending"):"none"}><button type="button" onClick={()=>order(key)}>{label} {sort===key?(descending?"↓":"↑"):"↕"}</button></th>)}</tr></thead><tbody>{filtered.map((row,index)=><tr key={row.id} hidden={ready&&(index<(page-1)*18||index>=page*18)}><th scope="row"><Link href={row.href}>{row.model}</Link></th><td>{row.brand}</td><td>{row.category}</td><td>{row.engine}</td><td>{row.priceLabel}</td></tr>)}</tbody></table></div>{!filtered.length&&<p>No models match. Try a different brand or search.</p>}<nav className="wf-pagination" aria-label="Price list pagination"><button type="button" disabled={page<=1} onClick={()=>setPage(p=>p-1)}>Previous</button><span>{page} / {pageCount}</span><button type="button" disabled={page>=pageCount} onClick={()=>setPage(p=>p+1)}>Next</button></nav><p className="wf-print-note">PDF export opens your browser’s print dialog. Choose “Save as PDF” to download the full filtered list.</p></div>;
}
