const fs=require('node:fs');const path=require('node:path');const {loadTypeScript}=require("./load-typescript.cjs");const ts=loadTypeScript();
const root=process.cwd();
const required=['lib/sellers.ts','lib/ingestion.ts','components/PriceAlertForm.tsx','components/OfferImportPreview.tsx','app/sellers/page.tsx','app/sellers/[slug]/page.tsx','app/dealers/[city]/page.tsx','app/api/price-alerts/route.ts','app/admin/ingestion/page.tsx','app/api/ingestion/validate/route.ts'];
for(const f of required)if(!fs.existsSync(path.join(root,f)))throw new Error(`Missing ${f}`);
const alert=fs.readFileSync(path.join(root,'app/api/price-alerts/route.ts'),'utf8');if(!alert.includes('persisted:false'))throw new Error('Prototype alert no-persistence safety missing');
const sellerPage=fs.readFileSync(path.join(root,'app/sellers/[slug]/page.tsx'),'utf8');if(!sellerPage.includes('index:false'))throw new Error('Demo seller noindex gate missing');
const sitemap=fs.readFileSync(path.join(root,'app/sitemap.ts'),'utf8');if(!sitemap.includes('filter(s=>!s.isDemo)'))throw new Error('Demo seller sitemap exclusion missing');
const schema=fs.readFileSync(path.join(root,'prisma/schema.prisma'),'utf8');for(const m of ['model PriceAlertSubscription ','model OfferImportBatch '])if(!schema.includes(m))throw new Error(`Missing ${m}`);
const files=[];function walk(d){for(const e of fs.readdirSync(d,{withFileTypes:true})){const p=path.join(d,e.name);if(e.isDirectory())walk(p);else if(/\.(ts|tsx)$/.test(e.name)&&!e.name.endsWith('.d.ts'))files.push(p)}}for(const d of ['app','components','lib'])walk(path.join(root,d));let errs=[];for(const f of files){const text=fs.readFileSync(f,'utf8');const out=ts.transpileModule(text,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext,jsx:ts.JsxEmit.Preserve},reportDiagnostics:true,fileName:f});for(const d of out.diagnostics||[])if(d.category===ts.DiagnosticCategory.Error)errs.push(`${path.relative(root,f)}: ${ts.flattenDiagnosticMessageText(d.messageText,' ')}`)}if(errs.length)throw new Error(errs.join('\n'));console.log(`v0.7 validation passed: ${files.length} TS/TSX source files parsed; seller, alert and ingestion gates present.`);
