import fs from "node:fs";
import path from "node:path";
const root=process.cwd(), failures=[];
const read=p=>fs.readFileSync(path.join(root,p),"utf8"), exists=p=>fs.existsSync(path.join(root,p)), assert=(c,m)=>{if(!c)failures.push(m)};
const pkg=JSON.parse(read("package.json"));
const [pkgMajor19,pkgMinor19]=String(pkg.version||"0.0.0").split(".").map(Number);
assert(pkgMajor19>1||(pkgMajor19===1&&pkgMinor19>=9),`package version should be v1.9 or newer, found ${pkg.version}`);
assert(pkg.scripts?.["validate:v19"]==="node scripts/validate-v19.mjs","validate:v19 script missing");
assert(pkg.scripts?.["validate:all"]?.includes("validate:v19"),"validate:all does not include v1.9");
const required=["lib/commute.ts","lib/commuteMath.ts","components/CommuteCostCalculator.tsx","components/AffordabilityCalculator.tsx","components/CommuteSnapshot.tsx","components/CommuteRankCard.tsx","app/commute/page.tsx","app/commute/[slug]/page.tsx","app/commute/cost-calculator/page.tsx","app/commute/affordability/page.tsx","app/commute/rainy-season/page.tsx","COMMUTE_SOURCES_V19.md","V19_BUILD_SUMMARY.md"];
for(const f of required)assert(exists(f),`missing ${f}`);
const commute=read("lib/commute.ts")+read("lib/commuteMath.ts");
for(const t of ["heavy-traffic","affordable-under-80k","delivery-riders","passenger-commute","commuteMonthlyCosts","maxPurchasePriceFromBudget","20","22"])assert(commute.includes(t),`commute layer missing ${t}`);
const cost=read("components/CommuteCostCalculator.tsx");
for(const t of ["Round trip / day","Commute days / month","Gasoline assumption","Parking / day","Maintenance reserve / month","Current commute spend / day","Vs current commute","Cost per"])assert(cost.includes(t),`commute calculator missing ${t}`);
const afford=read("components/AffordabilityCalculator.tsx");
for(const t of ["Monthly take-home pay","motorcycle budget cap","Running-cost reserve","Cash down payment","APR assumption","Maximum modeled purchase price","Estimate only."])assert(afford.includes(t),`affordability tool missing ${t}`);
const finder=read("components/MotorcycleFinder.tsx");
for(const t of ["Daily round trip","finder-commute-cost","commuteMonthlyCosts","daily_km"])assert(finder.includes(t),`finder commute integration missing ${t}`);
const modelRoute=read("app/motorcycles/[make]/[slug]/page.tsx");const model=modelRoute+(modelRoute.includes("MotorcycleEntityPage")&&exists("components/MotorcycleEntityPage.tsx")?read("components/MotorcycleEntityPage.tsx"):"");assert(model.includes("CommuteSnapshot"),"canonical model page missing commute snapshot");
const search=read("lib/searchQuery.ts")+read("components/SearchClient.tsx")+read("lib/search.ts");
for(const t of ["trafficFriendly","delivery rider","/commute/cost-calculator","/commute/affordability"])assert(search.includes(t),`search commute intent missing ${t}`);
const nav=read("components/Header.tsx")+read("components/Footer.tsx")+read("app/page.tsx");assert(nav.includes('href="/commute"'),"commuter hub missing from site navigation");
const sitemap=read("lib/sitemaps.ts");for(const t of ["/commute","/commute/cost-calculator","/commute/affordability","/commute/rainy-season","commuteGuides"])assert(sitemap.includes(t),`sitemap commute coverage missing ${t}`);
const rain=read("app/commute/rainy-season/page.tsx");for(const t of ["Ground clearance is not a flood-depth rating","Do not infer wading depth","safer decision can be not to enter"])assert(rain.includes(t),`rainy-season safety boundary missing ${t}`);
const launch=read("scripts/check-launch.mjs");assert(launch.includes("parts[2] > 23"),"launch guard must require a post-15.5.23 security patch after Aug 26");
const codeFiles=["lib/commute.ts","lib/commuteMath.ts","components/CommuteCostCalculator.tsx","components/AffordabilityCalculator.tsx","components/CommuteSnapshot.tsx","components/CommuteRankCard.tsx","components/MotorcycleFinder.tsx","lib/searchQuery.ts","app/commute/page.tsx","app/commute/[slug]/page.tsx","app/commute/cost-calculator/page.tsx","app/commute/affordability/page.tsx","app/commute/rainy-season/page.tsx"].map(read).join("\n");assert(!/\/price-history\b|PriceHistoryChart|historical price chart/i.test(codeFiles),"v1.9 accidentally added price history");
const css=read("app/globals.css");for(const c of [".commute-hero-grid",".commute-rank-card",".commute-calculator",".affordability-tool",".rain-check-grid",".commute-snapshot"])assert(css.includes(c),`v1.9 styling missing ${c}`);
if(failures.length){console.error(`v1.9 validation failed (${failures.length}):`);for(const f of failures)console.error(`- ${f}`);process.exit(1)}
console.log("v1.9 validation passed: Philippines-first commute hub, cost/affordability tools, heavy-traffic/work/passenger rankings, rainy-season safety boundary, finder/search/model integration and stricter launch security baseline are present; legacy demo/marketplace price history remains excluded.");
